### ISSUE TITLE
re: colormyworld

### ISSUE THREAD

**Issue by ccosse** [llaske/sugarizer#100]
Hi, I've been working on ColorMyWorld and it's getting very close.  It's playable and is supporting 8 languages (en,fr,de,it,gr,cn,th,sw) and 4 data regions (Africa, Europe, World, Caribbean).  I could use help understanding the palette system.  Alternatively could use a slide-out panel with some toggles and buttons to clear-up the toolbar.  -C

**Comment by llaske** [comment]
Very nice Charles. I'm going to add Color palette for you. I will send you a PR on your repository.

**Comment by ccosse** [comment]
Okay, I'm close to making another significant release ... probably the end for a while.  I have broken-apart the world into 11 regions (africa, europe, middle east, asia, caribbean, north america, central america, south america, australia, islands and antactica) and allowing the user to toggle them on/off independently, so can have the whole world by toggling all "on".  Each time a toggle changes it re-calculates the bounding box and re-positions the map.  

Is the palette functionality you are thinking of in order for child to click-and-color countries?  That would be a good activity ... otherwise currently it's using random colors as you can see.  I tried to copy/understand the use of "invokers"by studying the Speak.activity but started thinking that it was derived from something more fundamental, in the way that ActivityTemplate is similar to volojs ... so that's when I wrote that I could "use some help" understanding ... i.e. does the palette system derive from something external that would be useful to study?  Thanks!

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/a2d6a5616be2199b397016d504c453f399f02822
