### ISSUE TITLE
Off-center pictures in Abecedarium Activity

### ISSUE THREAD

**Issue by Shreyas-SAS** [llaske/sugarizer#1001]
**ISSUE:** 
pictures in the blocks are off centered and aligned more towards the left due to its margin as portrayed in the picture below. 

![image](https://user-images.githubusercontent.com/96542494/158179557-5c0012aa-95f3-42df-9a3f-3ee00b71b290.png)

**PROPOSAL:** 
Centre align the pictures in the block by using appropriate margin. (In case not done intentionally)

**Comment by llaske** [comment]
Make sense.

**Comment by llaske** [comment]
Fix in https://github.com/llaske/sugarizer/pull/1015
