### ISSUE TITLE
MediaViewer activity empty.

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#1003]
The mediaviewer activity shows an empty page with no option of adding media to be viewed. The readme file too is empty and doesn't shed light on what the activity actually intends to do and how to use it. Also as the help button is missing, there is no way of knowing about the activity and its functions.
![Empty mediaviewer activity](https://user-images.githubusercontent.com/89119829/158320920-8a87944f-e0f6-41c0-beea-91d41794be24.jpg)

**Comment by llaske** [comment]
It's deliberate. MediaViewer activity is not intended to be launch alone. It's a viewer for existing media content in the Journal.

**Comment by AnandChourasia007** [comment]
In that case, I think it would be helpful to users if this information is written somewhere like a help button or the future contributors if this is mentioned int the readme file for the activity.
What do you think, @llaske ?

**Comment by llaske** [comment]
Hmmm. Why not. It could be an icon + a localized message in the background like the one when the Journal is empty.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/981841/158604534-33a89060-7aba-4617-8502-05bcda27a999.png">

**Comment by AnandChourasia007** [comment]
Sure. I get it. I will do this and submit a PR soon.

**Comment by AnandChourasia007** [comment]
Hey @llaske , is this good?
![MediaViewer empty message](https://user-images.githubusercontent.com/89119829/158663864-ccd741dc-b5ef-4dd7-b840-0ef83e393a64.jpg)

**Comment by llaske** [comment]
That's the idea 
The message should be more simple: "Please open an existing media from the Journal".

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1081
