### ISSUE TITLE
Paint activity, filter activity options not clear.

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#1004]
In the paint activity, under the filter activity there are two options. However, there is no tooltip explaining what they do nor the help button explains it during the tutorial. Suggesting a very minor enhancement, i.e. simple tooltips explaining what they do.

**Comment by disha1202** [comment]
Hello,
I would like to work on this issue.
Can you please assign it to me.

**Comment by AnandChourasia007** [comment]
Hey @disha1202 , Sorry but I am working on this issue and already have a PR for it.

**Comment by llaske** [comment]
Fix in https://github.com/llaske/sugarizer/pull/1005

**Comment by llaske** [comment]
Please don't close the issue until a version with this fix is release.
