### ISSUE TITLE
PhysicsJS activity delete items issue

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#1006]
In the physicsJS activity, the clear function is not working properly. 
Expected behaviour: After clicking the clear button and then clicking on any item on the board, that particular item should get deleted.
Actual behaviour: The item doesn't get deleted,  and  instead an item just above it gets deleted (if present).

https://user-images.githubusercontent.com/89119829/158358745-d54c78d1-6000-4f34-bde5-3d9e1d523019.mp4

**Comment by codebloded** [comment]
Are you working on this issue? @AnandChourasia007

**Comment by AnandChourasia007** [comment]
Yes

**Comment by llaske** [comment]
@AnandChourasia007 I can't reproduce the issue.
Could you explain how to do this?

**Comment by AnandChourasia007** [comment]
@llaske , I checked this bug some more and found that this issue is only when using edge and chrome. On Firefox, delete activity works fine.
On edge and chrome, the clicks dont work the same everywhere on the object. Clicking on the upperhalf deletes the object above the current object. Clicking on the lower half actually works as expected and clicking on any spot in the lower half of the object deletes it.

**Comment by llaske** [comment]
Okay I see. I think that it's because to identify the item clicked, the activity check for the box around the item.
Of course for circle item it means that you could delete an item by clicking outside of the item.
It doesn't depend of the browser.
I don't consider it as a bug.

**Comment by AnandChourasia007** [comment]
I shall close this issue then. Thanks.
