### ISSUE TITLE
Improving Design in Calligra activity

### ISSUE THREAD

**Issue by Shreyas-SAS** [llaske/sugarizer#1016]
The **current Calligra Activity homepage** is totally dominated by the user base color as seen below:

![image](https://user-images.githubusercontent.com/96542494/158754341-b7aad7ce-b1a0-4e9f-8852-ad62c2a2cd71.png)

**Suggestion:** Using Box background on each letter to make the UI better looking.

**Proposed change:**
![image](https://user-images.githubusercontent.com/96542494/158754613-610b0bc1-0764-44ff-bd0f-6a39492d942e.png)

**_Additional Tasks:_**
Add Hover effect on each letter.

**Comment by llaske** [comment]
The use of buddy color is what's expected for Sugarizer activities.
It allow users to customize activities without coding. It's the case in most activities.
This behavior is by design.

**Comment by Shreyas-SAS** [comment]
> The use of buddy color is what's expected for Sugarizer activities. It allow users to customize activities without coding. It's the case in most activities. This behavior is by design.

oh. Its just that I thought that it was too overwelming to see at first but if it is done to serve a purpose I will leave it as it is. 
It does look nice even without it. 

Thank you for informing me beforehand. 
I will try to contribute in every other way possible.
