### ISSUE TITLE
Improvement in Exercise Cards in Exerciser Activity 

### ISSUE THREAD

**Issue by gitkaarma** [llaske/sugarizer#1020]
To open an activity we have to click on the play button itself. Intuitively, the exercise should open on clicking anywhere on the card. 

https://user-images.githubusercontent.com/96700361/158371350-a0a38372-6885-45db-8396-85eae9f5870d.mp4

Also adding hover effect on particular card would help the user. 

https://user-images.githubusercontent.com/96700361/158371369-673ab9eb-b56a-42b8-8a22-70a94c76f8c3.mp4

@llaske PTAL! 
I would like to work on this.

**Comment by Shreyas-SAS** [comment]
> Also adding hover effect on particular card would help the user.

@gitkaarma I feel like I have seen this issue before, is it that you have posted it before and reposted now or has it been repeated by mistake. can you please check previous issues to see if its already addressed or fresh one.

**Comment by gitkaarma** [comment]
Yep! I posted a similar issue on exerciser git repo, but I got no reply there.

**Comment by Shreyas-SAS** [comment]
> Yep! I posted a similar issue on exerciser git repo, but I got no reply there. 

Oh that's why i felt like I have seen it somewhere. 
Lets see what @llaske sir says about the feature.
