### ISSUE TITLE
Improvement in Results Section in Exerciser Activity 

### ISSUE THREAD

**Issue by gitkaarma** [llaske/sugarizer#1021]
![image](https://user-images.githubusercontent.com/96700361/158111219-69dc6bd2-f642-4655-bf2c-849cecd05587.png)

The three icons on the left doesn't seem very intuitive to first time users. Neither there is a description of what they do nor their description pops when we hover over them.  Adding tooltips would help.

**Comment by gitkaarma** [comment]
@llaske I would like to work on this.

**Comment by gitkaarma** [comment]
@llaske, where the PR's of exerciser app, should be made?

**Comment by llaske** [comment]
PR for Exerciser should be made directly on Exerciser repo https://github.com/llaske/ExerciserReact
