### ISSUE TITLE
Food Chain Activity: build: Fix Alignment to improve UI

### ISSUE THREAD

**Issue by Shreyas-SAS** [llaske/sugarizer#1023]
Proposed:

1. Change element alignment in the play area to center images vertically from the current (offset) position that does not look good right now using padding in canvas box.
2. Apply a small margin to center the box that is currently left aligned.

Current:
![image](https://user-images.githubusercontent.com/96542494/159209447-1737a011-e675-483d-9f06-e1c703077f7b.png)

Proposed:
![image](https://user-images.githubusercontent.com/96542494/159209403-d31f9dfa-7a05-41d3-9364-967371ad2aea.png)

**Comment by llaske** [comment]
I'm not convince that it's better.
Elements look like cards, IRL cards will not be set on the middle.

**Comment by Shreyas-SAS** [comment]
> I'm not convince that it's better. Elements look like cards, IRL cards will not be set on the middle.

@llaske sir, I bet to differ to the concept of non alignment even if the elements are taken as cards. the uniformity in space above and below will make a lot of difference. 

1. using padding properly also emphasis it to be an order of food chain aligned in a line rather just a bunch of pictures sticking to the top border. moreover, having proper space gives a better picture of all the options we have in our hand over the previous alignment that failed to give any such importance to the cards.

2. supporting point 2 of the proposal, addition of margin brings the focus to the content much better than the unequal border box margin that made the left border to stick to the left side of window and even be hard to detect. also the difference of 1% made one side border visible and other was mixed up with window.

**Comment by Shreyas-SAS** [comment]
> I'm not convince that it's better. 

If you still feel that the previous version of the UI was better than the central aligned one then I will respect your view and step down to contribute in another issue happily.

**Comment by llaske** [comment]
I hear your argument but I don't think it's better.

**Comment by Shreyas-SAS** [comment]
> I hear your argument but I don't think it's better.

Oh ok. Thank you for your precious time @llaske sir. I will surely help with any other issue possible.
