### ISSUE TITLE
Implode Activity: fix Warning message button alignment 

### ISSUE THREAD

**Issue by Shreyas-SAS** [llaske/sugarizer#1025]
**Proposed:**
Currently the warning message that comes up in implode activity when there are no possible moves left has a continue button that is left aligned on larger screens and behaves well on smaller ones. 
I would like to center the text Continue so that the button looks much more formal and not like a bug.

It is a small change but I feel that it makes a large visual difference as misalignment is easily noticeable.

**Current:**
![image](https://user-images.githubusercontent.com/96542494/159289395-f676a6dc-9046-4fe6-a84b-d31af21c5785.png)

**proposed:**
![image](https://user-images.githubusercontent.com/96542494/159290317-61851879-c103-44ba-b495-e31e71035f54.png)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1026

**Comment by AnandChourasia007** [comment]
Hey @Shreyas-SAS , you are not supposed to close solved issue with 'to be release' label before release of the next version of sugarizer.

**Comment by Shreyas-SAS** [comment]
> Hey @Shreyas-SAS , you are not supposed to close solved issue with 'to be release' label before release of the next version of sugarizer.

Oh is it. Sorry it just slipped off my mind. Thanks. I will repen it.
