### ISSUE TITLE
Absence of Settings Button from List View

### ISSUE THREAD

**Issue by gitkaarma** [llaske/sugarizer#1027]
There is no option to change settings in the list view.
I was unable to find the multi-language support setting since I preferred List view over Favorites view. 

A settings button in the Navbar would prove to be useful to users who prefer  List view.

**Comment by llaske** [comment]
Settings is related to the user so it comes only when the buddy icon that represent the user is visible.
It's why it's possible only on Favorites view or in Neighborhood view.

**Comment by gitkaarma** [comment]
Rightly said. So can we add the buddy icon in the List view?

**Comment by llaske** [comment]
@gitkaarma Sugarizer design tend to limit number of icons to simplify the UI.
So only important/often used icons should be add in the toolbar. I don't think we need the Settings feature here.
> “Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.” _(Saint-Exupéry)_
