### ISSUE TITLE
Add an activity to teach the Flags of the World (Flags Quiz)

### ISSUE THREAD

**Issue by MahmoudDawood** [llaske/sugarizer#1028]
Flags of the World is a very important knowledge especially for children, which could be achieved through a simple, fun quiz or game falling under the categories **Explore**, **Games**.

Use case:
- The student starts the quiz.
- A random flag is shown with four countries choices, one true answer among them.
- After he picks one of them, the true answer is revealed to him.
- Next button appears to get the next question.

Design overview:

- Simple for children to get the idea with only an option to select an answer and go next.
- A bit colorful to grab their attention and be enjoyable (What's more colorful than flags xD)
- A satisfying sound could be added on getting the right answer, and a low tone sound for wrong ones.

Cases samples from a flags of the world quiz :

A question
![ex1](https://user-images.githubusercontent.com/30799773/159345554-339bf349-f1e0-4c61-87c2-9f5643e13f90.PNG)

Wrong answer case
![ex2](https://user-images.githubusercontent.com/30799773/159345570-6522b8af-7fb8-4521-bd95-13a94c2bf933.PNG)

Right answer case
![ex3](https://user-images.githubusercontent.com/30799773/159345588-5ae01e07-fec8-4893-a126-5865459af6f7.PNG)

The quiz could be more interesting and fun by adding:
- Specific number of questions per quiz and the total final result at the end
- Personal high score record, or a server high score.
- A timer per question to add even more excitement

I would love to hear your thoughts about this activity and if we should consider adding it to sugarizer?

Inspiration: [Flags of the World](https://world-geography-games.com/en/flags_world.html)

**Comment by Shreyas-SAS** [comment]
@MahmoudDawood Don't get me wrong but of what I feel it will be much easier and less time consuming to rather add this as a MCQ quiz under Exersizer activity rather than creating a whole activity from scratch around it.

This will only take around 1-2 hr to add all the 197 (not fixed) countries rather than code a whole activity on your own from scratch.

It will save you a lot of time and allow you to work on other projects as well. What do you say?

**Comment by Shreyas-SAS** [comment]
![image](https://user-images.githubusercontent.com/96542494/159428811-5a1de347-42c3-4ddb-8994-e73875568eb4.png)

it took less than a minute to create 1 page if you have the flag image.
Apart from just a quiz, it also has an analysis page which saves a lot of time and helps track progress.

I really appreciate your hard work and suggestion but would love to save your time on a task already possible. I really hope we can together contribute on further projects if not this one.

**Comment by llaske** [comment]
@Shreyas-SAS good point.
Plus Flags are already visible in the Color My World activity.

**Comment by MahmoudDawood** [comment]
@Shreyas-SAS You're totally right, Thank you for notifying me with the Exerciser activity.
If I had a valid big activity idea I'd ask for your help for sure.

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS You're totally right, Thank you for notifying me with the Exerciser activity.
> If I had a valid big activity idea I'd ask for your help for sure.

Thank you for understanding. Hope to work with you soon.

**Comment by MahmoudDawood** [comment]
@llaske I've already browsed Color My World before making the issue but couldn't find Flags in it if I saw it right.
So would you think of adding this idea as a quiz inside the Exerciser activity as Shreyas-SAS mentioned an added value to the activity and learning or should we leave it as it is?

**Comment by llaske** [comment]
@MahmoudDawood Flags are display in Color My World when clicking on countries.
As @Shreyas-SAS said, anyone could add a new exercise in Exerciser activities to recognize flags. We don't need to provide it.
