### ISSUE TITLE
Merging Moon Activity into planets 

### ISSUE THREAD

**Issue by Shreyas-SAS** [llaske/sugarizer#1031]
**Observation:**
Of what I have understood after trying both the activities moon as well as planets is that either of them are purely data based activities and do not have much interaction, other than changing sides in moon and rotating the 3D models of planets.

The activities are too similar in purpose and UI, the only difference being the possible interactions of rotation in planets and the latitude longitude feature in moon. If these are kept apart these seems no such reason why they are even made into two parts.

**Suggestion:** 
Merge the activity into a single part as there is no need for 2 separate activities if it can be attained in 1 single activity..

---
I really liked the line by @llaske  sir in one of the other issues and feel that it really suits the suggestion of this issue too.
> “Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.” (Saint-Exupéry)

**Comment by llaske** [comment]
By definition, the Moon is not a planet... there is lot of moons in the solar system (Callisto, Titan, Europa, ...).

**Comment by llaske** [comment]
I'm not in favor of merging the two activities.
It's not the same thing.

**Comment by Shreyas-SAS** [comment]
> I'm not in favor of merging the two activities.

Oh. Ok. Then 1 last suggestion. We have covered planets and we have covered moon but sun is missing. Can we just create a sun activity just like moon activity. We only need to change the image and some code. What do you say @llaske sir?

**Comment by llaske** [comment]
No a Sun activity is not need.

**Comment by Shreyas-SAS** [comment]
> No a Sun activity is not need.

Oh. Thank you @llaske for your precious time. I will surely help with any other issues that I can help with.
