### ISSUE TITLE
Fractions Activity: Add score counter

### ISSUE THREAD

**Issue by Shreyas-SAS** [llaske/sugarizer#1032]
Issue: 
There seems to be no score counter in Fractions activity but only a check list on the top-left corner.

Suggestion: 
Add a score display so that progress can be better mapped using high scores and motivate kids to score higher.

**Comment by Shreyas-SAS** [comment]
@llaske please have a look once if this would be a good issue to resolve since we have a table already but not a score to map the number of correct answers.

**Comment by llaske** [comment]
Why not? Let's suggest a nice place and design to add the current score.

**Comment by Shreyas-SAS** [comment]
> Why not? Let's suggest a nice place and design to add the current score.

thank you for your confirmation. I will be working on the issue asap and put a PR soon.

**Comment by Shreyas-SAS** [comment]
I am not able to work on the issue at the moment due to some academic commitments so if anyone is interested in working on the issue please feel free.

**Comment by Shreyas-SAS** [comment]
> I am not able to work on the issue at the moment due to some academic commitments so if anyone is interested in working on the issue please feel free.

I will continue to work on the issue.

**Comment by Shreyas-SAS** [comment]
> Hlo @Shreyas-SAS if you don't mind can I work on this issue. My suggestion is I have observed that in fraction activity at each turn we have 10 chances so the max high score can be 10 so is it okay to display just score each time. I tried to display the score in the following way(i.e on the top right side in case of mobile we can change its position to center) the score is set to 0/10 at the start of each turn. @llaske please share your view on this changes.
> 
> ![Screenshot (128)](https://user-images.githubusercontent.com/101845170/217252867-cf402635-451b-4966-9fcd-fbf642aa0c05.png)
> 
> ![Screenshot (127)](https://user-images.githubusercontent.com/101845170/217252700-04164d3f-1e8f-4639-927c-3896b5ca31f7.png)
> 
> in the below video you can see how the score is reset of each turn(i.e after 10 chances).
> 
> https://user-images.githubusercontent.com/101845170/217256818-8d70a8c0-6dd9-4bd3-bfb8-517685f31198.mp4
> 
> 
> 

Yeah sure. Please do. I lost the code that I implemented before creating a pr. Please continue. I do not wish to work on it.

**Comment by Ayeshashaik759** [comment]
@llaske I tried adding score counter to the fraction activity. I tested it in the web browser I hope it is working fine. please check my pr and share your view on it.

**Comment by llaske** [comment]
@Ayeshashaik759 thanks. See my comments on your PR.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1185
