### ISSUE TITLE
Calligra activity stop button localization

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#1033]
Tooltip for stop button in calligra activity is hardcoded instead of localization.

**Comment by llaske** [comment]
Stop button tooltip is never localized in activities.
Its signification is obvious.

**Comment by AnandChourasia007** [comment]
Sure, I'll close this issue. @llaske 
But before that there's one thing I don't understand. If the significance of Stop button is obvious, why do we need a tooltip for Stop in the first place. Its like our english users have tooltips for stop button but rest of the users don't have that in their language, leading to unequal experience (very trivial, I agree) for english and non-english users. My point being, we should either not have a tooltip in any language, or if we have, we should have it localized (in all the languages) instead of hardcoded in just one language.

**Comment by llaske** [comment]
Both Stop word and Stop sign is universally recognized. Same for Help.
Plus, because Sugarizer is often use on touch device, tooltips are not so important.

**Comment by AnandChourasia007** [comment]
Now, I get it. Thanks.
I am closing this issue and the linked PR too.
