### ISSUE TITLE
Fraction jump tutorial navigation text issue.

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#1035]
Activity name: Fraction Bounce
Issue: Text on tutorial navigation buttons is the variable name instead of the value as shown.
  Current text:
![FractionBounce activity issue1](https://user-images.githubusercontent.com/89119829/159693144-44b3435e-16d2-49e2-a1c0-fc75e22db507.jpg).
  Expected text:
![FractionBounce issue1 after fix](https://user-images.githubusercontent.com/89119829/159693257-64e27582-5e2c-4415-9c6e-5f0425c50ff4.jpg)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1036
