### ISSUE TITLE
Align Grid in Memorize activity 

### ISSUE THREAD

**Issue by gitkaarma** [llaske/sugarizer#1038]
The grid is not vertically aligned. 
![image](https://user-images.githubusercontent.com/96700361/159795821-d745a8f3-5bcd-414b-b898-abab05ace397.png)

Also in mobile view, which is used by most of the users, it looks much worse. 
![image](https://user-images.githubusercontent.com/96700361/159796879-2eb8a5b0-75ff-4468-9125-7896703c9232.png)

After change: - 
![image](https://user-images.githubusercontent.com/96700361/159796865-318101f9-9541-4e0b-8160-32033e2c37b7.png)

**Comment by llaske** [comment]
The grid doesn't need to be aligned.
There is a limit to responsive in Sugarizer, see [here](https://github.com/llaske/sugarizer/issues/422).
