### ISSUE TITLE
Planets activity view distorted in mobile view

### ISSUE THREAD

**Issue by gitkaarma** [llaske/sugarizer#1040]
Planets are not aligned properly. 
Ipad view: - 

https://user-images.githubusercontent.com/96700361/159810480-7d54c2c9-10aa-4a50-956b-d8d924f3a864.mp4

Desktop view: - 
![image](https://user-images.githubusercontent.com/96700361/159810334-79b1a68e-1aee-48d2-ad64-d9696ecb7a19.png)

Proposed change: - 
Ipad view: - 

https://user-images.githubusercontent.com/96700361/159810649-199042a8-5bcf-49f8-99e7-e5bfe7313730.mp4

Desktop view: -
![image](https://user-images.githubusercontent.com/96700361/159810407-2ca5578b-d91e-4781-9860-fc6013f20c9d.png)

**Comment by llaske** [comment]
There is a limit to responsive in Sugarizer, see [here](https://github.com/llaske/sugarizer/issues/422).

**Comment by nikkuAg** [comment]
Is this issue sill open? 
I would like to work on this

**Comment by gitkaarma** [comment]
I understand that Sugarizer is currently compatible with Landscape view only. But isn't it better to make it responsive step by step. Also in Desktop view its looking much better than before. @llaske

**Comment by Shreyas-SAS** [comment]
> I understand that Sugarizer is currently compatible with Landscape view only. But isn't it better to make it responsive step by step. Also in Desktop view its looking much better than before. @llaske

@gitkaarma just my suggestion, I feel that in desktop view not aligning in the center but left is better choice. It was like a list earlier and like a presentation now. since its like a flow towards outer space in order its more beneficial to keep it in left than center. but for ipad view I support the new look as it was empty before that.

**Comment by llaske** [comment]
I'm agree with @Shreyas-SAS. Left alignment is better.
