### ISSUE TITLE
Xmas Lights: Text overlap makes icons unreachable in mobile

### ISSUE THREAD

**Issue by Shreyas-SAS** [llaske/sugarizer#1044]
**Issue:** 
In Xmas Activity the Text overlaps menu items in Mobile view leaving the icons behind them unreachable.

Visuals: (Mobile View)
Happy New Year message:
![Xmas_HNY](https://user-images.githubusercontent.com/96542494/160148639-638004e7-2a48-47d3-8bdf-8f7cd4b27560.jpeg)

Blue moon message:
![Xmas_BM](https://user-images.githubusercontent.com/96542494/160148649-5fda7e09-b478-4051-bb90-9b597cba7712.jpeg)

**Proposed:** 
Lowering text using Padding and margin at the top.

**Comment by llaske** [comment]
It depend of the mobile. 
Plus it does not prevent clicking on menu bar and it's solved in fullscreen mode.
Because designing the animation is left to user, I'm sure the user will try to fit it's animation to the window size.
It's not an issue.

**Comment by Shreyas-SAS** [comment]
> Plus it does not prevent clicking on menu bar and it's solved in full-screen mode. 
Actually it does prevent clicking of buttons in most mobile phones. I actually found this true on all the 3 mobiles in my house.

It may be that it works well with your mobile sir but I guess most of the phones will face this issue. 

Still if sir wants to keep the format as it is and put it to the user to adjust to the environment I have no problem with that, but would like to make a point: considering the user to be a child I strongly disagree with user trying to fit it on the screen by themselves and feel @llaske sir contradicts the reason for dismissing many previous changes in the repository that were kept simple because of user being a kid.

I am really thankful for your reply and will try my best to contribute in every other possible way.
