### ISSUE TITLE
Chess multiplayer bug when a third player join

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#1047]
Issue: If a chess match between two players is already going on, attempt to join by a third player is allowed. Any such attempts then actually BREAKS the game and the 1st and 2nd players lose the game status, returning to singleplayer screens.
Suggestion: Since, this activity is supposed to be used by kids, expecting them to 'not click when a chess game is full' is not a good idea. Instead, we can prevent clicking of the join game button after the second player has joined the game.

https://user-images.githubusercontent.com/89119829/160396030-f8d21940-923d-49c5-b786-1a7aa5fd08e3.mp4

**Comment by llaske** [comment]
Good point.
We can't prevent joining the game but we can stop the activity of the third player in this situation.
I guess some other activities do the same. May be Memorize?

**Comment by jcvails** [comment]
I was unsure of the player counts of other shared games so I only made the fix for chess, should be easy to add other player counts in the constant file though it may be worth adding player counts to the activities themselves for simplicity in creating new activities.

**Comment by llaske** [comment]
@jcvails the fix should be done in Chess activity

**Comment by UtkarshSiddhpura** [comment]
@llaske I've fixed the issue and tested it.
- 3rd user won't interrupt the game
- if any player leaves the opponent will be played by computer.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1345
