### ISSUE TITLE
Add buttons in Markdown activity to show/hide Editor/Preview

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#105]
Add buttons in the toolbar to show/hide Editor or Preview pane

**Comment by aditodkar** [comment]
Hello I am new to open source I would like to work on this how to get started

**Comment by llaske** [comment]
Hi, 
A good start is to understand the Activities part of the README file. https://github.com/llaske/sugarizer#activities
You could also follow the video tutorial to create an activity https://www.youtube.com/watch?v=31CCAYy0pLE&feature=youtu.be
Finally you have to understand how the Markdown activity work.

**Comment by aditodkar** [comment]
Thanks for providing the youtube link it was very helpful can you please tell me where can I get more information about Markdown activity.

**Comment by dinesh-sirvi** [comment]
--Some questions--
1)When I hide preview area, should the input area expand and take the entire width?
2)Should it be allowed to hide both of the areas ie., input and preview at the same time?

**Comment by llaske** [comment]
It has no sense to hide both areas so the non hide area should take the whole space

**Comment by dinesh-sirvi** [comment]
Opened a pr, plz check

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/5f642290f14bc60c947decef239566a09d9ffca3
