### ISSUE TITLE
some button text is not in centre with the icon

### ISSUE THREAD

**Issue by codebloded** [llaske/sugarizer#1052]
![Screenshot from 2022-04-03 23-01-34](https://user-images.githubusercontent.com/48005711/161527372-32d8ef4b-d309-4098-850a-63d50db9e9be.png)
![Screenshot from 2022-04-03 23-02-24](https://user-images.githubusercontent.com/48005711/161527383-0e4748bc-619e-4597-ab1b-31ead53f0b9d.png)

etc..!

**Comment by llaske** [comment]
You're right. It will be better.

**Comment by codebloded** [comment]
> You're right. It will be better.

#1053   FIXED
sir @llaske

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1054

**Comment by llaske** [comment]
@codebloded issues must not be closed before a release include it

**Comment by Ankitsharma991** [comment]
I want to work on this issue, can @llaske you assign this to me?

**Comment by llaske** [comment]
@Ankitsharma991 it's already fixed
