### ISSUE TITLE
Overlapping of "activity-palette" wrapper container with "back-button" in some activities

### ISSUE THREAD

**Issue by S-kus** [llaske/sugarizer#1055]
In **Tangram.activity** and **Curriculum.activity** the `activity-palette`'s `container` is overlapping with `back-button`. As shown:

![curr1](https://user-images.githubusercontent.com/86892991/162558648-35519f8d-3b13-400a-b226-1bc1201c35c8.png)

![curr2](https://user-images.githubusercontent.com/86892991/162558652-426c7a27-df0d-423b-89b8-492c13bb8318.png)

![ten](https://user-images.githubusercontent.com/86892991/162558656-cd704cac-853b-4b58-aa4a-d94206f54cc0.png)

**Comment by S-kus** [comment]
Hello @llaske, I fixed this, Could you please review its pull request.

**Comment by llaske** [comment]
Good point.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1056
