### ISSUE TITLE
Shared notes activity suggestion

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#1057]
--

**Comment by llaske** [comment]
You're wrong, a user who join see the current set of notes.

![Peek 09-04-2022 22-12](https://user-images.githubusercontent.com/981841/162590152-4bf612e4-0e41-4658-bc2b-968ca6ad19b6.gif)

**Comment by AnandChourasia007** [comment]
Oh I see, I expected changing of text to be reflected reflected as the typing is being done rather than once the typing is completed and the box is clicked.
I apologize for such an embarrasing mess I made here. Be assured this is not gonna happen again.
I close this issue without delay.
