### ISSUE TITLE
Overlapping of back button with the activity palette in Tangram Activity

### ISSUE THREAD

**Issue by nikkuAg** [llaske/sugarizer#1058]
<img width="233" alt="overalp" src="https://user-images.githubusercontent.com/77184239/163022328-0be628d3-2b29-4a6d-ba5b-860caf5fb9ec.png">
Back button in Tangram activity was coming above the activity palette.

**Comment by nikkuAg** [comment]
Hey @llaske,

I have solved this issue in the PR #1059

**Comment by llaske** [comment]
Duplicate https://github.com/llaske/sugarizer/issues/1055
