### ISSUE TITLE
Settings of Falabracman activity was overlapping with activity palette

### ISSUE THREAD

**Issue by nikkuAg** [llaske/sugarizer#1060]
The settings are not visible when we open `activity-palette` in Falabracman activity.

<img width="497" alt="s3" src="https://user-images.githubusercontent.com/77184239/163026538-f2528149-170e-47d9-ae12-80f673e1544e.png">

**Comment by nikkuAg** [comment]
Hey @llaske,

I have solved this issue 
PR: #1061 
Can you please review it

**Comment by llaske** [comment]
You're right.

**Comment by llaske** [comment]
Thanks but you're not supposed to send a PR to master. See [here](https://github.com/llaske/sugarizer/blob/dev/CONTRIBUTING.md).
I've merged it manually here: https://github.com/llaske/sugarizer/commit/15433b480f1afde09890f85f95035cb4b787f769
