### ISSUE TITLE
Word getting overlapped with background

### ISSUE THREAD

**Issue by nikkuAg** [llaske/sugarizer#1062]
I think that the word ***Dictonary*** should be a little below so that it does not overlaps with the color tranisition line in the background image.

<img width="763" alt="s6" src="https://user-images.githubusercontent.com/77184239/163028524-1dfa15a2-afc2-4a47-a54e-ab8f50feaddf.png">

**Comment by nikkuAg** [comment]
Hey @llaske,

I have made a PR to solve this
PR: #1063 
Please review it

**Comment by llaske** [comment]
It's not an issue.
