### ISSUE TITLE
Physics element are coming above toolbar

### ISSUE THREAD

**Issue by nikkuAg** [llaske/sugarizer#1064]
If we drag the physics elemnts in Physics JS activity above the toolbar then we see that the elements overlap with toolbar.

<img width="556" alt="s8" src="https://user-images.githubusercontent.com/77184239/163033522-1395f05c-39a0-46a8-84fc-b6bb189a9e06.png">

**Comment by nikkuAg** [comment]
Hey @llaske,

I have solved this issue
PR: #1065 
Please review it

**Comment by llaske** [comment]
You're right, it will be better to not overlap the toolbar

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1170
