### ISSUE TITLE
In Paint activity on resizing the window it crops the canvas instead of resizing it 

### ISSUE THREAD

**Issue by disha1202** [llaske/sugarizer#1100]
Current behaviour

[screen-recorder-thu-sep-01-2022-17-44-12.webm](https://user-images.githubusercontent.com/58461801/187911289-97e69ea0-8501-45c6-bcb1-600ad9ad728e.webm)

Expected behaviour

[screen-recorder-thu-sep-01-2022-17-37-51.webm](https://user-images.githubusercontent.com/58461801/187911320-8932402e-a34d-480f-bfd6-61fe61bbfd30.webm)

**Comment by llaske** [comment]
The drawing should not be resized because it will lost its proportion.
A drawing is not like an image.
So it's not a bug.

**Comment by disha1202** [comment]
> The drawing should not be resized because it will lost its proportion. A drawing is not like an image. So it's not a bug.

Alright, if that is the case then maybe we can remove the onResize function (https://github.com/llaske/sugarizer/blob/dev/activities/Paint.activity/js/paint-activity.js#L53)  and this line of code (https://github.com/llaske/sugarizer/blob/dev/activities/Paint.activity/js/paint-activity.js#L47) 

@llaske What do you think?

**Comment by disha1202** [comment]
Yes, the canvas is resized when you change the screen size and on this resize event we have called a function [onResize](https://github.com/llaske/sugarizer/blob/dev/activities/Paint.activity/js/paint-activity.js#L53) where the first line of code is a return statement. This function ends before performing any computation and will not affect the current behaviour if removed.

Please let me know if I'm missing something?

**Comment by llaske** [comment]
Oh :open_mouth:  you're right!
The Resize method is useless

**Comment by disha1202** [comment]
So should we remove it?

**Comment by llaske** [comment]
@disha1202 yes please.
