### ISSUE TITLE
MindMath Activity doesn't allow negative subtraction.

### ISSUE THREAD

**Issue by shubhangNarain** [llaske/sugarizer#1115]
@llaske I found an issue in the `MindMath` Activity where it was not allowing the user to calculate the difference between a smaller number and the difference between a larger number. I've attached an image where it doesn't calculate the difference when I try to.

![er1](https://user-images.githubusercontent.com/80174035/204464441-e30b3a69-1585-4fcd-87c3-6a69079a5fd5.PNG)

**Comment by llaske** [comment]
It's on purpose, the concept of negative numbers is not familiar to children.
The solver included in the activity take into account this "limitation" to propose operations that don't need using negative subtraction.
Thank for your contribution.
