### ISSUE TITLE
ColorMyWorld functionality breaks

### ISSUE THREAD

**Issue by shubhangNarain** [llaske/sugarizer#1116]
In `ColorMyWorld` activity, the 'sea' should be restricted to be selected by the user. @llaske I've attached a UI/Functionality break as it happened. Please share your inputs on this error.

![ColorMyWorld](https://user-images.githubusercontent.com/80174035/204467128-c3c52df9-e0e6-47a8-8f76-cdd60aaaf91e.PNG)

**Comment by llaske** [comment]
It's the expected behavior.
Children love to color everything, there is no reason to restrict their creativity 😄 
Thanks @shubhangNarain for your contribution.
