### ISSUE TITLE
Extra white space to right side of the buttons

### ISSUE THREAD

**Issue by disha1202** [llaske/sugarizer#1124]
There is extra white space to the right side of the following buttons
Back, Next, Done, Accept.

![Screenshot from 2022-12-26 12-05-25](https://user-images.githubusercontent.com/58461801/209512840-32a5afe7-e958-4076-87d7-a2b6eea5651e.png)
![Screenshot from 2022-12-26 12-05-44](https://user-images.githubusercontent.com/58461801/209512853-bb1d6210-0bf1-42e2-b415-6882a1bb6027.png)

We can update the css and improve the spacing of the buttons.

![Screenshot from 2022-12-26 12-11-43](https://user-images.githubusercontent.com/58461801/209513248-32c18ad8-8254-4115-8f4e-67c69a991abf.png)

**Comment by disha1202** [comment]
What do you think @llaske?

**Comment by llaske** [comment]
Hmmm. It's nice to have button of the same size to have a symmetric screen.
BTW you can suggest some improvements thought it should be done on the Sugar.IconButton component, not in each screen.

**Comment by prakharSrivs** [comment]
Hi @disha1202 , I would like to ask if you are working on this issue ?

**Comment by disha1202** [comment]
> Hi @disha1202 , I would like to ask if you are working on this issue ?

@prakharSrivs, you can work on this.

**Comment by prakharSrivs** [comment]
One more thing , @disha1202 I am having some problems in setting up Chrome Developer Tools for inspect element purposes in the application.
Plus I am not able to open it in chrome Browser.
It would be very nice of you if you could help me out here.

**Comment by disha1202** [comment]
> One more thing , @disha1202 I am having some problems in setting up Chrome Developer Tools for inspect element purposes in the application. Plus I am not able to open it in chrome Browser. It would be very nice of you if you could help me out here.

Try using firefox
Also set the `security.fileuri.strict_origin_policy` parameter to false for firefox

**Comment by ABHINAV-JHA-27** [comment]
Hey @prakharSrivs, are you still working on the issue?

**Comment by prakharSrivs** [comment]
> Hey @prakharSrivs, are you still working on the issue?

Yes Abhinav, I am working on it. @ABHINAV-JHA-27

**Comment by Vishalk91-4** [comment]
Hi @llaske, Is this the type of window, you expected it to look like after completion
![Screenshot 2023-05-17 053731](https://github.com/llaske/sugarizer/assets/116670999/b97f39c0-0ce1-4c28-a39b-deba0c3ef346)

**Comment by llaske** [comment]
@Vishalk91-4 , no. More spacing will be better like in @disha1202 suggestion.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1360
