### ISSUE TITLE
Addition of key bindings for fire button in Tank Operation activity.

### ISSUE THREAD

**Issue by anugcodes** [llaske/sugarizer#1128]
In the Tank Operation Activity on the [Sugarizer web app](https://try.sugarizer.org/index.html) , it would be great to add the key binding for the fire button so that it would be easy for user, else users have to drag mouse button each time and click fire button.

**Comment by llaske** [comment]
Thanks for your suggestion @anugcodes.
The fire button can be run using SPACE.
