### ISSUE TITLE
Left arrow not appearing in Xmas light activity

### ISSUE THREAD

**Issue by Ayeshashaik759** [llaske/sugarizer#1135]
In the Xmas light activity I have observed that left arrow for the prev button is not visible because of wrong go-left.svg file 

![Screenshot (113)](https://user-images.githubusercontent.com/101845170/211093734-7010ce31-fdc8-40e2-a7e4-c825ccc16ac6.png)

it can be solved by replacing the file with the correct file 

![Screenshot (114)](https://user-images.githubusercontent.com/101845170/211094055-e0ed4e4b-7b69-4106-9da9-0821f320caed.png)

@llaske what is your view on this

**Comment by llaske** [comment]
You're right but it's used only for tutorial and you fixed it in https://github.com/llaske/sugarizer/pull/1134

**Comment by Ayeshashaik759** [comment]
Hmm right @llaske  this issue is fixed there so you can close this issue
