### ISSUE TITLE
GameOfLife activity resets on changing the size of the canvas.

### ISSUE THREAD

**Issue by shubhangNarain** [llaske/sugarizer#1137]
Hey @llaske , I came across a functionality break(maybe) as when I changed the slider to change the size of the canvas for the `GameOfLife` activity, it resets the game and even the pattern with which we start the game, I've attached some screenshots for the same. Please try and replicate this and please give your thoughts.
![gol_1](https://user-images.githubusercontent.com/80174035/212495018-ca783821-291f-43c3-a5f4-e0fc49bae625.PNG)
![gol_1_2](https://user-images.githubusercontent.com/80174035/212495021-1660a9c9-a785-4def-b680-6779f04b863b.PNG)

**Comment by llaske** [comment]
Yes you're right but it seems logical since this slider redraw the board. Patterns buttons have the same behavior.
