### ISSUE TITLE
There is no lib/tutorial.js file in chess activity

### ISSUE THREAD

**Issue by saakxshi** [llaske/sugarizer#1139]
I was trying to replace the Bootstrap tour by IntroJs in the chess activity but **could not find the lib/tutorial.js** file to make the changes. 
![image](https://user-images.githubusercontent.com/91880528/212595414-3eee8e63-5abb-4ba9-94db-2e4daf8aa7e9.png)

**Comment by Ayeshashaik759** [comment]
@saakxshi you are right but you can find it in js/tutorial.js folder please try to make changes from there hope this help you. 

![Screenshot (115)](https://user-images.githubusercontent.com/101845170/212603156-f54f5893-531d-442e-a577-11eeb31449c6.png)

**Comment by saakxshi** [comment]
Thankyou, @Ayeshashaik759
