### ISSUE TITLE
Constellation Activity has no use of 'worldList'

### ISSUE THREAD

**Issue by shubhangNarain** [llaske/sugarizer#1140]
Hey @llaske , Please give some input over the `world-list` button in `Constellation.activity` , as it seems illogical to have the names of places in the constellation activity. Instead we could have the list for constellations in it. If yes, could you please assign the issue to me?

![constellation_1](https://user-images.githubusercontent.com/80174035/212753523-e649ede3-ad95-47b4-9a9a-e2e3c43ca45f.PNG)

**Comment by llaske** [comment]
Constellations are not the same in the sky depending of the place you are in the world, it's why it's useful to be able to change location. Then the game could be for students to find a specific constellation in the sky. Other parameters are dependent of the VirtualSky library.
