### ISSUE TITLE
dev: wrong path to activity icon in API?

### ISSUE THREAD

**Issue by bzg** [llaske/sugarizer#115]
http://dev.sugarizer.org/api/activities lists details of all activities.

I see `"icon": "activity/activity-icon.svg"` is each item, which does not seem correct.

**Comment by llaske** [comment]
No, it's not true. Some activities have a different path (Welcome web or EToys).
But this file path is relative to the activity directory.
To have the full icon path, you have to combine the activity directory and icon file path.
Note that that this path is loaded from the activity/activity.info file of each activity. See the source code for this reading here: https://github.com/llaske/sugarizer/blob/master/server/routes/activities.js#L30

**Comment by bzg** [comment]
Thanks for the reply.

Just curious: is it useful to keep the "activities/" and "activity/" part in, respectively, the directory and the icon paths?

Are there cases where the activity directory is not in "activities/" directory and where the icon is not in the "activity/" directory?

**Comment by llaske** [comment]
Good question.

The name of the directory "activities" is a settings in the sugarizer.ini file so it can't be removed.
The name of "activity" directory is inherited from Sugar but you're right it could be removed.

**Comment by bzg** [comment]
Thanks for the clarification!
