### ISSUE TITLE
Changing the position of down arrow and reload option in Blockrain Activity

### ISSUE THREAD

**Issue by Ayeshashaik759** [llaske/sugarizer#1160]
Hlo @llaske while playing the blockrain activity I just felt that it could be more convenient if we have the left, right and down arrow and reload option on the same side. As it is mainly designed for children it will more convenient for them to monitor the blocks rain one side and the actions to be performed one side instead of moving the mouse from left to right to perform different actions.
The present view of blockrain activity.
![Screenshot (117)](https://user-images.githubusercontent.com/101845170/214115154-a8878674-0d63-4ce3-9aaf-44b8a8e57bae.png)
The view after making the changes
![Screenshot (116)](https://user-images.githubusercontent.com/101845170/214115275-0dc6c6a5-654c-4003-9c99-304ec5784b9b.png)
If you think this changes are good then I want to make this changes please share your view on this changes.

**Comment by llaske** [comment]
Hi @Ayeshashaik759 ,
Icons are there for use on tablets/smartphone. For this usage it's better to dispatch them between left and right of the screen.
On a computer it's easier to use keyboard than mouse.

**Comment by Ayeshashaik759** [comment]
ok now I got it. yes in case of tablets/smartphone it's better to dispatch them between left and right of the screen. And in case of desktop we can use the keyboard easily so no changes need I will close this issue.
