### ISSUE TITLE
Undo and Redo keybindings in Paint Activity

### ISSUE THREAD

**Issue by dikwickley** [llaske/sugarizer#1164]
@llaske in the `Paint Activity` there is an option for undo and redo but there are no key bindings for them. It is very common across all software to map *undo* to `ctrl+z` and *redo* to `ctrl+y`. Paint activity should also support these key bindings

![image](https://user-images.githubusercontent.com/31622972/214392074-e4b017f0-388b-4131-8147-16c8d4f97184.png)

**Comment by llaske** [comment]
These shortcuts make no sense for children. 
They are not familiar with shortcuts and it's often too complex for them to press two keys simultaneously.

**Comment by dikwickley** [comment]
Makes sense, thanks @llaske
