### ISSUE TITLE
Creating Elements in PhysicsJs.activity that're Bigger than canvas

### ISSUE THREAD

**Issue by UtkarshSiddhpura** [llaske/sugarizer#1171]
- Collisions are only detected for the **top edge** of view-port (i.e base of toolbar) for bodies/elements while **creating**.
- So elements bigger than canvas are easily possible to create from other edges
- e.g
![phy](https://user-images.githubusercontent.com/90092555/215289371-0303780b-0c12-41f0-bb6c-0a8fad2dd6ad.jpg)

Solution: consider each edge of viewport and stop increase in size once edge is touched.

**Comment by llaske** [comment]
Make sense.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1172
