### ISSUE TITLE
Template container interfering the Calligra Activity 

### ISSUE THREAD

**Issue by UtkarshSiddhpura** [llaske/sugarizer#1174]
When the template **drop-down** is open interaction with the above half of canvas is not possible
as it's coming on top of canvas.
This drop-down can be easily left opened as it doesn't closes itself.

![cal2](https://user-images.githubusercontent.com/90092555/215335228-522ea3ab-b876-4b4a-9154-728212e71885.jpg)
![cal](https://user-images.githubusercontent.com/90092555/215335235-27825de7-a22b-485d-8d85-c99c2b5f432b.jpg)

**Comment by llaske** [comment]
You're right. Could be improved.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1179
