### ISSUE TITLE
SharedNotes activity: Text content overflows out of the notes container

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1177]
hey, @llaske I came across a functionality break in the SharedNotes activity. Whenever we try to write text more than the size of the notes container it overflows out of the container, the scrollbar still works and we can view the entire text by dragging the scrollbar but as soon as the notes container is filled the text overflows out of it. 
I have attached the screenshots for the same, please look and review them and give me your thoughts. If you find it as a issue then I would like you to assign this issue to me :)

<img width="1280" alt="Screenshot 2023-01-31 at 2 24 30 AM" src="https://user-images.githubusercontent.com/46915044/215596806-d0112b9c-1d91-4c8d-8d44-7c1027b94f39.png">

**Comment by llaske** [comment]
This activity is useful for small notes. It has no sense for long text.

**Comment by rockharshitmaurya** [comment]
Sir, I have an idea. We can limit the text length in the notes container so that they do not exceed the container's limit. This will prevent our UI from breaking, and an alert can be displayed when the limit is reached.

**Comment by codebloded** [comment]
> Sir, I have an idea. We can limit the text length in the notes container so that they do not exceed the container's limit. This will prevent our UI from breaking, and an alert can be displayed when the limit is reached.

Good for the UX ! 👍
