### ISSUE TITLE
Reload option in Blockrain activity not visible fully when screen width < 500px

### ISSUE THREAD

**Issue by Ayeshashaik759** [llaske/sugarizer#1178]
while playing blockrain activity in mobile phone I found that the realod button is not visible fully because its background-size is fixed to 40px when max device width is lessthan 500px.

![Screenshot (120)](https://user-images.githubusercontent.com/101845170/215676559-478e09bc-a19d-4fc2-9e38-09c5f992bf7b.png)

screenshot from my mobile
![Screenshot_20230131_110043](https://user-images.githubusercontent.com/101845170/215678008-fe54279a-9829-4a4a-b81f-3ec1efb08393.jpg)

This can solved by removing the background-size.
output after making required changes.
![Screenshot (121)](https://user-images.githubusercontent.com/101845170/215677930-4275b763-5de2-4f4f-ac99-e50451340012.png)

**Comment by llaske** [comment]
Activities are not suppose to be responsive in any condition. See https://github.com/llaske/sugarizer/issues/422 for more.

**Comment by Ayeshashaik759** [comment]
Oh I have not gone through this issue before now I gone through it 😊.
