### ISSUE TITLE
Zoom container interfering the Calligra Activity

### ISSUE THREAD

**Issue by saakxshi** [llaske/sugarizer#1180]
### Issue
When the **zoom drop-down** is clicked, the interaction with the upper half of the canvas is **hindered** as it is on top of it.
This can lead to uneasiness as the drop-down menu can be easily left open until the desired size is achieved. And zooming in and out with the drop-down menu open further contributes to it.

![image](https://user-images.githubusercontent.com/91880528/216008063-3efdea98-2fc1-4ba6-b7e2-68677c90c5ff.png)

### Solution
This can be avoided by making the display property inline so that it does not conflict. 

![image](https://user-images.githubusercontent.com/91880528/216007344-8721a9e5-d349-499a-a69d-d70ff70b94e5.png)

If the above seems fine then I'd like to implement it.

**Comment by llaske** [comment]
Hmmm. Instead of https://github.com/llaske/sugarizer/issues/1174 I don't think that in this case it's a problem.
BTW you're right it could be better.

**Comment by llaske** [comment]
Same issue than https://github.com/llaske/sugarizer/issues/1174
