### ISSUE TITLE
Not Able to see Text and XML req error

### ISSUE THREAD

**Issue by kirtanchandak** [llaske/sugarizer#1189]
### Text not visible - 
 
![textnot](https://user-images.githubusercontent.com/92196705/218839196-4bc66709-6958-4e27-8e38-42e633660551.png)

### Console Error - 
![cors](https://user-images.githubusercontent.com/92196705/218839240-456dbad5-dd8e-4dc7-bea2-f0536e06f512.png)

**Comment by llaske** [comment]
@kirtanchandak as the message mention, it's typically an error due to missing access right running the browser.
See **Sugarizer Application into the Web Browser** section in the [README](https://github.com/llaske/sugarizer/blob/dev/README.md).
