### ISSUE TITLE
Add required check-alert to input for server reconnection

### ISSUE THREAD

**Issue by Tushar98644** [llaske/sugarizer#1190]
<img width="1440" alt="Screenshot 2023-02-19 at 1 06 17 AM" src="https://user-images.githubusercontent.com/107763774/219884993-fe05fd64-2dce-4b20-aa53-89f76c59c60a.png">

Even on clicking on next button , no alert is displayed saying the image is a required field...i think it would be best to display such kind of check

**Comment by llaske** [comment]
There is nothing like "required field" in Sugar Design UI. When there is a Next button, it seems obvious than the field is required.

**Comment by Tushar98644** [comment]
@llaske closing the issue....also i found that when we hover on one of the activities , the activity description overlaps with the icon and i think the icons should be given a scaling while hovering .....

`References`:

<img width="1440" alt="Screenshot 2023-02-22 at 1 15 38 PM" src="https://user-images.githubusercontent.com/107763774/220556477-d77cde47-475a-42b8-89dc-a82c1437cc3a.png">

`References to the scaling property on icon hover`:

<img width="415" alt="Screenshot 2023-02-22 at 1 19 39 PM" src="https://user-images.githubusercontent.com/107763774/220556822-880fb098-fc23-46d0-a801-e74817fb2e72.png">

the first icon is on hover while the other 2 are in natural state
