### ISSUE TITLE
The football will shake when the mouse is pressed continuously

### ISSUE THREAD

**Issue by ybwell** [llaske/sugarizer#1192]
There is a high probability that the football will shake when you press the mouse continuously. Can you optimize it
https://user-images.githubusercontent.com/87561656/221182583-113c7a80-aeb5-4a21-94ac-ea6549e77869.mp4

https://user-images.githubusercontent.com/87561656/221182586-fc49c530-600f-4f9a-ad58-ef8a16810276.mp4

**Comment by ABHINAV-JHA-27** [comment]
Hey, can you describe a bit more about the issue and Tell how to reproduce the issue. It would be a great help.

**Comment by llaske** [comment]
@ybwell I don't think it's an issue, it's fun

**Comment by ybwell** [comment]
> Hey, can you describe a bit more about the issue and Tell how to reproduce the issue. It would be a great help.

Thanks，Next time I will

**Comment by ybwell** [comment]
> @ybwell I don't think it's an issue, it's fun

Thanks
