### ISSUE TITLE
Creating a New Activity

### ISSUE THREAD

**Issue by jo780-full** [llaske/sugarizer#1195]
Hello I wanted to create an activity that introduces children to fruits and vegetables and by dragging and dropping ingredients would create a dish, but I wanted to ask if this activity is created in VanillaJs how would it be made available on the desktop we would have to physically clone this activity into the desktop?

**Comment by llaske** [comment]
If by desktop you mean Sugarizer running on a PC, there is nothing to do, Sugarizer activities run on every device.
If you mean running on Sugar, you have to adapt it.
BTW I'm not a big fan of the idea of digital cooking, cooking should be done in real life.

**Comment by jo780-full** [comment]
I meant running it on Sugar.
And With digital cooking, it's more to familiarize ingredients than to really cook. It was just a suggestion.
