### ISSUE TITLE
Chess Activity : Step Number are not visible after 99

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1196]
Hey @llaske .  I came across a functionality break in the Chess activity. After the number of steps get beyond 99 the 100th step get out of the container , It is showing 00, 01, 02 instead of 100, 101, 102 , Also the double digit numbers required some padding from the left and alignment.
For reference i have attached screenshots for the same, please look and review them and give me your thoughts. If you find it as a issue then I would like you to assign this issue to me :)

![Screenshot (32)](https://user-images.githubusercontent.com/81116984/221430913-34d5481f-ee7b-49bf-8520-b5975a005eb9.png)

**Comment by llaske** [comment]
You're right it's a bug. There's nothing like assigning issue here but feel free to try to fix it.

**Comment by NischayGoyal1** [comment]
Hey @llaske I have fixed the issue , Please review my PR https://github.com/llaske/sugarizer/pull/1198

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1209
