### ISSUE TITLE
Extension for closed issue #1177 SharedNotes activity

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1200]
Sir, I have an idea. We can limit the text length in the notes container so that they do not exceed the container's limit. This will prevent our UI from breaking, and an alert can be displayed when the limit is reached.

please refer https://github.com/llaske/sugarizer/issues/1177 to check my previous closed issue.

**Comment by llaske** [comment]
I don't think we need that. Sometimes it's interesting for young users to understand that they could break things.
