### ISSUE TITLE
some button text is not in centre aligned with icons

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1202]
I've noticed that some button text isn't ***centered*** with the icon on buttons : 

here are the screenshots of the functionality break, If you find it as an issue then I would like you to assign this issue to me :)

1.
<img width="1280" alt="Screenshot 2023-02-27 at 5 49 45 AM" src="https://user-images.githubusercontent.com/46915044/221447053-7226228f-4fad-4c6e-9484-6eb89fc1a543.png">

2.
<img width="1280" alt="Screenshot 2023-02-27 at 5 02 49 AM" src="https://user-images.githubusercontent.com/46915044/221447065-68b77976-df72-4c92-b184-f70094c68731.png">

**Comment by llaske** [comment]
Not an issue. Buttons text and icon are not intended to be centered in the Sugar UI.
