### ISSUE TITLE
FoodChain Activity UI enhancement

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1205]
Hey @llaske . I have a suggestion for the FoodChain Activity. I noticed that the standard time format displayed in the UI is not correct.
I believe this issue might affect the overall user experience, and I would like to report it to you so that it can be addressed.
For reference I have attached screenshots for the same, please look and review them and give me your thoughts. If you find it an issue then I would like you to assign this issue to me :)

![Screenshot (123)](https://user-images.githubusercontent.com/91108730/221558610-89a188c6-85cf-4fbc-b03d-dfa13d1d2656.png)

![Screenshot (30)](https://user-images.githubusercontent.com/91108730/221558671-5f2fb3b8-d7c9-4f38-83ae-f7b06676f3aa.png)

**Comment by llaske** [comment]
It seems correct to me. Why you think it's not correct?

**Comment by Ydvaaman** [comment]
@llaske  I think it would be better if there is a colon before a millisecond instead of a coma. ( Minutes: seconds: milliseconds )

**Comment by llaske** [comment]
Hmmm I don't think so.

**Comment by Ydvaaman** [comment]
## Hi @llaske 
## Inconsistency in Time Format between Stopwatch Activity and Food Chain Activity.
## Description
There is an inconsistency in the time format used in two activities, the Stopwatch activity and the Food Chain activity. 
In the Stopwatch activity, the time is displayed in the correct format as minute : second : milliseconds while in the Food Chain activity, the time format is minute : second , milliseconds.
I believe this enhancement would be great and make the user experience better, and I would like to report it to you so that it can be addressed.
For reference I have attached screenshots for the same, please look and review them and give me your thoughts.

## In the Foodchain Activity, there is a comma in the timer but in the Stopwatch Activity, there is a colon in the timer.

 # FoodChain Activity:


![Screenshot (121)](https://user-images.githubusercontent.com/91108730/222216698-dd144d6c-44f7-4183-b1e1-789bd2546b2d.png)

# Stopwatch Activity:


![Screenshot (382)](https://user-images.githubusercontent.com/91108730/222216839-3887d8ea-46d8-48a5-8862-2995c7016b5f.png)

Therefore, it is recommended to use a consistent time format, preferably the standard minute : second : milliseconds format, in both activities to ensure clarity and consistency in the presentation of data.

**Comment by llaske** [comment]
Hahaha :laughing:  I think we can live with this inconsistency.

**Comment by Ydvaaman** [comment]
ok @llaske
