### ISSUE TITLE
TamTam Micro :  Piano Color keys dont work when pressed near Black keys.

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1206]
Hey @llaske 

I found a bug in the Piano mode of TamTam Activity where the color keys do not work properly when pressed near the black keys area. Specifically, when a color key is pressed above a certain height near the black keys, it does not produce any sound and there is no visual indication of it being pressed. This issue affects multiple keys {Except the 1st and the 7th keys } and significantly impairs the usability of the application.

For the 7th key , it works at the edge of the button but not near the black keys.

## Steps to Reproduce : ##

Open the Piano mode in TamTam Activity.
Click on any Colorfull key in the top section near the black keys.
Notice that the key does not produce any sound and there is no visual indication of it being pressed.

## Expected Result: ##
All keys in the Piano Application should work when clicked, regardless of their position on the keyboard.

## Actual Result: ##

Color keys near the black keys area do not produce any sound and there is no visual indication of them being pressed.

## Video ##
I have added Video showcasing the  issue

https://user-images.githubusercontent.com/34246727/221560422-ac62ade1-d168-42d6-8dfc-e78448899124.mp4

Kindly look into this and share your thoughts on this .
So, that i can work on the issue.

**Comment by llaske** [comment]
You're right. It could be improved.

**Comment by kanishkcs** [comment]
Thanks for the Response @llaske ,
i am working on the fix .

**Comment by kanishkcs** [comment]
Hey @llaske  ,I have fixed the issue  Kindly Review the PR #1214

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1215
