### ISSUE TITLE
The placeholder in search bar is not readable properly in neighborhood view for small screen.

### ISSUE THREAD

**Issue by abhishektiwari47** [llaske/sugarizer#1207]
In the search bar in neighborhood view , there is a placeholder which says "Search in Neighborhood". This is not readable when the screen size is reduced to (min-width: 410px) and (max-width: 1023px). 
This issue looks like this.
![Placeholder](https://user-images.githubusercontent.com/88083639/221560513-dccec056-d729-4a4f-a4d4-f257efd8c568.PNG)

**Comment by abhishektiwari47** [comment]
I have completed the solution for this.

**Comment by llaske** [comment]
It's just a matter of visibility, it's not a bug.

**Comment by abhishektiwari47** [comment]
Yes that's not a bug but I thought it was an improvement to be done. That
is actually resolved now. So should push it from dev branch or not?

**Comment by llaske** [comment]
No
