### ISSUE TITLE
Canvas issues and NaN

### ISSUE THREAD

**Issue by aec1140** [llaske/sugarizer#121]
My group and I were working on a project and made an app mainly through canvas. Inside the app, we found we could not do math on variables and constantly got NaN results (see below for example), even though the code comes from an app I have developed in the past and works fine outside of sugarizer. Now my question mainly is for Sugarizer, are you not suppose to use Canvas or is the entire app suppose to be DOM elements other than Canvas? If you are able to use canvas, are types being casted to another type for efficiency, and not documented, or is something else going on under the hood that is causing issues for standard JavaScript code from not working with the app.

`console.log(this.ySpeed*this.speed) // outputs a correct value eg. 108.01`
`console.log(this.y) // outputs a correct value of 10`
`isNaN(this.y) // returns false so this.y is a number`
`this.y += this.ySpeed *this.speed // outputs NaN`
`this.y = this.y + this.ySpeed*this.speed //outputs Nan`

**Comment by llaske** [comment]
Not sure to understand your issue. 
Not related to a Sugarizer issue.
