### ISSUE TITLE
FoodChain Activity : ImageCards going outside of the container

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1211]
Hey @llaske , I came across a functionality break in the Food Chain activity. Whenever I try to drag the image cards to the extreme right or left they overflow out of the draggable area (i.e the container they are supposed to be inside) and the same problem occurs when I try to drag them towards top or bottom.
For reference i have attached screenshots for the same, please look and review them and give me your thoughts. If you find it as a issue then I would like you to assign this issue to me :)

## Screenshot
![Screenshot (36)](https://user-images.githubusercontent.com/81116984/221659353-4e33cb24-68f7-4a5d-bfad-2722b191e500.png)

**Comment by llaske** [comment]
Hmmm. It's not a big deal and it doesn't prevent the activity to work.
I don't think it's a bug.

**Comment by NischayGoyal1** [comment]
Yeah you are right , but we can restrict it So it can improve overall User Experience
