### ISSUE TITLE
Dollar Street Activity sliders can overlap

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1212]
Hey @llaske . I have encountered an issue with the Dollar Street Activity. 
Specifically, when I try to slide the left slider all the way to the extreme right and both sliders overlap, I am unable to move the slider. I have attached a video for reference, which I would appreciate if you could review and provide your thoughts. If you agree that this is an issue, I would like to request that the issue be assigned to me :) 
Thank you!

https://user-images.githubusercontent.com/91108730/221698278-f1977cf2-d413-4d48-8e5d-25dffeeb1ec3.mp4

**Comment by llaske** [comment]
You're right it's a bug since it's not possible to change slider position once overlapped.
There's nothing like assigned issue here (see https://github.com/llaske/sugarizer/blob/dev/CONTRIBUTING.md), so feel free to work on it

**Comment by Ydvaaman** [comment]
Hey @llaske
I have raised a PR for the above Dollar Street Activity UI enhancement please refer to my PR at https://github.com/llaske/sugarizer/pull/1218
