### ISSUE TITLE
BlockRain Activity: functinality issue

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1213]
Hello @llaske, 
I have discovered a functional issue with the BlockRain activity. Whenever we press the down button, the game automatically starts without requiring us to click on the play button. However, the game should only start when we actually click on the play button. 
I wanted to bring this issue to your attention and request that you review it. If you believe it is a genuine issue, I would be interested in being assigned to address it. 
Thank you

https://user-images.githubusercontent.com/46915044/221699018-e110d334-62d3-460f-bd2c-d7ca3c3b7af0.mov

**Comment by llaske** [comment]
@rockharshitmaurya I don't think it's a bug. It's fun to be able to play in background.

**Comment by rockharshitmaurya** [comment]
Hello @llaske ,

Thank you for your response. While I understand that some users may find it enjoyable to play the game in the background without clicking the play button, _**it is important to maintain consistency in the user experience across the activity.**_

To ensure that the game only starts when the user intends to play, may I suggest adding a feature that automatically hides the play button whenever the game is started without clicking on the Play button? This way, users who wish to play in the background can still do so, while those who prefer to start the game by clicking on the play button can continue to do so without any confusion.

I appreciate your consideration in this matter and look forward to hearing your thoughts.

**Comment by llaske** [comment]
No I think it's better like this. It's a fun trick.
