### ISSUE TITLE
Abecedarium Activity: No  Example words for letter X

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1217]
Hey @llaske ,

# Issue: No example words for letter X

## Description
In the Abecedarium activity  there are alphabets and upon pressing an alphabet, a section opens with few words that start with that particular alphabet. However, there are no example words for letter X.

## Suggestion
I would like to suggest some possible words that start with X that can be used as examples for the kids. Some common words that start with X are:

- x-ray
- xylophone
- xerox
- xylem
- xenon

## Implementation
I want to implement this feature by adding a new section for letter X in the application and displaying these words along with their images and sounds.

## Additional information
I have attached the Video for the same, 
kindly look into this and share your thoughts.
So, i can work on the fix

https://user-images.githubusercontent.com/34246727/221888232-f1f65402-7e84-422e-bab9-a2c8a9cd7343.mp4

**Comment by llaske** [comment]
Images and sounds from this activity comes from [Art4apps](https://www.art4apps.org/) who provides gracefully a set of content in Creative Common license. Not all letters and words are present in all languages in this library.
It's complicated to find quality images and sounds.
Just thinking to words beginning by X is not enough.

**Comment by kanishkcs** [comment]
Hey @llaske 

Thank you for your prompt response to my issue. I completely understand that images and sounds for all letters and words may not be available in all languages, and it can be a challenging task to find quality content for the application.
However, As you suggested, just thinking of words beginning with X may not be enough, and I am willing to put in the effort to find quality images and sounds to associate with the words.

I am confident that with the help of the community, we can find or create quality content for the letter X, and make the learning experience for children more engaging and effective.

**Comment by llaske** [comment]
No. To stay consistent with current design and quality, I don't think it's a good idea to try to fix missing content by patching it with other contents.
But if you've got any suggestion of good quality educative content using a creative common license, you're welcome.

**Comment by kanishkcs** [comment]
Thank you for your reply and for considering my suggestion. I understand and respect your decision to stay consistent with the current design and quality standards.

Regarding your question about educational content, I will be happy to look for good quality content that uses a Creative Commons license and share my findings with you. Thank you for your kind offer.

I appreciate your help and guidance throughout this process, and I will close this issue now. Please let me know if you have any further questions or feedback in the future.

Best regards
