### ISSUE TITLE
TurtleBlock Activity : Stucked when trying to open

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1219]
# Issue
### Hey @llaske , I came across a problem in TurtleBlock activity , The activity has an loading issue , the screen stucked on loading part when we try to open the activity , also we cannot close the activity when it stucked hence we have to close the whole sugarizer app and restart to play other activities

# Error
![Screenshot (40)](https://user-images.githubusercontent.com/81116984/221940202-fb585a78-3f15-4955-adb7-e82d3903e1fc.png)

2)
![Screenshot (39)](https://user-images.githubusercontent.com/81116984/221940315-444f90a9-41e5-428d-87ef-4c86fb234a21.png)

**Comment by llaske** [comment]
You're right. Thanks for warning me.
It's a side effect of a [previous PR](https://github.com/llaske/sugarizer/commit/200275c9f1d6b5938784ecb03965502409c056b8#diff-67c28299d23be3a592baf9f4ec84471eba09b049f623b87642a063bc8d3a03c3).
I've just fixed it [here](https://github.com/llaske/sugarizer/commit/38326cf84bddae52dd960e7ed6da7627ef3e7366).
