### ISSUE TITLE
Tangram Activity : Game score is not updating

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1220]
Hey @llaske I came across an issue in Tangram Activity.
## Description
I would like to bring an issue to your attention regarding the Tangram Activity. Even after winning the game, my scores are not updating. I have attached a video for your reference and would appreciate it if you could review it and provide your thoughts. 
"Thank you!"

https://user-images.githubusercontent.com/91108730/221945300-664b60f7-bc7a-45dd-8e57-8bea5c665db0.mp4

**Comment by llaske** [comment]
@Ydvaaman you have to drag&drop item from the right side to the left side.

**Comment by Ydvaaman** [comment]
@llaske ohh I see sorry for the misunderstanding.
