### ISSUE TITLE
Jappy Activity : Tutorials are missing

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1225]
### Hey @llaske , I have noticed that ***Tutorials*** are missing for the jappy Activity , So i would to like to add ***Tutorial Tour*** for this activity

![Screenshot (41)](https://user-images.githubusercontent.com/81116984/222179487-1a29c015-b78c-402c-be1a-9af7bd9efe4b.jpg)

**Comment by Ayeshashaik759** [comment]
Not only in jappy activity, tutorial tours are not present in some other activities like Markdown, Pomodoro, Media Viewer, get things and scratch and in case of gears activity it has a video tutorial

**Comment by NischayGoyal1** [comment]
So can i implement the tutorial functionality for this particular activity?

**Comment by Ayeshashaik759** [comment]
> So can i implement the tutorial functionality for this particular activity?

I think @llaske will respond regarding that.

**Comment by llaske** [comment]
@NischayGoyal1 Jappy activity is deprecated and no longer deployed in the Sugarizer package.
@Ayeshashaik759 same apply for other activities you mentioned.
