### ISSUE TITLE
Ctrl+7 keyboard key not binding in TamTamMicro.activity while playing piano

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1240]
in the TamTamMicro.activity of our project, we have a feature to play piano using touch and keyboard keys from 1 to 7. Additionally, users can also use keyboard keys with Ctrl key combination to play the piano. However, I have identified an issue where the piano does not make any sound when the user presses the Ctrl+7 keyboard key. it works fine till ctrl+6. 

Steps to Reproduce:

Launch the TamTamMicro.activity
Select the piano feature
Press from ctrl+1 to ctrl+6 (that will work fine)
Press the Ctrl+7 keyboard keys (it will not work)

if you think this is an issue, please allow me to fix this issue 🥇

**Comment by llaske** [comment]
The keyboard is not intended to be used with the Ctrl key. In fact, it's difficult for children to use a combination of keys. So it's enough that it works like this.

**Comment by rockharshitmaurya** [comment]
I understand that you may not have intended to support keyboard keys with the Ctrl key combination in your piano feature. However, to ensure consistency in your application's behavior, it would be beneficial to either remove the keyboard keys with Ctrl key combinations from all notes, including notes 1 to 6, or implement support for all keys, including Ctrl+7. This would help users interact with the piano feature more efficiently and reduce any potential confusion caused by inconsistent behavior. 

Thank you for your consideration

**Comment by llaske** [comment]
Not agree I think that nothing need to be changed.
