### ISSUE TITLE
Not able to console

### ISSUE THREAD

**Issue by Vansh-Baghel** [llaske/sugarizer#1241]
* Here I was doing the activity development tutorial but was not able to console log anything.
* Its showing somewhat this message.
* Also as the app is getting opened in chrome or any other browser, I am not able to see the console log statements.
![ss1](https://user-images.githubusercontent.com/103327712/222684629-42d71cf3-9153-4cd3-a9f1-7827fe8ce84d.png)

**Comment by NischayGoyal1** [comment]
Hey @Vansh-Baghel , Use  **npm start -- --sdebug --window**
It will open debug console window

**Comment by Vansh-Baghel** [comment]
> Hey @Vansh-Baghel , Use **npm start -- --sdebug --window** It will open debug console window

Its opening the same tab which is opened using **npm start**.
Is there anything else to startup other than **npm install** and then **npm start**?

**Comment by llaske** [comment]
@Vansh-Baghel try with the latest dev branch, I've upgraded the electron version

**Comment by Vansh-Baghel** [comment]
> @Vansh-Baghel try with the latest dev branch, I've upgraded the electron version

Hey, I to be honest didn't use electron. Wasn't confident in using it.
