### ISSUE TITLE
Get Things Done Activity : plus button unaligned

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1245]
## Hey @llaske
I have found the UI issue in the Get things done activity plus button it is not properly aligned.
For reference I have attached screenshots for the same, please look and review them and give me your thoughts.

![Screenshot (411)](https://user-images.githubusercontent.com/91108730/222781198-a42c927f-18a9-4d13-965f-ea3f03c7952c.png)

**Comment by llaske** [comment]
Yes, it's true.

**Comment by Ydvaaman** [comment]
ok, @llaske I will fix it.

**Comment by Ydvaaman** [comment]
Hey @llaske
I have raised a PR for the above Get Things Done Activity button UI enhancement please refer to my PR at https://github.com/llaske/sugarizer/pull/1266
