### ISSUE TITLE
Falabracman Activity intro popup Header text & cross button UI issue

### ISSUE THREAD

**Issue by VedantSharma11** [llaske/sugarizer#1246]
hey @llaske 
In Falabracman Activity when we go to settings and start the intro there, for the last 2 popups the header and cross button is not properly styled.

# issue solved in PR: https://github.com/llaske/sugarizer/pull/1247

## Before:
![image](https://user-images.githubusercontent.com/96445392/222823157-d91cd8be-7211-468b-b4a6-d4e35c354fc5.png)

## After:
![image](https://user-images.githubusercontent.com/96445392/222823560-f8ecb77c-4a68-4710-a04c-f04fb6c3de6e.png)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1247
