### ISSUE TITLE
Padding Issue In Intro Popups in both ( Abacus Activity and Video Viewer Activity)

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1249]
Hey @llaske , As you mentioned **Padding issues** in intro popups  header in your comment on PR: https://github.com/llaske/sugarizer/pull/1239#issuecomment-1453748954 . So similar issues were existing on Abacus & Video-Viewer Activity. So I have solved both these issues in PR: https://github.com/llaske/sugarizer/pull/1248

#### 1)
![image](https://user-images.githubusercontent.com/81116984/222830663-bc35dd5c-e96d-41d1-acee-aca1b4b44246.png)

#### 2)
![image](https://user-images.githubusercontent.com/81116984/222831090-586e478b-ce4e-48ed-8c03-d266609fad41.png)

**Comment by llaske** [comment]
Yes you're right. Good point.

**Comment by llaske** [comment]
Fix in https://github.com/llaske/sugarizer/pull/1248
