### ISSUE TITLE
Overflow issue in Mind math Activity for screen size 1536x793

### ISSUE THREAD

**Issue by VedantSharma11** [llaske/sugarizer#1250]
hey @llaske ,
In the Mindmath Activity during the intro tutorial when the "slots" popup comes up Scrollbars appear whick breaks the UI.

**This issue is not there in smaller screen size but exists at device width:1200px**
# solved in PR: https://github.com/llaske/sugarizer/pull/1260
**Please give your thoughts**

### Snippet
---
![image](https://user-images.githubusercontent.com/96445392/222834965-e3090f81-ddd3-4b59-93e3-bb2a2867c589.png)

**Comment by llaske** [comment]
I don't reproduce the issue on my side.
Tested on 1280x750

**Comment by VedantSharma11** [comment]
@llaske yes you are right because this issue exists on screen size 1536x793 .

On your screen it must be showing like this:

![WhatsApp Image 2023-03-05 at 05 22 58](https://user-images.githubusercontent.com/96445392/222934266-0f294f6b-2624-4c33-a6f1-bba0df2f2a76.jpg)

### so i would like to correct this issue for screen size 1536x793.

**Comment by llaske** [comment]
No I think it doesn't mind. It's not a standard screen size for children.
