### ISSUE TITLE
UI issue in Intro Headers in ( Chess , Clock Web , Calculator ) Activity

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1251]
Hey @llaske , I have found UI issues in following activities ( **Chess** , **Clock Web** , **Calculator** ) , The text and the button are not aligned , 
**Please look at the snippets for the reference** and allow me to fix them

### Snippets
* * *
#### 1)
![image](https://user-images.githubusercontent.com/81116984/222835101-677cd21e-bc5f-4531-beb1-86c9c39a796a.png)

---
#### 2)
![image](https://user-images.githubusercontent.com/81116984/222835190-d6ac3601-3609-4f45-bf45-30bd8c555f41.png)

---
##### 3)
![image](https://user-images.githubusercontent.com/81116984/222835302-16642a48-c4bc-4f18-b58b-1baf83298914.png)

**Comment by llaske** [comment]
I don't have the issue on my side.

![image](https://user-images.githubusercontent.com/981841/222930796-58c4927b-ec5a-424d-93d4-4fc516567ddd.png)


![image](https://user-images.githubusercontent.com/981841/222930760-65edc216-33bf-4f13-a2a4-9d788c2ec66d.png)


![image](https://user-images.githubusercontent.com/981841/222930743-0a71b08b-d68a-4503-b8ec-b67d49cf366b.png)

**Comment by NischayGoyal1** [comment]
But on my side the alignment for header are not correct
I have tested it on all screen sizes

![image](https://user-images.githubusercontent.com/81116984/222931279-050f9d68-5091-448a-a15b-f2261fb788a5.png)

**Comment by NischayGoyal1** [comment]
But @llaske  on my side the alignment for header are not correct
I have tested it on all screen sizes (14 inch and 15 inch screens)
Tested it on : 1280x698 and 1536x793

Can you please try to test it by resizing your window

![image](https://user-images.githubusercontent.com/81116984/222931279-050f9d68-5091-448a-a15b-f2261fb788a5.png)

**Comment by llaske** [comment]
I guess it's screen resolution dependent. 
These resolutions are not the most common for children, plus this is a minor drawback for a minor feature.
I think we could ignore it.
