### ISSUE TITLE
Measure Activity intro popup header issue & overflow issue

### ISSUE THREAD

**Issue by VedantSharma11** [llaske/sugarizer#1252]
hey @llaske 
In the Measure Activity there are alignments issue in  intro headers and also in one popup the content overflows and scrollbars appear.

### Solved in PR:https://github.com/llaske/sugarizer/pull/1307
**Look at the snippets & Please give your thoughts**

## Snippets
---
![image](https://user-images.githubusercontent.com/96445392/222836604-77fa41c2-cd9c-456e-8fa3-79eb87a86787.png)

![image](https://user-images.githubusercontent.com/96445392/222836629-b61d1700-9814-4417-842d-371558590f37.png)

![image](https://user-images.githubusercontent.com/96445392/222836622-3609ac45-98d5-4c6b-8b6d-f86c9127d82d.png)

**Comment by llaske** [comment]
Yes you're right.

**Comment by VedantSharma11** [comment]
@llaske I'm working on the fix
