### ISSUE TITLE
QR code Activity: buttons are unaligned

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1253]
Hey @llaske
I have found the UI issue in the QR code activity left side drop-down button is not properly aligned as compared to the right side button.
For reference I have attached screenshots for the same, please look and review them and give me your thoughts.

![Screenshot (333)](https://user-images.githubusercontent.com/91108730/222859979-081d74d1-6ebe-4a95-8d16-98d0670c690f.png)

# Left side dropdown button
![Screenshot (00)](https://user-images.githubusercontent.com/91108730/222860533-e5311979-edaa-4e70-b6cb-11fd6c615954.png)

# Right side button
![Screenshot (01)](https://user-images.githubusercontent.com/91108730/222860571-79ad8a98-7e37-4cd7-a01a-8567db703075.png)

**Comment by llaske** [comment]
Yes, that's right

**Comment by Ydvaaman** [comment]
ok, @llaske I am working on it.

**Comment by Ydvaaman** [comment]
Hey @llaske
I have raised a PR for the above QR code Activity button UI enhancement please refer to my PR at https://github.com/llaske/sugarizer/pull/1287

**Comment by llaske** [comment]
Fixed by https://github.com/llaske/sugarizer/pull/1287
