### ISSUE TITLE
Story Activity: Mouse pointer UI issue on scrollbar

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1254]
## Hey @llaske
I have found the UI issue in the Story activity, when I try to point the mouse pointer on the scrollbar to scroll the slider the mouse pointer does not appear instead of the mouse pointer the text pointer appears on the scroll bar.
For reference I have attached a screenshot and video for the same, please look and review them and give me your thoughts.

![1](https://user-images.githubusercontent.com/91108730/222863268-9ba9e15f-4aa5-472c-a230-d38c5b2778a9.jpg)

https://user-images.githubusercontent.com/91108730/222863517-fbb48764-11f2-4791-955e-0e11cd1f62a5.mp4

**Comment by llaske** [comment]
Hmmm. Hard to see but that's right.

**Comment by Ydvaaman** [comment]
😂 ok @llaske I am working on it.

**Comment by Ydvaaman** [comment]
Hey @llaske
I have raised a PR for the above story activity mouse cursor UI enhancement please refer to my PR at https://github.com/llaske/sugarizer/pull/1288

**Comment by llaske** [comment]
Duplicate https://github.com/llaske/sugarizer/issues/1281, now fixed
