### ISSUE TITLE
Markdown Activity: Mouse pointer UI issue on scrollbar

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1255]
## Hey @llaske
I have found the UI issue in the Markdown activity, when I try to point the mouse pointer on the scrollbar to scroll the slider the mouse pointer does not appear instead of the mouse pointer the text pointer appears on the scroll bar.
For reference I have attached a screenshot and video for the same, please look and review them and give me your thoughts.

![IMG20230304074408](https://user-images.githubusercontent.com/91108730/222870740-900ee82d-6f97-4573-8c5e-462ae50d2b3c.jpg)

https://user-images.githubusercontent.com/91108730/222870619-288ab0b4-9cf1-4da5-a10a-961ed8e10263.mp4

**Comment by llaske** [comment]
That's right. Same in Write activity.

**Comment by rockharshitmaurya** [comment]
> That's right. Same in Write activity.



> That's right. Same in Write activity.

hey @llaske i have fixed the issue in this PR(https://github.com/llaske/sugarizer/pull/1276) please review it

**Comment by Ydvaaman** [comment]
Thank you @rockharshitmaurya 👍

**Comment by Ydvaaman** [comment]
Hey @llaske
I have raised a PR for the above Markdown activity mouse cursor UI enhancement please refer to my PR at https://github.com/llaske/sugarizer/pull/1289

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1289
