### ISSUE TITLE
Request to Add Full-Screen Mode Option in ChatPrototype.activity

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1257]
I noticed that ChatPrototype activity currently doesn't have a full-screen mode option, and I would like to request that this feature be added in a future update. If you think this is a good idea, I would like to work on it.

Before :
<img width="1280" alt="Screenshot 2023-03-04 at 10 35 43 AM" src="https://user-images.githubusercontent.com/46915044/222877240-be3930b3-6817-4b06-8fbc-0c97cc8aadcf.png">
After :

https://user-images.githubusercontent.com/46915044/222878139-083ffa6d-e3b5-4a97-8a3d-3e0350899d21.mov

**Comment by VedantSharma11** [comment]
@llaske in SPEECH ACTIVITY also there is no full screen mode , i think it should have a full screen mode as the activity works well on touchscreen devices. what are your thoughts?

**Comment by llaske** [comment]
No, typing text is not practical on mobile device.

**Comment by VedantSharma11** [comment]
@llaske okay but fullscreen mode is also not present in SPRINT MATH activity in which we just need to touch the correct options again and again ! your thoughts?

**Comment by llaske** [comment]
No, Sprint Math is a deprecated activity.

**Comment by VedantSharma11** [comment]
oh Sry my bad i did not knew that , by the way @llaske  where can i find the list for activities which are depricated?

**Comment by llaske** [comment]
You can't, you should ask 😄

**Comment by VedantSharma11** [comment]
😅Then can you pls tell me @llaske  so that i remember from next time.
