### ISSUE TITLE
Adding a new activity feature

### ISSUE THREAD

**Issue by Kunal7069** [llaske/sugarizer#1258]
A new quiz activity in various fields, including math, science, and English grammar...
If you allow I would like to work upon this....

**Comment by llaske** [comment]
The Exerciser activity already allow to create quiz.

**Comment by Kunal7069** [comment]
> The Exerciser activity already allow to create quiz.

We can work on graphics and animations and can add more topics for quiz such as basic science and English vocablaury..

**Comment by llaske** [comment]
@Kunal7069 it's a work for teachers, not developers
