### ISSUE TITLE
Adding a new activity Dictionary feature

### ISSUE THREAD

**Issue by Kunal7069** [llaske/sugarizer#1259]
This activity will have a feature of telling meanings and synonyms of any English word.

**Comment by llaske** [comment]
Writing a dictionary activity is not the complex part.
The hard work is to find a good quality existing dictionary,  multi-language, with a creative common license and who could work offline (since no every Sugarizer has an internet connection)

**Comment by Kunal7069** [comment]
So if you allow can I work to find a such dictionary 
or find any alternate way?

**Comment by Kunal7069** [comment]
@llaske if you allow can I work on this and find any alternate way so that this activity could also work offline?

**Comment by llaske** [comment]
@Kunal7069 first give me links on open content you plan to use
