### ISSUE TITLE
Stopwatch Activity :Overflow issue

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1263]
## hey @llaske 
I found a side-scrollbar overflow issue in the Stopwatch activity when we add some extra time laps and after that, we try to click on the help button then due to pop there is an overflow issue in the last 2 pop-up dialog boxes.

For reference I have attached a screenshot and video for the same, please look and review them and give me your thoughts.

![Screenshot (45)](https://user-images.githubusercontent.com/91108730/222917378-98a27017-81eb-4db7-8766-c638d4923e0b.png)

https://user-images.githubusercontent.com/91108730/222917371-df82aca9-d1ed-4da3-8407-29d5e1b9a011.mp4

**Comment by llaske** [comment]
Okay. That's true.

**Comment by Ydvaaman** [comment]
ok @llaske I am working on it

**Comment by Ydvaaman** [comment]
Hey @llaske
I have raised a PR for the above issue please refer to my PR at https://github.com/llaske/sugarizer/pull/1326

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1326
