### ISSUE TITLE
Qr Code Activity DropDown Button UI

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1267]
Hey @llaske 
In the QR activity 
The Text dropdown Button is not properly alighned  with rest of the element in the Input Field.
alos there is a extra arrow in the image, which is slightly visible
Before
![image](https://user-images.githubusercontent.com/34246727/222919293-9af705a0-3be5-4224-bf56-e8035eb645e2.png)

it should Look like this

![image](https://user-images.githubusercontent.com/34246727/222919274-3121b2c7-3afd-4729-b988-6840c0ef3483.png)

Please do share your thought on this , if you think it can be improved.
Do let me Now, i have allready fixed it localy.

**Comment by NischayGoyal1** [comment]
Hey @kanishkcs , This issue is already raised see https://github.com/llaske/sugarizer/issues/1253

**Comment by kanishkcs** [comment]
Thanks @NischayGoyal1  , i didnt noticed it ,
