### ISSUE TITLE
QR activity Photo Loading Icon Overlaping

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1268]
Hey @llaske 

the Image loading icon , and Drop Down  icon is overlapping Each other in the Photo Activity of QR activity

![image](https://user-images.githubusercontent.com/34246727/222922142-fa1da199-b2e2-46bc-843f-5a0c02f7dbe0.png)

We can fix it ,by keeping it next to the drop down icon
like this 
![image](https://user-images.githubusercontent.com/34246727/222922601-b898e5e1-cda0-4f8f-a2a3-c7f9228741e7.png)

Please share your thought on this.

**Comment by llaske** [comment]
You're right but I think the spinner should be set under the bar near the camera.

**Comment by kanishkcs** [comment]
Ok @llaske , can i have a marked area , where you want particulary the spinner?

**Comment by llaske** [comment]
@kanishkcs do the best you can

**Comment by kanishkcs** [comment]
hey @llaske 
![image](https://user-images.githubusercontent.com/34246727/223623849-34ddf51b-2c93-479e-94e1-a3bc33255331.png)

as per your suggestion i have put the loading spinner under the bar , near the camera,
kindly review changes and  provide feedback if you want any further improvement.

**Comment by llaske** [comment]
No I think it's better to put the spinner in the white zone under the arrow. Not in the search bar.

**Comment by kanishkcs** [comment]
Hey @llaske 

Preview of the Changes:
![image](https://user-images.githubusercontent.com/34246727/225534496-7a91ec89-de0e-4dc5-b2f6-6f2d34cf8dcb.png)


I have raised the Pr #1334 , kindly Review it. If any further changes is required do let me Know.

Thanks and Regards.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1394
