### ISSUE TITLE
Calligra Activity: Popup UI enhancement

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1270]
## Hey @llaske 
I have found a UI issue in Calligra activity when we are going to insert a new word by pressing the insert button then a popup appears
then the popup heading text is not aligned properly.
For reference I have attached screenshots for the same, please look and review them and give me your thoughts.

# Before
![Screenshot (49)](https://user-images.githubusercontent.com/91108730/222924992-8e383edf-2728-4a20-8c16-f969f7760404.png)

# After

![Screenshot (50)](https://user-images.githubusercontent.com/91108730/222925005-65b3791a-f882-41d7-964e-bb8da2573c0a.png)

**Comment by llaske** [comment]
No, it's the standard UI for Sugar popup. The empty left space is for a potential icon.

**Comment by Ydvaaman** [comment]
ok @llaske
