### ISSUE TITLE
Ebook Activity : Want to map keys to the pagination

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1273]
Hey @llaske , i want to add feature to Ebook activity , I want to map left and right arrow keyboard key to the paginations of ebooks, So that we can just change the pages by just pressing the keys
It will provide good user experience and feel

![image](https://user-images.githubusercontent.com/81116984/222932624-0f149241-1040-4227-803b-f2a6d0a35ecb.png)

**Comment by llaske** [comment]
Sure. Why not.

**Comment by NischayGoyal1** [comment]
Thanks ilaske , i am working on it

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1292
