### ISSUE TITLE
VideoViewer Activity add key mapping

### ISSUE THREAD

**Issue by VedantSharma11** [llaske/sugarizer#1274]
### In the video viewer activity , I have found some issues. I would like you to review them & give your thoughts

+ ### Functionality break:  when I try to resize the window the library section popup breaks, the scrollbar comes on half of the section. I am attaching video for reference
---
https://user-images.githubusercontent.com/96445392/222932951-8aa2e93d-d11f-44d8-b1fb-c70e15038d30.mp4

## Suggestion for mapping Arrow keys

+ ### I would like to add keyboard eventlisteners on the left and right, page changing buttons Because since there are so many pages it becomes   tiring to change the pages by clicking on buttons instead i would like to implement the functionality of left & right arrow keys to change pages which would improve the UX.
---
![Screenshot 2023-03-05 043721](https://user-images.githubusercontent.com/96445392/222933600-7276aef5-b1eb-4d31-80f7-0eada7f13c83.png)

**Comment by llaske** [comment]
I'm okay to add a key mapping.

No for the resize feature. This popup is just displayed at the first start, we don't need to change it.

**Comment by VedantSharma11** [comment]
@llaske I'll work on the key mapping part then.

**Comment by VedantSharma11** [comment]
@llaske i have raised the pr please review it

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1327
