### ISSUE TITLE
UI issue in All Activity  Button icon Not working in Full Screen View 

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1278]
hey @llaske 

i have found a UI issue in  All Sugarizer activities,

if the `activity-palette'`s  `container` is active  , and we switch 
to full screen view, the toggle button becomes un responsive , hence we cant no longer close the  `activity-palette'`s  `container`.

#Steps to Produce #

1. Toggle  `activity-palette'`s  `container` icon.
2. Switch to Full Screen View.

![image](https://user-images.githubusercontent.com/34246727/222941062-8061a66d-40e4-4370-bf79-4701028ef840.png)

### Video ### 

https://user-images.githubusercontent.com/34246727/222944606-37a7abee-c104-4b96-b87e-141ff35ac491.mp4

Kindly share your thought on this , So  i can work on the fix.

**Comment by llaske** [comment]
You're right but it's a very rare use case and it's not a blocking problem.
We can ignore it.
