### ISSUE TITLE
UI issue : (Exerciser , Fototoon , Fraction) Activity

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1279]
## Hey @llaske 
I have found a UI issue in various activities popup search bar is not properly aligned.
For reference I have attached screenshots for the same, please look and review them and give me your thoughts.

# Exerciser Activity:
![Screenshot (62)](https://user-images.githubusercontent.com/91108730/222941020-d323b17c-a3f0-4073-8404-dbfd7d1b2dd8.png)

# Fototoon Activity:
![Screenshot (58)](https://user-images.githubusercontent.com/91108730/222941202-551c380d-a3b3-4391-b142-3c84af589408.png)

# Fraction Activity:
![Screenshot (59)](https://user-images.githubusercontent.com/91108730/222941095-a4f1766e-47e2-44da-9be7-9a17def38791.png)

**Comment by llaske** [comment]
No. It's the standard way to display popup in Sugar UI.

**Comment by Ydvaaman** [comment]
ok @llaske
