### ISSUE TITLE
UI issue : (Paint , Write) Activity

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1280]
## Hey @llaske 
I have found a UI issue in various activities popup search bar is not properly aligned.
For reference I have attached screenshots for the same, please look and review them and give me your thoughts.

# Paint Activity:
![Screenshot (60)](https://user-images.githubusercontent.com/91108730/222941398-f5e1d205-a1af-4585-bfcb-c25accca95c5.png)

# Write Activity:
![Screenshot (52)](https://user-images.githubusercontent.com/91108730/222938674-e183786a-9209-49b9-9018-a6abdc6aecc9.png)

**Comment by llaske** [comment]
No. It's the standard way to display popup in Sugar UI.

**Comment by Ydvaaman** [comment]
ok @llaske
