### ISSUE TITLE
Bad cursor pointer on scrollbar

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1281]
That's right. Same in Write activity.

_Originally posted by @llaske in https://github.com/llaske/sugarizer/issues/1255#issuecomment-1454906559_

Hey, @llaske I have found the same issue in all the activities of sugarizer, please look and review them and give me your thoughts. if you think this is an issue I would be happy to fix it. 

https://user-images.githubusercontent.com/46915044/222942394-5ac402b0-5887-4319-9ca9-a47d9833e460.mov

**Comment by llaske** [comment]
It's really a minor problem.
If we can find a very simple way to improve that, why not. Else we could ignore it.

**Comment by Hazemkak** [comment]
Hello @llaske I have already solved the problem but i can't push my changes due to permissions so can you please allow me to make the PR , Thanks

**Comment by rockharshitmaurya** [comment]
Hey @Hazemkak since I found this issue I'll be glad to fix it , thanks for showing your interest

**Comment by rockharshitmaurya** [comment]
> It's really a minor problem. If we can find a very simple way to improve that, why not. Else we could ignore it.

Sir, I have created a PR taking into account your suggestions. Could you please review it and provide your feedback?

**Comment by Ydvaaman** [comment]
> Hey @Hazemkak since I found this issue I'll be glad to fix it, thanks for showing your interest

This is the right approach: if someone identifies an issue, they should try to solve it themselves. If they are unable to find a solution, then they can ask for help from others.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/08836106e8f03e554625003a55ad9a3211c074c3
