### ISSUE TITLE
Activity icon Underflow in Calculator Activity

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1282]
Hey @llaske 
in  Calculator activity  , if we toggle the  `activity-palette'`s  `container` and switch to full screen, the  `activity-palette'`s  `button` goes under the page , which hides  the button partialy.

![image](https://user-images.githubusercontent.com/34246727/222942724-bb8c0fc8-aebb-4e79-9b7a-2f547a4ef224.png)

### Video ###

https://user-images.githubusercontent.com/34246727/222944331-477e2898-621b-4174-bc99-e345a6aa150b.mp4

**Comment by llaske** [comment]
Very rare use case and not blocking problem.
We can ignore it.

**Comment by kanishkcs** [comment]
Dear @llaske ,

Thank you for your feedback on the issue regarding the activity-palette's container in the Calculator activity. I appreciate your taking the time to review the issue and provide your feedback.

If this is considered a rare use case and not a blocking problem, I understand that it may not be a priority to address this issue at this time.

Thank you again for your response
