### ISSUE TITLE
Tour UI Enhancement in LastOneLoses.activity

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1283]
Hey @llaske , There seems to be an issue with the animation in the background of the LastOneLoses.activity tour. Specifically, in the second step of the tour, the shadow behind the main item does not appear to fit properly, resulting in an undesirable appearance.

it look like this currently : 
<img width="1280" alt="Screenshot 2023-03-05 at 12 12 12 PM" src="https://user-images.githubusercontent.com/46915044/222946121-b4ac6a4b-c285-4ab2-a61e-23e8bf63b9f6.png">

it can be further improved by this : 

<img width="1280" alt="Screenshot 2023-03-05 at 12 05 41 PM" src="https://user-images.githubusercontent.com/46915044/222946320-80c5dce8-97b7-435b-89b4-274785d2e4ed.png">

give your thoughts on this :)

**Comment by llaske** [comment]
The tutorial has changed. Upgrade your repo.

**Comment by rockharshitmaurya** [comment]
I have checked in the updated repo the issue is still persisted, can I work on it?
 
<img width="1280" alt="Screenshot 2023-03-07 at 8 47 18 AM" src="https://user-images.githubusercontent.com/46915044/223311683-92a8ba11-580c-43d4-a95d-5eb4948699b8.png">

**Comment by llaske** [comment]
It's correct on my side 

![image](https://user-images.githubusercontent.com/981841/223843078-dcf2dbdc-ca20-444a-8678-13199fc37cec.png)

**Comment by rockharshitmaurya** [comment]
I'm talking about the shadow effect that is in the background. that shadow is not properly in a rectangular shape around the main container.

like this : https://user-images.githubusercontent.com/46915044/222946320-80c5dce8-97b7-435b-89b4-274785d2e4ed.png

**Comment by llaske** [comment]
Got it now. it is so insignificant that I had not seen it.
Not an issue.
