### ISSUE TITLE
Sugarizer offers Shutdown and Reset 

### ISSUE THREAD

**Issue by jvonau** [llaske/sugarizer#129]
Sugarizer offers Shutdown and Reset when serving from a server on a network while there is no logout. How does one change from one user to another user from the same web browser? Closing the page and opening it again restored the prior session without offering to login again.
![screenshot_2017-09-22_17-06-11](https://user-images.githubusercontent.com/5579710/30769964-b665f674-9fea-11e7-9e86-57399202b5e2.png)

**Comment by llaske** [comment]
Yes you're right, it's not possible today. It's planned for the next version with a true login system.
In the meantime, two tip&tricks:
- Go to settings/about my computer and click several time on the Sugarizer version. A checkbox will appear to let you clean all journal/settings of the current user
- Go to settings/my server on an user already connected, you will see the user id. If you copy/paste this id on another browser, Sugarizer will retrieve settings and remote journal of the user.

**Comment by llaske** [comment]
Released in https://github.com/llaske/sugarizer/releases/tag/v1.0
