### ISSUE TITLE
Physics Js Activity : Nav bar still active in fullscreen mode

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1290]
Hey @llaske , I have found a functionality break in physics js activity , In full screen mode the the navbar buttons are not visible but they are still working , Whereas they should not as like in other activities 
I am attaching video for reference,  give your thoughts

### Video

https://user-images.githubusercontent.com/81116984/222986453-5bc02f7f-bd3e-4cbf-bca4-67a8691c39b6.mp4

**Comment by llaske** [comment]
I could be an undocumented fun feature but it could be risky (if the user click the Clear item).
So yes it's a bug.

**Comment by NischayGoyal1** [comment]
@llaske i have fixed it in PR : https://github.com/llaske/sugarizer/pull/1291

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1291
