### ISSUE TITLE
Undefined tutorial step in curriculum activity

### ISSUE THREAD

**Issue by disha1202** [llaske/sugarizer#1293]
In case there is only one step in tutorial, although both the buttons are disabled, but if you click on next button it displays an undefined tutorial step.

[screen-recorder-mon-mar-06-2023-12-14-45.webm](https://user-images.githubusercontent.com/58461801/223038282-46e86113-3d6f-46b4-bdf7-cbd56652a278.webm)

**Comment by llaske** [comment]
Oh you're right.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1336
