### ISSUE TITLE
Improve Usability of Calculator Activity: Add Clear Button for Result Area

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1294]
Hey @llaske 

### Description
Currently, there is no clear button for the result area in the Calculator activity in Sugarizer. To clear the result, users have to close the activity, which can be inconvenient. Therefore, I suggest adding a clear button to the activity that would allow users to clear the result without having to close the activity.

### Proposed   Solution
Add a clear button that would appear next to or below the result area in the Calculator activity. When clicked, the button would clear the result area and reset the calculator to its default state.

### Benefits 

- Provides a more convenient way for users to clear the result area.
- Improves the usability of the Calculator activity.

### Possible Implementation 
The clear button could be implemented as a new button widget in the Calculator activity's UI. When clicked, the button would trigger a function to clear the result area and reset the calculator results  to its default state. 

![image](https://user-images.githubusercontent.com/34246727/223042758-84b5e394-b0b5-47cb-bf5c-0e9c4c8c144a.png)

I would like to ask for your feedback on whether this enhancement request is valid and if it's feasible to add a clear button for the result area in the Calculator activity. If it is, I would be interested in working on this issue

**Comment by llaske** [comment]
No, it's important to keep the history.
If the user want to start from a clear view, he could create a new instance

**Comment by kanishkcs** [comment]
Thanks for the Response @llaske.
