### ISSUE TITLE
Abacus Activity: Result Overlaps with Undo Full Screen Icon in Full-Screen View

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1295]
Hey @llaske 
### Description

In the Abacus activity in Sugarizer, when in full-screen view, If the Rods are Less then 15 .the result of the abacus calculation gets overlapped by the undo full screen icon. This can make it difficult to read the result and can be confusing for users.

### Steps to Reproduce

Open the Abacus activity in Sugarizer.

- Choose Rods Less then 15  e.g 14
- Enter a calculation in the abacus.
- Click on the full screen icon to enter full-screen view.
- Observe that the result of the calculation is overlapped by the undo full screen icon.

### Expected Behavior
The result of the abacus calculation should be visible and not overlap with any UI elements, including the undo full screen icon.

 ### Actual Behavior

The result of the abacus calculation is overlapped by the undo full screen icon when in full-screen view.

Screenshots
![image](https://user-images.githubusercontent.com/34246727/223046975-b34083d4-8ba3-4649-b997-b72c0aa534a8.png)

###  Possible Solution
One possible solution could be to adjust the positioning of the undo full screen icon or the result area to ensure that they do not overlap. Another solution could be to adjust the size of the UI elements to allow more space for the result area.

I would like to ask for your feedback on whether this request is valid and if it's feasible improve the result area in the Abacus activity. If it is, I would be interested in working on this issue

**Comment by llaske** [comment]
No it's a rare case and the work around is to unfull screen

**Comment by kanishkcs** [comment]
Okay @llaske ,thanks for the response.

**Comment by kanishkcs** [comment]
Thanks for the Response @llaske  ,
