### ISSUE TITLE
Stopwatch activity: Activity dropdown UI issue

### ISSUE THREAD

**Issue by VedantSharma11** [llaske/sugarizer#1297]
## Snippets
---
### The way it is:
![121](https://user-images.githubusercontent.com/96445392/223359473-5c06803c-d5f9-4971-a694-785bc7365a8b.png)

### The way it should be like in other activities:
![8798](https://user-images.githubusercontent.com/96445392/223359482-0cfd617e-1cbb-488a-9743-d6356a7b62d5.png)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1300
