### ISSUE TITLE
QR code Activity: Bug in full screen mode

### ISSUE THREAD

**Issue by VedantSharma11** [llaske/sugarizer#1298]
## Video
---
### How it is:

https://user-images.githubusercontent.com/96445392/223362444-d86c79ff-ee98-45ff-b7c2-e94b7a6e88a3.mp4

## After: Removing the functionality in fullscreen mode so that by mistake if the user types anything and press enter the qr will not change

https://user-images.githubusercontent.com/96445392/224069932-21dacbd6-0239-4069-a4f0-933a4266c962.mp4

**Comment by llaske** [comment]
Full screen mode in QR code activity is just for displaying the code to be able to share it.
The users don't click on the board when in full screen mode.
It's not an issue.

**Comment by VedantSharma11** [comment]
@llaske  okay then I think we can completely remove its functionality when in fullscreen mode  , As when fullscrren mode is activated the left dropdown and the textbox all are functional but not visible.
Pls give your thoughts on this suggestion

**Comment by VedantSharma11** [comment]
@llaske okay then I think we can completely remove its functionality when in fullscreen mode , As when fullscrren mode is activated the left dropdown and the textbox all are functional but not visible.
Pls give your thoughts on this suggestion

**Comment by llaske** [comment]
No. We can keep it.
