### ISSUE TITLE
Info button pop-up goes out of screen in full-screen mode in Tank Operation Activity

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1299]
hey @llaske, I found an issue in the Tank Operation Activity, where the Info button generates a pop-up that goes out of the screen in full-screen mode. This makes it difficult to read the information in the pop-up and affects the user experience, If You think this is an issue I will be happy to fix it.

https://user-images.githubusercontent.com/46915044/223408573-d7970533-34f6-43f0-b630-7eec67be05cc.mov

**Comment by llaske** [comment]
Not an essential feature

**Comment by rockharshitmaurya** [comment]
Hi @llaske , I appreciate your response, but I believe that fixing the pop-up issue would greatly improve the user experience.  Would you be open to considering a fix for this? Thank you.

**Comment by llaske** [comment]
No, there is no user experience here.
