### ISSUE TITLE
Difficulties with mongodb

### ISSUE THREAD

**Issue by georgejhunt** [llaske/sugarizer#130]
Testing internet-in-a-box, we have discovered that mongodb seems to randomly allocate up to 800MB of disk space, during the install process, even when we set the prealloc=no flag.  So we were wondering what loss of function, which activities would degrade, if we just did not load mongodb?

**Comment by holta** [comment]
Full Details @ https://github.com/iiab/iiab/issues/254

**Comment by llaske** [comment]
Issue transfered to Sugarizer Server https://github.com/llaske/sugarizer-server/issues/27
