### ISSUE TITLE
QR code Activity: Textbar unaligned

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1306]
## Hey @llaske 
I have found a UI issue in the QR code activity the text bar is unaligned if it would be aligned it would look much better.
For reference I have attached a screenshot for the same, please look and review them and give me your thoughts.

# Before
![Screenshot (77)](https://user-images.githubusercontent.com/91108730/223509563-9490d52d-9a75-4537-99ad-55376082fada.png)

# After
![Screenshot (76)](https://user-images.githubusercontent.com/91108730/223509674-9bb06697-9051-43c0-af85-892d0cf5f8c4.png)

**Comment by llaske** [comment]
No we don't need a such alignment.
