### ISSUE TITLE
Jappy Activity doesn't work on Chrome OS

### ISSUE THREAD

**Issue by abdulsamad234** [llaske/sugarizer#131]
I just discovered that when i open up the jappy activity, it doesn't work and just shows a blank screen and no buttons to do anything, i cannot go back, and the only option i have is to quit the sugarizer program.

**Comment by llaske** [comment]
Could you tell on which browser/environment you're testing ?

**Comment by abdulsamad234** [comment]
I'm testing it as an extension on a chrome browser.

**Comment by llaske** [comment]
Okay. I see.
Unfortunately, Jappy activity can't work on Chrome OS or as Chrome Extension.
See more information here: https://github.com/llaske/sugarizer/pull/124

**Comment by abdulsamad234** [comment]
Okay 👍

**Comment by llaske** [comment]
Starting from [v1.1](https://github.com/llaske/sugarizer/releases/tag/v1.1.0), Sugarizer is no longer distributed as a Chrome OS application.
Jappy works on Chrome and on the Electron (with Chromium) version.
