### ISSUE TITLE
QR Code Camera Activity: Fullscreen button Does Not Work

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1314]
Hey @llaske  ,
I found this issue in QR code Camera Activity where the full screen button Does not do anything.

Is it supposed to have such behaviour or is it a bug?
if it is meant to not work in the camera activity we can hide the Full screen Button .

If it is bug , I would like to fix it.
Kindly share your thought on this.

https://user-images.githubusercontent.com/34246727/223625993-0359be82-9f7d-47a8-a333-6bd3bb3fb6d7.mp4

**Comment by llaske** [comment]
Which OS? Which browser?

**Comment by llaske** [comment]
Can't reproduce on my side.
What's this logo?

<img width="329" alt="image" src="https://user-images.githubusercontent.com/981841/224513906-0abbd95d-6cff-4f66-84d7-975ecb6ea46c.png">

 Do you use a specific camera?
Are you sure your browser has access to it? Does the video works into another web app?

**Comment by kanishkcs** [comment]
Hey @llaske  the camera works properly fine , 

the issues lies in the full screen toggle Button .

### Screenshot
![image](https://user-images.githubusercontent.com/34246727/224526179-30ce11c0-42fc-40e3-b891-b3fd7d6f19b6.png)

The  `fullscreen` Toggle Button Does not work.

Is it supposed to have such behaviour or is it a bug?
if it is meant to not work in the camera activity we can hide the Full screen Toggle  Button .

**Comment by llaske** [comment]
Oh okay. Not an issue, the fullscreen button is just to have the QR code in fullscreen.
