### ISSUE TITLE
UI issue : FotoToon Actitvity So Much Padding in Warning Pop Up

### ISSUE THREAD

**Issue by kanishkcs** [llaske/sugarizer#1318]
Hey @llaske ,
i found this issue in FotoToon activity.

If we click the clean all icon a warning Pop up shows. 
the Pop up buttons elements `cancel` and `continue`  have extra  width which doesnt follow the sugarizer UI .

### Current
![image](https://user-images.githubusercontent.com/34246727/223918257-e2043018-4262-44b6-9b2a-2925c22094c1.png)

### How it should Be
![image](https://user-images.githubusercontent.com/34246727/223918317-32905acd-8301-49c9-bb6a-8b3ce12c25c5.png)

It can be improved by a minor change in the CSS .
If you think it can be improved do let me know your thoughts on this.
I would love to fix it.

**Comment by llaske** [comment]
No, it's good like that.
