### ISSUE TITLE
Acitivity Idea: Sprint Math

### ISSUE THREAD

**Issue by Survivor75** [llaske/sugarizer#132]
I have an idea for a new Activity, sprint math where the user has to decide the output of a math problem in a given time frame by clicking left or clicking right. It can be fun and engaging.

**Comment by llaske** [comment]
Do you think to something like the Sugar Arithmetic activity: http://activities.sugarlabs.org/fr/sugar/addon/4204 ?

**Comment by Survivor75** [comment]
Yeah, I has a different user interface in mind, however the purpose is same.
Closing this.

**Comment by llaske** [comment]
The Arithmetic activity has a poor interface and because it's written in Python, it don't work on Sugarizer. If you think that you could rewrite it in JavaScript with a better UI, do not hesitate.

**Comment by Survivor75** [comment]
Yeah, I have thought of some features to gamify it with a cool UI, so I'll work on that.

**Comment by manki11** [comment]
I was working on a similar one.

**Comment by hardiked** [comment]
does anyone working on it? I would like to work on it. Please let me know.
