### ISSUE TITLE
Abecedarium Activity: Unexpected behaviour with language change button

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1321]
Hey @llaske , i have found a functionality break in **Abecedarium Activity** ,  tutorial popup is been visible but the "Change Language" button is not visible there(mainly "Country flag" image on button is not displaying). In the last screen i.e. Game Finished Screen, initially the "Change Language" button is not visible. But when i switch to full-screen mode and return back to normal mode, "Change Language" button starts appearing which is not the expected behavior. Also clicking the ( "Country flag" image) button show unexpected popup, 
Please find the attached video for reference:

https://user-images.githubusercontent.com/81116984/223954325-4494c59b-b3b3-4e6e-bb64-ffa3b20fa7d6.mp4

**Comment by llaske** [comment]
Hmmm. It is unlikely that an user click on the help button here. It's not blocking. Not an issue.

**Comment by NischayGoyal1** [comment]
But if we turn off the full screen mode , the langauge button shows up, And if user clicks it is show unexpected popup

See
![image](https://user-images.githubusercontent.com/81116984/224514463-5acf93f7-20b7-413e-b63c-12ee1e3448d9.png)

**Comment by llaske** [comment]
Yes you're right. Good point.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1328
