### ISSUE TITLE
ChatPrototype Activity: UI enchancement

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1322]
## Hey @llaske 
I have noticed a UI issue in the ChatPrototype activity where the message written in the footer section has no right padding. 
I have attached a screenshot for your reference. Can you please review it and share your thoughts?

# Before
![Screenshot (79)](https://user-images.githubusercontent.com/91108730/223977230-fed688f7-905c-4ca9-8779-5795fd150c65.png)

# After
![Screenshot (78)](https://user-images.githubusercontent.com/91108730/223977268-8aeee5eb-9b41-4422-945d-52e601b5913f.png)

**Comment by Ydvaaman** [comment]
Hey, @llaske please have a look at this.

**Comment by llaske** [comment]
Chat activity UI need to be rethink, I'm not in favor of doing minor style change.

**Comment by Ydvaaman** [comment]
Ok @llaske , I understand that you're interested in enhancing the user interface (UI) of the chat activity. Could you please elaborate on the specific areas you'd like to improve?

**Comment by llaske** [comment]
I haven't thought about it yet

**Comment by Ydvaaman** [comment]
Ok @llaske 👍🏻

**Comment by vinayaknayar** [comment]
If no one is working on this, I would like to work on this.  @llaske

**Comment by Ydvaaman** [comment]
@vinayaknayar I will we working on this issue just waiting for the llaske approval 😊

**Comment by llaske** [comment]
@Ydvaaman @vinayaknayar everyone could suggest an UI Design.
BTW because I don't think about the expected design yet, I can guaranty to accept your suggestion.

**Comment by llaske** [comment]
Expected UI is describe here https://github.com/llaske/sugarizer/issues/1356
