### ISSUE TITLE
Vote Activity: UI enhancement

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1323]
Hey @llaske 
I have identified a UI issue in the Vote activity. When we open the 'Which is your favorite animal?' game in fullscreen mode, there is very little padding between the header and the game container. 
I have attached a screenshot for your reference. Could you please take a look and share your thoughts on it?

# Before
![Screenshot (81)](https://user-images.githubusercontent.com/91108730/224008696-3de658ca-8de9-4199-9d88-237418e21eea.png)

# After
![Screenshot (80)](https://user-images.githubusercontent.com/91108730/224008777-20fb775f-53a6-478f-82cc-75a94d28d16c.png)

**Comment by llaske** [comment]
No. The margin is okay.

**Comment by Ydvaaman** [comment]
Yes, @llaske the margin is right but I am talking about the space between the header and the game container. There is no space between them please have a look into this.

**Comment by llaske** [comment]
No, it's good like that.

**Comment by Ydvaaman** [comment]
ok @llaske
