### ISSUE TITLE
Tangram Activity: UI enhancement

### ISSUE THREAD

**Issue by Ydvaaman** [llaske/sugarizer#1324]
## Hey @llaske 
I have identified a UI issue in the Tangram activity. In the Miscellaneous section, the size of the shopping cart container is very big as compared to the other containers and there is much space between the buttons.
I have attached a screenshot for your reference. Could you please take a look and share your thoughts on it?

![Screenshot (82)](https://user-images.githubusercontent.com/91108730/224018135-65828329-961f-4037-a327-02b4f65c670c.png)

**Comment by AdityaDey-80** [comment]
### I WANT TO WORK ON THIS ISSUE

UI can be updated in the following ways-
Padding
Margin
Border
Border radius

Thanks and regards
### ADITYA DEY

**Comment by llaske** [comment]
No it's very dependent of the screen size.

![image](https://user-images.githubusercontent.com/981841/224164080-4fe6590f-79fd-4e24-b8e8-660beb2ce05f.png)

Plus because it concern editing only, it's not important.

**Comment by Ydvaaman** [comment]
Ok @llaske
