### ISSUE TITLE
UI issue in Description Box of ( Calculate Activty and Sprint Maths)

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer#1325]
Hey @llaske , I have found a styling issue in ( Calculate Activity and Sprint Maths) , These both are using bootstrap libraries , so Sugar-Web CSS and bootstrap CSS are clashing resulting in creating UI issue in Description box 
Also we if we try to fix the UI issue it is very difficult to make the exact replica of description box of other activites, So we can make these activities bootstrap free or or we can fix the issue keeping Bootstrap (Give Your suggestions)
See the attached screen shots for reference

![image](https://user-images.githubusercontent.com/81116984/224153593-882d1e89-26fa-42c7-9134-e197d81e3704.png)

![image](https://user-images.githubusercontent.com/81116984/224153676-9a29d74d-6770-48c2-a407-7ae894f71772.png)

## After removing bootstrap
![image](https://user-images.githubusercontent.com/81116984/224155121-0fe2fce4-fdaf-47b3-93e2-d00a834190cf.png)

**Comment by VedantSharma11** [comment]
@NischayGoyal1 sprintMath activity is deprecated check here: https://github.com/llaske/sugarizer/issues/1257#issuecomment-1455167082

**Comment by NischayGoyal1** [comment]
Thanks for telling @VedantSharma11  , but i already knew that Sprint-Maths is depricated, And also there is no loss in correcting  both these activities as both have same solution

**Comment by llaske** [comment]
Bootstrap has an impact on styling so I'm not in favor of removing it in activity using it. 
It will require heavy testing to ensure there is no impact to remove it.

**Comment by NischayGoyal1** [comment]
So instead of removing bootstrap we can just change the **CSS** of description box.

**Comment by llaske** [comment]
Seems related to https://github.com/llaske/sugarizer/issues/1303

**Comment by llaske** [comment]
@Vishalk91-4 , will be better to work on https://github.com/llaske/sugarizer/issues/1303
It seems more logical to be able to move only vertically.

**Comment by Vishalk91-4** [comment]
@llaske I saw this box issue in most of the activities, so should I change all the boxes to vertical direction, and do you want them to go till the end of the page in vertical direction
If we do it that we I think it goes beyond the page so should I keep some space between bottom line and the box, just for UI

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1522
