### ISSUE TITLE
Bug in sound card in Memorize

### ISSUE THREAD

**Issue by sanatankc** [llaske/sugarizer#133]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20373641/33521606-1a4a5690-d7fd-11e7-830a-4e2d342e2c09.gif)

### Bug Explanation
If I click twice on any of the Card in Sound version of Memorize. Then it never hides. (Try to click on all card twice).

### Steps to reproduce:
1. Go to Memorize activity.
2. Click on Sound Version.
3. Click twice on any Card.

**Comment by llaske** [comment]
You're right, it's a bug. cc @mikklfr

**Comment by kunal-mohta** [comment]
I think I have solved this issue, should I send an MR?

**Comment by llaske** [comment]
Yes please, send a PR (Pull Request).

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/9dab33ace662bf806490614b3ca3fcc3dcda9cf8

**Comment by llaske** [comment]
Released in https://github.com/llaske/sugarizer/releases/tag/v1.0
