### ISSUE TITLE
Multiple Cursors in the E-Toys activity

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer#1330]
Hey @llaske , I noticed a bug in the Etoys Activity where both the normal as well as sugarized cursor are visible and they overlap.

I guess we should hide the original pointer when present in the Etoys Activity.

https://user-images.githubusercontent.com/75615092/224798205-e160920b-f26d-435a-a94c-47e6b1bef500.mov

What do you think ?

**Comment by llaske** [comment]
E-Toys activity is deprecated an no longer distributed with the app.
