### ISSUE TITLE
Improve design of "unfullscreen" button in Falabracman Activity

### ISSUE THREAD

**Issue by rockharshitmaurya** [llaske/sugarizer#1333]
When using the full-screen mode in the Falabracman Activity, the "unfullscreen" button appears in the top right corner of the screen. However, the current design doesn't look visually appealing and doesn't fit well with the overall UI of the activity. To improve the design, I suggest adding some space between the button and the top and right edges of the screen. this will make the button more visually appealing.

### Before :
<img width="1280" alt="Screenshot 2023-03-16 at 4 45 46 AM" src="https://user-images.githubusercontent.com/46915044/225466077-79e00d2d-b5a4-4701-a5b6-8e20189fe371.png">

### After :
<img width="1280" alt="Screenshot 2023-03-16 at 4 44 49 AM" src="https://user-images.githubusercontent.com/46915044/225466016-7db76e17-f464-41a6-8991-0541d04738f1.png">

**Comment by llaske** [comment]
There is no mandatory position/margin for the unfullscreen button.
Margin is not a requirement we can leave it that way.

**Comment by rockharshitmaurya** [comment]
but sir @llaske  Adding space around the unfullscreen button would improve its appearance. Can we make this change?

**Comment by llaske** [comment]
@rockharshitmaurya nope
