### ISSUE TITLE
Application window on desktop opens with no frame.  

### ISSUE THREAD

**Issue by Anujverma89** [llaske/sugarizer#1335]
When we run desktop application it launches without frame  which creates difficulty in navigation. Can we include frame in window? It can be fixed by modifying the browser window property of electron.
 
**BEFORE MODIFYING BROWSER WINDOW PROPERTY**
![Screenshot from 2023-03-17 12-22-36](https://user-images.githubusercontent.com/68897803/225902888-f63bdd90-c00f-4aab-87fa-3360a02eb0e5.png)

**AFTER MODIFYING BROWSER WINDOW PROPERTY**
![Screenshot from 2023-03-17 12-29-39](https://user-images.githubusercontent.com/68897803/225901974-a09dba89-84b8-424c-a99b-c558bdff1e4f.png)

**Comment by llaske** [comment]
It's on purpose so the children could stay concentrate on the application.
A `--window` option already exist to run it in a Window. See https://github.com/llaske/sugarizer/tree/dev#sugarizer-application
