### ISSUE TITLE
Matching not Allowed from right side

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer#1337]
Hey @llaske , I noticed a issue in Exerciser Activity's Animal Sound lesson that we can't match columns from other side.

https://user-images.githubusercontent.com/75615092/226218736-6e4b564a-8f2e-498f-97ba-5783cdea51fa.mov

wasn't sure if it was a issue or not. What do you think ?

I recommend it would be better if we could allow matching from both ends.

**Comment by llaske** [comment]
Yes you're right it's frustrating

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/ExerciserReact/pull/164
