### ISSUE TITLE
Text Alignment and visibility issue in stopwatch Activity

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer#1338]
Hey @llaske , i noticed a bug in the stopwatch activity where the breakpoint text are not Aligned properly and if we have multiple breakpoints the some of the disappears.

I recommend to have a proper Alignment  for these text and also to have a scrollable area to look at all these text.
if not then to make all the breakpoints visible.

<img width="1320" alt="Screenshot 2023-03-20 at 5 38 45 AM" src="https://user-images.githubusercontent.com/75615092/226219181-a4d5c74b-24c1-4e91-a8ad-810cff7d3ac0.png">

What do you think?

**Comment by llaske** [comment]
Duplicate https://github.com/llaske/sugarizer/issues/1342
