### ISSUE TITLE
Close popup when clicked on white space

### ISSUE THREAD

**Issue by Shruti-codes236** [llaske/sugarizer#1339]
When we open any drop box, it closes only after we click on it again.
A better user flow can be that it can also close if we click on any place other than that box.

https://user-images.githubusercontent.com/76914026/226403222-3f039598-e3f7-418b-b033-e448789564aa.mov

**Comment by Shreyas-SAS** [comment]
I think that it is a valid point. @llaske can you please check this? If @Shruti-codes236 isn't working on it I am open to take it up.

**Comment by llaske** [comment]
That's the way it suppose to work on Sugar Design.
