### ISSUE TITLE
Canvas should be centred in TankOp_activity.

### ISSUE THREAD

**Issue by shubhangNarain** [llaske/sugarizer#1340]
Hey @llaske ! I came across one of the activities in Sugar activities where the game canvas wasn't centred on the whiteboard. We could achieve a more cleaner look for the activity by simply entering the canvas along with the whiteboard. Also, I've made some UI changes to the activity as well, I've opened a Pull Request - #1341, accordingly and attached a before and after of the same. Please do review and merge it. Do let me know if there's anything we could do more on this.

Before:

![image](https://user-images.githubusercontent.com/80174035/226767090-8cb1bbcd-67c1-4846-83d0-beed88634cc1.png)
After:

<img width="1440" alt="TankOP_Final" src="https://user-images.githubusercontent.com/80174035/226767319-dc6d2513-757d-4cd3-a666-09714f4d5ea8.png">

**Comment by llaske** [comment]
No that's fine like this.
