### ISSUE TITLE
Stopwatch activity does not allow logging of all timestamps.

### ISSUE THREAD

**Issue by shubhangNarain** [llaske/sugarizer#1342]
Hey @llaske !, In `stopwatch.activity` when logging the results it skips the previous timestamp entries when the user tries to log a larger number of timestamp entries in it. I've made a Pull Request - #1341 regarding the same. Please do look and review it. Thanks.
I've attached an image of the issue here below:

<img width="1440" alt="Stopwatch_main" src="https://user-images.githubusercontent.com/80174035/226772358-e84e0ebb-c5c6-46bd-a320-167ecf28de0c.png">

**Comment by ABHINAV-JHA-27** [comment]
Hey @shubhangNarain ,  I think  i opened a Issue regarding the same as well. Make sure to check present issues before opening a one.

**Comment by ABHINAV-JHA-27** [comment]
> There is no need to be able to log a large number of entries

Hey @llaske , I do understand that we dont need to log a large number of entries but dont you think there is a issue with alignment as well. I guess we should at least rectify it.

**Comment by llaske** [comment]
No, that's fine like that.
