### ISSUE TITLE
No end button available in tutorial of home screen in dev branch but same is available in master branch

### ISSUE THREAD

**Issue by Anujverma89** [llaske/sugarizer#1343]
@llaske Sir i have noticed that no end button available in tutorial of home screen in dev branch but same is available in master branch is it by design or a bug ?

Home screen of Sugarizer Dev branch
![Screenshot from 2023-03-22 18-00-28](https://user-images.githubusercontent.com/68897803/226906866-e421359f-dafd-4014-ac28-0c56b537feb1.png)
Home screen of Sugarizer master branch 

![Screenshot from 2023-03-22 18-00-45](https://user-images.githubusercontent.com/68897803/226907158-5c0308d9-55bc-43cd-a30b-915eb4818538.png)

**Comment by rockharshitmaurya** [comment]
hey @Anujverma89, in the sugarizer repo contribution are being made in the dev branch the master branch in not been updated yet the home screen tour which you are seeing in the master branch is written in bootstrap and is now replaced with intro.js in the dev branch if you want to find issue find them in dev branch, not in master.
