### ISSUE TITLE
Activity description box have a bug

### ISSUE THREAD

**Issue by DhruvMishra1826** [llaske/sugarizer#1346]
While going through sugarizer, i seen that there is a bug in description box of few activities, and one of them is shown below.
The text area is not having any constraint of size and its going even beyond the description box and this looks really awkward and will provide bad impression on user.

@llaske i fell its a bug and can be resolved. What's your take on this.

**Current look :**
![WhatsApp Image 2023-03-25 at 10 31 02 AM](https://user-images.githubusercontent.com/78314127/227697375-4a55cde4-97b0-4a34-9af5-ff829a3a2b8b.jpeg)

**Proposed Result :** 

https://user-images.githubusercontent.com/78314127/227697495-c7734e8e-311c-41a9-9eec-9a9b817fecce.mp4

**Comment by DhruvMishra1826** [comment]
@llaske If it is fine with you, I'd like to work on this.

**Comment by DhruvMishra1826** [comment]
@llaske what's your take in this case ?

**Comment by llaske** [comment]
This issue duplicate https://github.com/llaske/sugarizer/issues/1303

**Comment by DhruvMishra1826** [comment]
@llaske No, sir actually that issue which he figured out is on repository named as "Exerciser React" which was fixed few days ago. But the bug which i have pointed is on the current dev branch of sugarizer. So, it seems it is yet unsolved.

**Comment by raazseth** [comment]
Can you assign me this project? @llaske

**Comment by DhruvMishra1826** [comment]
@raazseth i am on it. My PR is waiting for @llaske approval.

**Comment by rockharshitmaurya** [comment]
> @raazseth i am on it. My PR is waiting for @llaske approval.

 @llaske means this issue is duplicate someone is already working on it , you can not rise issue for same issue multiple times

**Comment by DhruvMishra1826** [comment]
> > @raazseth i am on it. My PR is waiting for @llaske approval.
> 
> @llaske means this issue is duplicate someone is already working on it , you can not rise issue for same issue multiple times

No that's not the case. It's my issue thread and @raazseth was asking to assign this to him that's it.

**Comment by rockharshitmaurya** [comment]
> > > @raazseth i am on it. My PR is waiting for @llaske approval.
> > 
> > 
> > @llaske means this issue is duplicate someone is already working on it , you can not rise issue for same issue multiple times
> 
> No that's not the case. It's my issue thread and @raazseth was asking to assign this to him that's it.

but I'm talking about @llaske's reply in which he mention that this issue is duplicate

**Comment by DhruvMishra1826** [comment]
> > > > @raazseth i am on it. My PR is waiting for @llaske approval.
> > > 
> > > 
> > > @llaske means this issue is duplicate someone is already working on it , you can not rise issue for same issue multiple times
> > 
> > 
> > No that's not the case. It's my issue thread and @raazseth was asking to assign this to him that's it.
> 
> but I'm talking about @llaske's reply in which he mention that this issue is duplicate

It's still unresolved and the context of that issue was different.

**Comment by llaske** [comment]
This issue duplicate https://github.com/llaske/sugarizer/issues/1303
The problem exist in all activities, it should be fixed in all activities
