### ISSUE TITLE
Hot Key "/" to focus the search field

### ISSUE THREAD

**Issue by vinayaknayar** [llaske/sugarizer#1348]
The idea is to add a Hot Key to focus on the Search Field like we have in some applications, for example: youtube.

**Comment by raazseth** [comment]
Hello Can you assign me this project?

**Comment by vinayaknayar** [comment]
> Hello Can you assign me this project? @llaske

I already made a PR for this issue.

**Comment by llaske** [comment]
It's useless. Remind you that Sugarizer target children not necessarily familiar with Youtube and handling Sugarizer with a touch screen where hoot keys has no sense.
