### ISSUE TITLE
Measure activity Id

### ISSUE THREAD

**Issue by UtkarshSiddhpura** [llaske/sugarizer#1351]
#### metadata:
https://github.com/llaske/sugarizer/blob/9630e2a2cbab435a65e2239bdac25b13a897a630/activities/Measure.activity/js/activity.js#L864

#### activity.info
https://github.com/llaske/sugarizer/blob/9630e2a2cbab435a65e2239bdac25b13a897a630/activities/Measure.activity/activity/activity.info#L4

#### activities.json
https://github.com/llaske/sugarizer/blob/9630e2a2cbab435a65e2239bdac25b13a897a630/activities.json#L58

**Comment by llaske** [comment]
Could you explain the problem?
I can export an instance on my disk the reimport it.

**Comment by UtkarshSiddhpura** [comment]
### Basically what i'm trying, is to show ".txt" log from measure activity in Journal Dialog .
### So i used this filter : 

`var filters = [ { mimetype: "text/plain"}, ];
`

- But when `journalchooser.js` try to get the activity which exports "text/plain" type ,for styling and icon of that item.

- `var activity = activities[entry.metadata.activity]`  

- The metadata.activity  `"org.olpcfrance.Measure"`  is not present in  `activities` array.

![measure](https://user-images.githubusercontent.com/90092555/229041271-9c0709d8-4d9b-4869-b3f9-085a9a71dd1c.png)

**Comment by llaske** [comment]
Okay got it. It's not a bug. When the [Chart activity](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2023.md#sugarizer-word-puzzle-and-chart-activities) will be implemented we will associate CSV files to Chart activity so we could directly open CSV from the Journal. But you're right it will probably require some change in Measure activity too.
