### ISSUE TITLE
Porting sugarizer Journal module to vueJS component.

### ISSUE THREAD

**Issue by Anujverma89** [llaske/sugarizer#1352]
@llaske Sir ! can i work towards developing Journal component  using VueJS ?

**Comment by llaske** [comment]
There is a dedicated project to port Sugarizer Core to VueJS: https://github.com/sugarlabs/GSoC/blob/master/Ideas-2023.md#sugarizer-vuejs-core
Porting Journal will be done after this project because it require handling offline mode and to avoid too much complexity it's not planned for the moment.

**Comment by Anujverma89** [comment]
@llaske Sir i'm aware about the that project but I have gone through functionality and use cases of journal and i guess it's a independent module which relies on **sugar web, local storage and other supporting libraries** so can be implemented independently without needing to effect other modules(**except palette.js**). I think i can port it to vueJS, so if you don't mind i will port it to vueJS and if it matches with the sugar standards and you are satisfied with it you merge it in main project.  If you are ready i will  develop a visual representation of how it will be implemented using flow chart and attach it here.

**Comment by llaske** [comment]
@Anujverma89 thanks for your proposal but I want to avoid parallelize these projects.

**Comment by Anujverma89** [comment]
@llaske okay sir !!
