### ISSUE TITLE
New enhanced UI for Chat Activity

### ISSUE THREAD

**Issue by vinayaknayar** [llaske/sugarizer#1356]
As mentioned earlier, Chat activity UI needed to be rethought. Here is the Figma Link to the design approved by @llaske 
Figma Link: https://www.figma.com/file/A4RDcgCuTfC4JxQkec02KH/Sugarizer-Chat-Activity?type=design&node-id=0%3A1&t=XkDWZuwypF1illlz-1
Image: 
![image](https://user-images.githubusercontent.com/98237998/236647017-568a11f9-256f-4c7b-b8c3-d42fe0de2da5.png)

**Comment by samyakshah3008** [comment]
Hey @llaske , I believe this issue is resolved. can we close this? Since it is good to have open issues which actually needs some work to be done. 😄 
If there is some work required, can you highlight it?

**Comment by llaske** [comment]
@samyakshah3008 you're right.
Fixed in https://github.com/llaske/sugarizer/pull/1399

**Comment by samyakshah3008** [comment]
Cool ✅
