### ISSUE TITLE
Improving the navbar's UI with the content

### ISSUE THREAD

**Issue by abhinav2712** [llaske/sugarizer#1363]
The nav items animation is overlapping with the content: 
![image](https://github.com/llaske/sugarizer/assets/68495520/2d711ae3-cd28-42a7-85f3-114a6c87acff)
Assign me this issue, i can work on it

**Comment by UtkarshSiddhpura** [comment]
I think you're looking to contribute to this repository: https://github.com/llaske/sugarizer-doc

**Comment by abhinav2712** [comment]
@UtkarshSiddhpura ohh yeah, okay
