### ISSUE TITLE
QR activity, spinner hidden and the text box has lot of spaces to it's right

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1364]
@llaske , it's a small issue but after reading some previous issues I found that the spinner was there previously i don't see it know, do you want it back under the arrow and there were a lot of spaces to the right of the text boxes which could be removed

![image](https://github.com/llaske/sugarizer/assets/116670999/8e8bdb1a-da8c-4c00-9f21-5de56d2a5639)

I don't know why there are two arrows within one

**Comment by Amithbhise007** [comment]
assign this issue to me and i solve it
i have depth knowledge of javascript and css

**Comment by llaske** [comment]
> there were a lot of spaces to the right of the text boxes which could be removed

The space depend of the window width. On the standard screen size, it's not a lot.

![image](https://github.com/llaske/sugarizer/assets/981841/73200155-265c-4843-a0c2-55fa1082376b)

**Comment by Vishalk91-4** [comment]
Yes @llaske , I forget to check on other devices and it looked fine
Thanks
