### ISSUE TITLE
Buttons remain below the shapes in fototoon activity

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1368]
In the Fototoon Activity, when the shapes overlap the buttons appear below the shapes
![Screenshot 2023-06-17 091623](https://github.com/llaske/sugarizer/assets/116670999/b9a19de8-41bc-4e05-94ce-5c6b080bb789)

The resize, edit, remove these buttons remain below the rectangle shapes in Title box and Rectangle Type, when their position is being displaced
![Screenshot 2023-06-17 091601](https://github.com/llaske/sugarizer/assets/116670999/04877fac-8dcc-4206-a397-791ab5b61fe2)
![Screenshot 2023-06-17 091610](https://github.com/llaske/sugarizer/assets/116670999/87255544-2478-4a92-a026-652e9745a4c9)

**Comment by llaske** [comment]
Yes you're right.
Duplicate https://github.com/llaske/sugarizer/issues/1221
