### ISSUE TITLE
Clicking On Play Again should stop gear Activity

### ISSUE THREAD

**Issue by sanatankc** [llaske/sugarizer#137]
Right Now Only way to stop Gear Activity is by clicking on other button (which is not apparent). 
Clicking on play button again should stop Gear activity.

![screen shot 2017-12-05 at 7 14 45 am](https://user-images.githubusercontent.com/20373641/33585785-02c58fea-d98c-11e7-8812-5cd2dc203993.png)

**Comment by kunal-mohta** [comment]
I wonder why isn't it working despite of [these lines](https://github.com/llaske/sugarizer/blob/master/activities/Gears.activity/js/activity.js#L85-L87).

**Comment by llaske** [comment]
No, I guess the demo mentioned is for tutorial mode (click on the question mark icon).

**Comment by kunal-mohta** [comment]
I am able to solve this issue, but there is still one problem.
I can't find the function that unselects the button, as in the selection background doesn't disappear.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30414954/34327637-83d66808-e8ef-11e7-8657-df3d0b2ed2ac.gif)

**Comment by llaske** [comment]
I'm not sure it's important to unselect it because all buttons on the toolbar are in selected mode (i.e. there is always one button selected). So let it selected.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/84ff1254948906b77ba54dc0514beb852391e76c

**Comment by llaske** [comment]
Released in https://github.com/llaske/sugarizer/releases/tag/v1.0
