### ISSUE TITLE
Adding Uniformity in the Clock Activity Taskbar 

### ISSUE THREAD

**Issue by AryanGupta0007** [llaske/sugarizer#1375]
![clock](https://github.com/llaske/sugarizer/assets/111166297/2a6ecc5a-5f66-4fb5-b586-abda6a6ddcbb)
2 options show As " Show  minutes/ hours"  and others as write  which will make all the options uniform
. So i am making all of them as Show instead of Write which looks better according to me.

**Comment by llaske** [comment]
Hmmm. It depends. "Write" could mean "Writing as text" the time and date. Since "Display" could mean "Graphically display" seconds and days.

**Comment by AryanGupta0007** [comment]
So instead of Show Minutes (original) it could be better to say Show Minute Hand?
