### ISSUE TITLE
Replace WebL10n to i18next in all activities

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#1378]
![Capture d’écran du 2023-07-09 18-18-55](https://github.com/llaske/sugarizer/assets/981841/08690e61-0dc4-4ad3-8d4e-232df8e853d4)

Currently localization in Sugarizer activities relies on [WebL10n localizaton framework](https://github.com/fabi1cazenave/webL10n).

This framework is outdated and no longer actively maintained. So in order to ensure continued support and modern localization capabilities, we decided  to migrate to the [i18next internationalization framework](https://www.i18next.com/).

This change require an update of all Sugarizer activities. The migration process, which depends on whether the activity is written in Vanilla JS or Vue.js, is described [here](https://github.com/llaske/sugarizer/blob/dev/docs/webL10n2i18n.md). Two activities have already been migrated [QRCode](https://github.com/llaske/sugarizer/pull/1371) and [Measure](https://github.com/llaske/sugarizer/pull/1371).

The objective of this issue is to migrate to i18next each activity:
* [x] Abacus
* [x] Abecedarium
* [x] Blockrain
* [x] Calculate
* [x] Calligra
* [x] Chart
* [x] ChatPrototype
* [x] Chess
* [x] Clock
* [x] ColorMyWorld
* [x] Constellation
* [x] Curriculum
* [x] DollarStreet
* [x] EbookReader
* [x] Falabracman
* [x] Flip
* [x] FoodChain
* [x] Fototoon
* [x] FractionBounce
* [x] GameOfLife
* [x] GetThingsDone
* [x] Gridpaint
* [x] Implode
* [x] LabyrinthJS
* [x] LastOneLoses
* [x] Markdown
* [x] MazeWeb
* [x] Measure
* [x] MediaViewer
* [x] Memorize
* [x] MindMath
* [x] Moon
* [x] Paint
* [x] PhysicsJS
* [x] Planets
* [x] Pomodoro
* [x] QRCode
* [x] Record
* [x] Reflection
* [x] SharedNotes
* [x] Speak
* [x] SprintMath
* [x] Stopwatch
* [x] Story
* [x] TamTamMicro
* [x] Tangram
* [x] TankOp
* [x] TurtleBlocksJS
* [x] VideoViewer
* [x] Vote
* [x] Write
* [x] XOEditor
* [x] XmasLights

Please make **one different PR for each activity**.

Before sending your PR, please ensure:
* There is no error in the browser console
* The activity still works when the Sugarizer language is changed
* All "old" localization files (.ini, po/*) are removed

**Comment by Rohan20-10** [comment]
@llaske  while creating pull request if I am making changes to a particular activity directory on a particular branch when its checking for automated merging it checks the differences for all the files on my branch and not that particular directory. So this goes up to changes in all 869 files. Will u pls help me out with this .

**Comment by llaske** [comment]
> @llaske while creating pull request if I am making changes to a particular activity directory on a particular branch when its checking for automated merging it checks the differences for all the files on my branch and not that particular directory. So this goes up to changes in all 869 files. Will u pls help me out with this . I have faced this problem in my pull requests [#1472 ](https://github.com/llaske/sugarizer/pull/1472), [#1475](https://github.com/llaske/sugarizer/pull/1475) ,[#1476](https://github.com/llaske/sugarizer/pull/1476)

It's because you're not doing change on dev branch.

**Comment by Rohan20-10** [comment]
> > @llaske while creating pull request if I am making changes to a particular activity directory on a particular branch when its checking for automated merging it checks the differences for all the files on my branch and not that particular directory. So this goes up to changes in all 869 files. Will u pls help me out with this . I have faced this problem in my pull requests [#1472 ](https://github.com/llaske/sugarizer/pull/1472), [#1475](https://github.com/llaske/sugarizer/pull/1475) ,[#1476](https://github.com/llaske/sugarizer/pull/1476)
> 
> It's because you're not doing change on dev branch.
@llaske Thanks for ur suggestion. Done changes in pr [#1478](https://github.com/llaske/sugarizer/pull/1478) and [#1479](https://github.com/llaske/sugarizer/pull/1479). Pls review those.
