### ISSUE TITLE
Tutorial Section missing in Jappy

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1390]
I didn't find tutorial section in Get Things Done and it was ok, since it didn't contained many functionalities, but
In Jappy I think we should add tutorials as there are some amount of functionalities

![image](https://github.com/llaske/sugarizer/assets/116670999/bdc3cf7c-1c25-4d21-990b-6eb34104d336)

**Comment by llaske** [comment]
Jappy is deprecated and not deployed with the app package.
Same for TurtleJS.
So it don't need a tutorial.
