### ISSUE TITLE
Foodchain Activity, Score gets added up when activity is reopen

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1404]
Hi @llaske, in the Foodchain Activity, 

I found that, after restarting the game, the score of my previous game also adds up to it
![Screenshot 2023-08-31 221032](https://github.com/llaske/sugarizer/assets/116670999/08e40329-fabb-4c51-b87a-a0eabd257dea)
![Screenshot 2023-08-31 221051](https://github.com/llaske/sugarizer/assets/116670999/7d2f0887-a297-4f66-bfb4-2e203cc7d4bf)

Images overlap, and the game cannot be started after a snake has eaten, at the initial point i.e the position of snake should change after one life is gone, otherwise 2 lifes are gone at same time, since there is a delay of revival
![Screenshot 2023-08-30 071712](https://github.com/llaske/sugarizer/assets/116670999/50c29754-4af4-4079-8902-0c82a214075c)
![Screenshot 2023-08-31 214337](https://github.com/llaske/sugarizer/assets/116670999/e7c55660-ec19-4e4c-ad57-9dcc7e09b25c),

**Comment by llaske** [comment]
That's true for the score, image overlap is already declared here https://github.com/llaske/sugarizer/issues/1191

**Comment by Vishalk91-4** [comment]
@llaske, can I work on it to fix this issue

**Comment by llaske** [comment]
@Vishalk91-4 sure

**Comment by gauravsingh94** [comment]
@llaske  I have  resolved the reported issue. Please take a moment to review the changes and provide your feedback.

**Comment by llaske** [comment]
I've reviewed the full activity.
It appears that the score is kept from one game to the next in the whole activity (Learn, Build and Play).
It seems that it score is more to show the investment of the player in the game than to compete with other players.
So we don't need to change the current behavior.
Thanks for your help @Vishalk91-4  and @gauravsingh94
