### ISSUE TITLE
Calculator does not display graph

### ISSUE THREAD

**Issue by sahran99** [llaske/sugarizer#141]
When a function is entered into the calculator and enter is pressed, the graph does not display. I am on chrome version 62.0.3202.94

Before equal sign is clicked:
![image](https://user-images.githubusercontent.com/34138005/33732063-cd19e880-db4a-11e7-9290-8bf3f5193f53.png)

After equal sign is clicked:
![image](https://user-images.githubusercontent.com/34138005/33732087-e7ba1296-db4a-11e7-8a24-c67852d69d84.png)

**Comment by llaske** [comment]
Can't reproduce the issue on the same Chrome version.
Could you look if there is any message in the browser console.

**Comment by sahran99** [comment]
Well now the graph and calculator is displaying. It was not displaying for the past 2 days, so I do not know what the issue was.
