### ISSUE TITLE
[Feature] Add linting (eg: prettier)

### ISSUE THREAD

**Issue by Tweniee** [llaske/sugarizer#1417]
"prettier": "prettier \"{,e2e/**/,projects/**/,src/**/}*.{md,java,json,y(a)?ml,html,js,ts,tsx,css,scss}\"",
"prettier:check": "npm run prettier -- --check",
"prettier:fix": "npm run prettier -- --write",

**Comment by Tweniee** [comment]
@mohitvdx i'll not suggest you to start working on this as no one from the sugarizer team approved this 



> Hi, can you please describe the issue more?

The development project now incorporates linting tools to automatically format the code for proper indentation.

**Comment by llaske** [comment]
@Tweniee not all activities use the same indentation policy.
For maintenance reason (i.e. to be able to track real change in files), it's not a doable to reformat all files.
So we should take care of it in each contribution.
