### ISSUE TITLE
A message / pop-up when no name is given

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1419]
@llaske, can we have like a message / pop up when user clicks on the next button but no name was entered

![image](https://github.com/llaske/sugarizer/assets/116670999/8a1ddca0-4a0c-480e-a8f6-7154ed24c4f5)

**Comment by llaske** [comment]
@Vishalk91-4 I think it's obvious. In case it's not, the help button is here.

**Comment by SayyedSajdeen** [comment]
Hi Dear Team,

Can We Work On This On Your This Issue.

Thanks & Regards
Sayyed Sajdeen

**Comment by llaske** [comment]
@SayyedSajdeen it's not an issue.

**Comment by SayyedSajdeen** [comment]
Dear Team,

Thanks for your reply.

Thanks & Regards
Sayyed Sajdeen
