### ISSUE TITLE
Food Chain Activity bug

### ISSUE THREAD

**Issue by sahran99** [llaske/sugarizer#142]
It is not possible to re-spawn after the frog dies.
![image](https://user-images.githubusercontent.com/34138005/33777974-6b13e25e-dc0c-11e7-881b-209ddd719721.png)
The frog pictures at the bottom right of the screen suggests that there are two more lives left. If there is a way to re-spawn, I suggest making it more obvious such as pressing space-bar or clicking a button as I am not able to find it.

**Comment by llaske** [comment]
When the frog die a new frog is automatically display again.
Not sure to understand where is the issue.

**Comment by kunal-mohta** [comment]
I think this issue should be closed.

**Comment by llaske** [comment]
Not a real issue.
