### ISSUE TITLE
Enhancing the Markdown Activity

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1424]
We don't have a tab for generating Table through Markdown
And like the Quote and the Code tabs also don't have any differentiating UI, may cause confusion between quote and text written

![Screenshot 2023-12-14 075548](https://github.com/llaske/sugarizer/assets/116670999/865d8fe4-2cf7-4dcc-87b4-1c529664132f)

Just a suggestion which I think can be done here
@llaske what do you think about it

**Comment by Raushankumar-prog** [comment]
<table style="width:100%; border:1px solid black;">
 use style as inline css in the order to  produce the table.

**Comment by Raushankumar-prog** [comment]
<table style="border: 1px solid black; padding: 8px;">
      <thead>
        <tr>
          <th>Company</th>
          <th>Contact</th>
          <th>Country</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Alfreds Futterkiste</td>
          <td>Maria Anders</td>
          <td>Germany</td>
        </tr>
        <tr>
          <td>Centro comercial Moctezuma</td>
          <td>Francisco Chang</td>
          <td>Mexico</td>
        </tr>
      </tbody>
    </table>

**Comment by Vishalk91-4** [comment]
@Raushankumar-prog, my point is that a tab would be great to generate rather than writing lines and lines whenever we use and to change the layout of the Markdown Activity a bit
@llaske any suggestion/review

**Comment by llaske** [comment]
@Vishalk91-4 thanks for the suggestion but the markdown activity is deprecated.
Markdown activity was interesting when there was no other activity to do some text formatting but it's useless since Write activity is here.
