### ISSUE TITLE
Misalignment of close button on intro dialog boxes 

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1428]
The close button on the intro dialog boxes in dev.sugarizer.com are bugged, whereas on server.sugarizer and try.sugarizer they are fine. 

<img width="1180" alt="dev bugged button" src="https://github.com/llaske/sugarizer/assets/64434937/cc5029b0-5558-46ae-b4c1-63d8dc0308a0">

Upon comparing them on both the websites, there is an additional line-height property for the introjs-skipbutton class in the dev site, which when removed fixes the issue. This property is missing on the other sites.

<img width="854" alt="Screenshot 2023-12-20 at 5 30 12 PM" src="https://github.com/llaske/sugarizer/assets/64434937/59921b84-a3c4-43ca-9846-0b2b7259904a">

**Comment by llaske** [comment]
Guess it's related to the fix https://github.com/llaske/sugarizer/issues/1403
I'm afraid that if we remove this line, the problem will happen again.
Any suggestion?

**Comment by VishnuVardhanBR** [comment]
I believe we can remove the line. I've checked the behaviour on multiple pages after its removal, and the button remains clickable with no issues.

**Comment by llaske** [comment]
No the `line-height` is need else there is shift on the cross (forced in blue below).

![image](https://github.com/llaske/sugarizer/assets/981841/a0e7115b-4e91-4e2e-a77e-f40356a6844a)

BTW, to fix the issue it's possible to set the color to `transparent`.

**Comment by VishnuVardhanBR** [comment]
Setting to transparent works, but when I try to reproduce what you have done above I receive the expected result? Why might this be?

![Screenshot](https://github.com/llaske/sugarizer/assets/64434937/51cc6331-a7e0-4a06-b508-54525200ce31)

![Screenshot](https://github.com/llaske/sugarizer/assets/64434937/655b3a5d-8735-4fea-8d35-fdf021968bd1)

**Comment by llaske** [comment]
> Setting to transparent works, but when I try to reproduce what you have done above I receive the expected result? Why might this be?

It seems that the alignment depend on resolution. Increase the zoom to change the alignment.

**Comment by VishnuVardhanBR** [comment]
I'm confused, It still works fine on lower resolutions, tried zooming in, reducing window size, manually setting resolution in dev tools. 

![Screenshot](https://github.com/llaske/sugarizer/assets/64434937/d1a9f7d0-9d81-467d-b970-991abb2d8ad6)

**Comment by llaske** [comment]
I mean related to physical screen resolution, changing screen size in Chrome has no effect.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1461
