### ISSUE TITLE
Calculator ln function

### ISSUE THREAD

**Issue by sahran99** [llaske/sugarizer#143]
When the ln function is clicked, log appears. Although the calculator still calculates the answer as if it were natural log, simply log means base 10, which can be confusing for the user. I believe this should be changed to say ln( when clicked. 
![image](https://user-images.githubusercontent.com/34138005/33780181-86d1da38-dc15-11e7-8b49-30c574a6b64e.png)

**Comment by llaske** [comment]
log (Math.log) is the name of function called. 
It has no sense to change it.
