### ISSUE TITLE
[Bug] : the calculate Activity is not responsive for 14 inch laptop 

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [llaske/sugarizer#1430]
The Calculate Activity is not responsive for the laptops screens of 14 inch .
![Screenshot (907)](https://github.com/llaske/sugarizer/assets/130988755/458bf49b-f393-4b22-9ea8-9577fef099e1)
As you can see in the image the number 0 and symbol . is not properly visible and also equals to is not visible 
@llaske plese check this issue and assign this to me

**Comment by llaske** [comment]
@Rohit-Sharmaa Sugarizer is not responsive on all resolution and screen size.
See https://github.com/llaske/sugarizer/issues/422 for a guide line.

**Comment by Rohit-Sharmaa** [comment]
@llaske  thank you for clarifying
