### ISSUE TITLE
Changing the Social Logos

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1438]
Logo Update for discord, Twitter and facebook

![image](https://github.com/llaske/sugarizer/assets/116670999/66f2a628-2f5d-4e5f-af26-24c4ecacd3c1)

**Comment by llaske** [comment]
First step here https://github.com/llaske/sugarizer-doc/pull/49

**Comment by samrudh3125** [comment]
how do you want the logos to be

**Comment by Vishalk91-4** [comment]
> how do you want the logos to be

I think the issue is resolved in sugarizer-doc

**Comment by llaske** [comment]
Yes it's fixed in https://github.com/llaske/sugarizer-doc/pull/54
