### ISSUE TITLE
Markdown issue

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#144]
In Markdown Activity.

When I type `#text` and it displays as h1.
Which according to markdown only converts into h1 when we type `# text`

I mean `#text` should have a space between `#` and `text`, right?

**Comment by llaske** [comment]
Space is not required according to [Markdown documentation](https://daringfireball.net/projects/markdown/syntax).

**Comment by satyamchaudharydev** [comment]
I don't know but you can look at Github for example. It does require space between `#` and `text`.

In github,

#not a header

# is a header

And the documentation you linked, though doesn't mention this specifically, but all it's example have space in them.

![screen shot 2017-12-12 at 5 51 12 am](https://user-images.githubusercontent.com/26341752/33860913-05fdb00a-df01-11e7-8c08-9a4b2067d44f.png)

and it makes sense because often we write #1234 as hashtag, issues and what not.

**Comment by llaske** [comment]
I've tested on few different tools: Atom, MacDown, ... All accept syntax without white space.
And the reference documentation mention "hash characters at the start of the line" no "hash characters at the start of the line followed by white space".
Can't do anything for Github.
