### ISSUE TITLE
Separate hover effect for icon and text in settings popup

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1441]
The icon and the text currently have separate hover animations. They should function as a unified element, with the hover effect applying to the entire list item as a whole.

![image](https://github.com/llaske/sugarizer/assets/64434937/099540e4-39dd-48db-9179-ea98899263aa)

**Comment by llaske** [comment]
Hmmm. Why not? BTW because there is a Vue.js rewrite in progress in branch https://github.com/llaske/sugarizer/tree/feature/v2, I think it has no sense to fix it in dev branch with the Enyo framework.

**Comment by VishnuVardhanBR** [comment]
Just an aesthetic enhancement, I was unaware of the rewrite branch, I'll look into it. Thanks!

**Comment by VishnuVardhanBR** [comment]
What do you think of this look @llaske ?

![Screenshot 2024-01-03 at 3 07 34 AM](https://github.com/llaske/sugarizer/assets/64434937/6a67f798-90bc-4c6b-857b-c2dde700b0bb)

**Comment by llaske** [comment]
Sounds good.

**Comment by hharshas** [comment]
@llaske I think this issue is resolved, we should close this.

**Comment by llaske** [comment]
@hharshas it's fixed on v2, not on 1.8.0. But yes it could be closed.
