### ISSUE TITLE
Calculate Activity Breaks in Mobile

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1442]
In the mobile version, I have found that We are unable to calculate the values, since the result gets displayed at the bottom, we cannot reach out at there for Android and 
We cannot reah the button to generate the answer for IOS

Android
![Screenshot_20231226-091824](https://github.com/llaske/sugarizer/assets/116670999/c973060f-6ddf-4ea2-bd3d-573cb11ffc78)

IOS
![image](https://github.com/llaske/sugarizer/assets/116670999/daf9a3a0-0f60-4a0b-9ca9-457360f7bc3f)

@llaske, what do you think of it

**Comment by llaske** [comment]
You're right thought Sugarizer is not adapted to smartphone as explained [here](https://github.com/llaske/sugarizer/issues/422#issuecomment-553519081).

**Comment by Vishalk91-4** [comment]
@llaske, i found that both on IOS, I Phone 14 pro max and on Android 
it is not working, e can't calculate the answer
IOS
![WhatsApp Image 2024-01-03 at 11 54 08](https://github.com/llaske/sugarizer/assets/116670999/a899d93a-e4e5-43f5-b00c-5abb9c1ee286)

@llaske, should I try to improve it

**Comment by Vishalk91-4** [comment]
> You're right thought Sugarizer is not adapted to smartphone as explained [here](https://github.com/llaske/sugarizer/issues/422#issuecomment-553519081).

**Comment by llaske** [comment]
@Vishalk91-4 you could try to improve it.

**Comment by llaske** [comment]
Close due to lack of activity
