### ISSUE TITLE
[Bug]: Invalid user name or images

### ISSUE THREAD

**Issue by samyakshah3008** [llaske/sugarizer#1443]
## Description: 

- While playing around with sugarizer web app, I initially created a new user with name `Samyak`. After that I opened a new tab where I did login with `Samyak` as username, now in the image selection I am getting below error: 

![image](https://github.com/llaske/sugarizer/assets/86982322/4f2f9ee7-3d94-4df7-a911-0bb734a2f961)

I am not sure why this bug is getting produced, secondly the error message is guiding something is incorrect but it is not showing me what can be the possible correct solution, like if images are incorrect then what are considered to be correct. 

## Steps to reproduce this bug: 

- Head over to https://try.sugarizer.org/ 
- Logout if you are already logged in
- Enter `Samyak` as username
- Select any images you want 

## Console errors: 

![image](https://github.com/llaske/sugarizer/assets/86982322/1cd73d7d-b615-43b2-b213-cf10d2064187)

## Expected behavior: 

- If a user is getting logged in, then why he/she is redirected to selected images? Shouldn't we be redirecting him/her straight away to  main page?

**Comment by llaske** [comment]
The message just mean that your image (i.e. password) doesn't match the one recorded for your user.

**Comment by samyakshah3008** [comment]
Okay got it, thank you for answering. Not sure how I missed on this :P 
Follow up thought -- can we consider to rename it to password or something or add help text? what's your take on this? @llaske ?

**Comment by llaske** [comment]
It seems obvious and it's mentioned in the help message.
Plus it's explained by teachers to children when they launch Sugarizer the first time.
At worse an admin can reinitialize the password.

**Comment by samyakshah3008** [comment]
> It seems obvious and it's mentioned in the help message. Plus it's explained by teachers to children when they launch Sugarizer the first time. At worse an admin can reinitialize the password.

Ahh, got it @llaske 
Cheers, closing this issue.
