### ISSUE TITLE
Grid paint activity issue.

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#145]
When I right click on screen it doesn't emulate right click instead it just works like if I clicked on it or something which doesn't feel right.

**Comment by llaske** [comment]
Right click is not a good practice, specifically because Sugarizer could be use on touch screen.
What you expect to do with a right click?

**Comment by satyamchaudharydev** [comment]
Sorry, I couldn't able to put my point across last time but I'd still argue this, in fact, is a bug. When I right click on any page, I except my chrome (or other browsers) native dialog to be open.

Like this:
![screen shot 2017-12-12 at 5 44 56 am](https://user-images.githubusercontent.com/26341752/33860602-a5b835a4-deff-11e7-883a-084353341ac9.png)

If it doesn't emulate this native dialog on right click and just works like a normal click, is , in fact, a bug.

You are right, right click is not a good practice for the app. That is why this is a bug.

**Comment by llaske** [comment]
No you're wrong, the good practice is to not count on right click.
So considering right click like left click is not a bug.

**Comment by satyamchaudharydev** [comment]
Maybe you right, but still, might want to inspect page or translate the page or something like that by clicking right. I just can't imagine why emulating click would be good practice.

**Comment by bzg** [comment]
Is this discussion for GridPaint or for any Sugarizer activity?

I tested right-click on the Markdown activity through dev.sugarizer.org and I get the usual context window from Firefox 57.  Which makes sense here: it is useful to be able to copy and paste text in a text application, whether I use it on a smartphone or on the web.

If the discussion is general, perhaps who should have it activity by activity instead?

I agree that with @satyamchaudharydev that always considering right-clicking as left-clicking in all activities would be confusing.

**Comment by llaske** [comment]
Left click and Right click events in JavaScript are handle in the same way: by [onmouse events](https://www.w3schools.com/jsref/dom_obj_event.asp). It doesn't do distinction between left/right click. I don't find pertinent to specialize the source code to do a differentiation because the right click is a legacy feature: most systems tend to totally remove it (written from a MacBook without right button).

Regarding Markdown activities - or other activities with input/text fields - the right click event is handle by the browser, not into the activity.

**Comment by bzg** [comment]
> Regarding Markdown activities - or other activities with input/text fields - the right click event is handle by the browser, not into the activity.

Okay, then it's fine for those activities. 

But just to be sure I understand: in other activities, what does the right-click event? Is it ignored? Considered as a left-click event? My expectactions would be that the right-click event consistently triggers the usual browser context menu.

**Comment by llaske** [comment]
Other activities (Paint, Maze, Physics, ...) process mouse click in the same way because as I said it depends of JavaScript. So for all activities right click = left click.
So yes, it's consistent but not necessarily in the way you expect :-)
