### ISSUE TITLE
Addition to Planet Info

### ISSUE THREAD

**Issue by HitanshuPrasad** [llaske/sugarizer#1451]
This  issue is to add more planet info to Planets activity.

Information to be added:
1. Length of Day
2. Surface Gravity

**Comment by HitanshuPrasad** [comment]
Working on this.

**Comment by AdityaKrSingh26** [comment]
Hey  @llaske  is this enhancement still available to work upon ?

**Comment by llaske** [comment]
@AdityaKrSingh26 no, it's not pertinent.

**Comment by AdityaKrSingh26** [comment]
> @AdityaKrSingh26 no, it's not pertinent.

okay
