### ISSUE TITLE
Bug in Achievements in Curriculum Section

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1454]
The skills section can be unlocked, just by clicking on them, even without uploading any media, and there it accepts as skill achievement on posting any media, unrelated to task

https://github.com/llaske/sugarizer/assets/116670999/834dcbea-0ff0-486c-b169-fac703e504b2

![Screenshot 2024-01-03 101520](https://github.com/llaske/sugarizer/assets/116670999/9a7488cd-8419-4fa7-8350-2116d2519483)

**Comment by llaske** [comment]
@Vishalk91-4 yes skill achievement is declarative. There is no need to upload a proof.

**Comment by Vishalk91-4** [comment]
> @Vishalk91-4 yes skill achievement is declarative. There is no need to upload a proof.

Thanks, I got confused there, since it is written, integrate proof, now I get the point of having it
