### ISSUE TITLE
Allow clicking on Abacus balls to move it

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#146]
For now, we have to drag balls which is requires bit effort and is error-prone.

It would be great if we can move balls by just clicking on them and it would also be better for mobile and touch users.

**Comment by ag1709** [comment]
I am interested in working on this. Is anyone already working on it?

**Comment by llaske** [comment]
Cool. Let's go.

**Comment by ag1709** [comment]
Which file in particular is to be modified?

**Comment by llaske** [comment]
Guess it should be in https://github.com/llaske/sugarizer/blob/master/activities/Abacus.activity/js/abacusbead.js#L88
Try to debug to understand how it works.

**Comment by utkarsh-raj** [comment]
https://github.com/llaske/sugarizer/pull/181#issuecomment-370563571

The changes proposed by @llaske are intuitive, more than the current behaviour. I would carry the work forward by @aditigupta17 to incorporate the proposed behaviour. Any ideas for still better behaviour ? (Since the issue has been open for quite a long time)

**Comment by llaske** [comment]
Like I said, we could propose an automatic move on click/tap when there is no doubt about the direction expected and let the drag gesture - since double-tap is not intuitive - when it's not possible to do the deduction. It should be tested.

**Comment by utkarsh-raj** [comment]
https://github.com/llaske/sugarizer/pull/277#issue-255474687
I have opened a PR with some changes. Can you look and see if it feels intuitive @llaske ?

**Comment by llaske** [comment]
Fixed by https://github.com/llaske/sugarizer/issues/146

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
