### ISSUE TITLE
Exerciser Activity MCQ Choice Color Issue

### ISSUE THREAD

**Issue by HitanshuPrasad** [llaske/sugarizer#1469]
When playing Exerciser Activity, when a MCQ  option is chosen , Its Background color changes to Color that makes it difficult to view the option. 

https://github.com/llaske/sugarizer/assets/96762115/1c028a43-8e45-4225-8c02-52c0ddbe3c9c

**Comment by HitanshuPrasad** [comment]
Working on it.

**Comment by llaske** [comment]
Please do not send a PR before the issue has been approved.
There is a dedicated repo for Exerciser https://github.com/llaske/ExerciserReact
