### ISSUE TITLE
Sugar activity scroll view in phone in Portrait mode

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#148]
![whatsapp image 2017-12-12 at 5 49 06 pm](https://user-images.githubusercontent.com/26341752/33884345-4ad0e3d2-df65-11e7-97e3-2871e3240997.jpeg)

Whenever I try to scroll this view from bottom to top in the phone. It always messes up with chrome native scrollbar, in turn making scrolling very hard. I think this is because of custom scroller in sugar (can anyone confirm this?).

and also clicking on labe should open their corresponding activity, IMO.

**Comment by llaske** [comment]
On smartphone, Sugarizer should be used via the dedicated Android/iOS app.
