### ISSUE TITLE
Menu button is overflowing on mobile in Portrait mode

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#149]
![whatsapp image 2017-12-12 at 5 49 06 pm 1](https://user-images.githubusercontent.com/26341752/33884506-f98ee1da-df65-11e7-82c8-08e1be8bc1d2.jpeg)

The menu button is overflowing.

**Comment by llaske** [comment]
On smartphone, Sugarizer should be used via the dedicated Android/iOS app.
