### ISSUE TITLE
Pause button for BlockRain activity

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1499]
There is currently no pause button in the BlockRain activity. Would be nice addition, thoughts? @llaske 

![Screenshot](https://github.com/llaske/sugarizer/assets/64434937/5e6a5a39-6211-4ce6-ba46-75164d18ba82)

**Comment by llaske** [comment]
Why not but to be consistent with other activities, it should be a button in the toolbar

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1501
