### ISSUE TITLE
Many buttons are overflowing on mobile in Portrait mode

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#150]
![whatsapp image 2017-12-12 at 5 49 06 pm 2](https://user-images.githubusercontent.com/26341752/33884539-1c1b493c-df66-11e7-8fa1-285146c32a8a.jpeg)
Many buttons are overflowing.

**Comment by llaske** [comment]
On smartphone, Sugarizer should be used via the dedicated Android/iOS app.
