### ISSUE TITLE
Pause button not shown when paused in Gears Activity

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1503]
The play button does not change to a pause button when paused in Gears Activity

![gears](https://github.com/llaske/sugarizer/assets/64434937/917d219a-c5a5-4bda-8b4c-1903b521dec9)

**Comment by llaske** [comment]
You're right, it will be better.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1506
