### ISSUE TITLE
Misaligned button in Speak activity

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1504]
The button in the chat box is misaligned

![Screenshot](https://github.com/llaske/sugarizer/assets/64434937/529cc8e1-f70f-464d-8bd7-4da4b6e51fce)

**Comment by llaske** [comment]
It seems that it depends of the screen resolution but it could be better.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1505
