### ISSUE TITLE
Time fluctuations in Clock Activity

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1507]
https://github.com/llaske/sugarizer/assets/116670999/ccbf0683-7e75-4669-80b8-7ac40efc4a36

In Clock Activity, the time gets changed from 24 hr one to 12 hr clock, in this case from 18 to 6 continously

@llaske, what's your thought on this

**Comment by llaske** [comment]
continuously? It seems that it appears only when switching display time mode. Right?

**Comment by Vishalk91-4** [comment]
> continuously? It seems that it appears only when switching display time mode. Right?

Yes, I meant that, whenever we click the button on the first

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1529
