### ISSUE TITLE
Tooltips not localized in Reflection activity

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1508]
Tooltips are not localized after migration to i18next.

![Screenshot](https://github.com/llaske/sugarizer/assets/64434937/5e8b660f-c20c-4e40-8f7c-e81eec019840)

Language was set to spanish in the above picture

**Comment by llaske** [comment]
You're right.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1509
