### ISSUE TITLE
JavaScript error in Gear when removing an item

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#151]
![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/26341752/33916736-49343f68-dfd0-11e7-8dec-407fc57b95b5.gif)

I don't if that is intended or a bug?
Also console has following error.

```
Uncaught TypeError: Cannot read property 'gears' of null
    at Function.Board.fromObject (gearsketch_model.js:1427)
    at onLoaded (activity.js:33)
    at DatastoreObject.loadAsText (sugarizer.js:131)
    at activity.js:40
    at Object.execCb (require.js:1604)
    at Module.check (require.js:844)
    at Module.<anonymous> (require.js:1084)
    at require.js:129
    at require.js:1127
    at each (require.js:57)
```

**Comment by llaske** [comment]
It's intended : it's a way to remove an item from the board but the JavaScript error is not intended.
BTW I'm not able to reproduce it: could you retry and tell us exactly when this error appear.

**Comment by llaske** [comment]
I've tested in Chrome and on High Sierra too but can't reproduce the error.
Could try with a new instance of Gears ("Start New" from the activity menu) and see if it happen again?

**Comment by llaske** [comment]
Unable to reproduce the issue.

**Comment by satyamchaudharydev** [comment]
You can give this task to GCI so other developers can also solve that.
