### ISSUE TITLE
Calligra Activity does not support resize

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1510]
https://github.com/llaske/sugarizer/assets/116670999/520e75bc-1a42-4755-ac0c-352f1360ad45

@llaske

On Capitalizing the words, the area to draw doesn't resize, it remains the same and the proceeds to draw in blank space

**Comment by llaske** [comment]
It's not a problem of resizing, it's just that the drawing zone has a limited size.
Reducing the zone is not a solution because letters should be enough big to be drawn with the finger.
