### ISSUE TITLE
Fraction Bounce Activity, trick to cheat the score

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1511]
@llaske 

When the pause button is clicked, the bounce doesn't get counted, so the no. of times it get's played increases to more than 10

https://github.com/llaske/sugarizer/assets/116670999/28af82f6-9752-4427-9107-1ddd44b81f2b

**Comment by llaske** [comment]
Hmmm it's seems to appear only when you click the pause button exactly just before the bounce.
Right?

**Comment by Vishalk91-4** [comment]
> Hmmm it's seems to appear only when you click the pause button exactly just before the bounce. Right?

yes, little before + after

**Comment by hackorlyf** [comment]
@llaske can I contribute in fixing this or is it already fixed?

**Comment by Vishalk91-4** [comment]
> @llaske can I contribute in fixing this or is it already fixed?

It's already fixed
