### ISSUE TITLE
[v2] password.js Component Issues

### ISSUE THREAD

**Issue by UtkarshSiddhpura** [llaske/sugarizer#1515]
### Issues found
1. **Long pressing keys doesn't work**: we could ignore other keys but being not able to long-press `backspace` could be annoying to users.
2. **Ctrl keys combination**: e.g `ctrl+a`, `ctrl+backspace`.

### Possible Fixes
1. Handle all long presses or only backspace key.
2. Remove text highlights of input selection. Handle `ctrl+backspace` by checking `e.target.value === ""`.

**Comment by Vishalk91-4** [comment]
@UtkarshSiddhpura, @llaske, another thing I've found is that if I press any key let's say `a`, then the letter get's displayed till it's pressed, then the emoji is displayed only once

**Comment by Vishalk91-4** [comment]
I'm fixing this issue now, will raise the PR

**Comment by UtkarshSiddhpura** [comment]
> @UtkarshSiddhpura, @llaske, another thing I've found is that if I press any key let's say `a`, then the letter get's displayed till it's pressed, then the emoji is displayed only once

Yes that's already mentioned long pressing keys.

**Comment by llaske** [comment]
1. I don't think supporting long press key is a good idea. It could be difficult to understand for young children. But you're right long press on backspace key should work.
2. Ctrl keys could be ignored (it's not supported in v1). It's not intuitive for children. BTW the current behavior is weird on Ctrl+a and should be fixed.

**Comment by llaske** [comment]
Close by https://github.com/llaske/sugarizer/pull/1519 and https://github.com/llaske/sugarizer/pull/1527
