### ISSUE TITLE
[v2] Remove user from history on delete account

### ISSUE THREAD

**Issue by UtkarshSiddhpura** [llaske/sugarizer#1516]
## Issue:
By deleting user-account from privacy settings (Delete server account), the user is not removed from local storage. Hence visible on firstscreen.

## Fix:
use `removeUser` method of sugarizer history module to remove user from local storage.

**Comment by llaske** [comment]
Yes you're right. It's removed in v1.

**Comment by AdityaKrSingh26** [comment]
Hey , i would like to work on this issue .... could you please assign me

**Comment by UtkarshSiddhpura** [comment]
> Hey , i would like to work on this issue .... could you please assign me 

We don't assign issues, you can send a PR which is referencing the issue ID (e.g fixes #id)

**Comment by AdityaKrSingh26** [comment]
okay

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1517
