### ISSUE TITLE
Dropdown looks weird when lot of items inside

### ISSUE THREAD

**Issue by satyamchaudharydev** [llaske/sugarizer#152]
![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/26341752/33917135-802fbdc4-dfd2-11e7-8645-466dd4e0134a.gif)

Dropdown looks weird.

**Comment by RosaGeorge31** [comment]
I would like to work on this. Is anyone already working on it?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/c0105ca5d9a6539618d755f2578ae19e4e11935c

**Comment by llaske** [comment]
Released in https://github.com/llaske/sugarizer/releases/tag/v1.0
