### ISSUE TITLE
Too fast player in Maze Web activity

### ISSUE THREAD

**Issue by hackorlyf** [llaske/sugarizer#1534]
@llaske Isn't the movement of player too fast for kids to even notice or comprehend paths the player took?

https://github.com/llaske/sugarizer/assets/130314506/0daf2212-cfd8-4f1d-b57b-c04ea3093b79

**Comment by hackorlyf** [comment]
@llaske I can work around with tween operation and create a delay (not of much, just half a second or a second), anything that'll give more time for kids to observe and think about the path while also keeping it such that it doesn't become too slow or boring.

**Comment by llaske** [comment]
The idea of the game play is to minimize the number of click. So while there is no option, the pawn move alone until the next branch.
It could appear to be too fast but it's not so fast when the level increase and number of path is more important.
So I don't think we need to add a delay.

**Comment by hackorlyf** [comment]
Understood, thanks.
