### ISSUE TITLE
Text Box cannot handle resize and excess characters in Shared Activity

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1537]
@llaske 

In Shared Activity, I have found that, when a word consisting of lot of characters is typed 
And if we try to write a lot of words, it doesn't get fit nicely, 

The Box Overflows in Both the cases

https://github.com/llaske/sugarizer/assets/116670999/8b8641f4-28c5-477f-8a04-f2d8dcdb3fe4

**Comment by llaske** [comment]
I know this bug, duplicate https://github.com/llaske/sugarizer/issues/333
I'm not sure it's a good idea to take risk to fix it since it's not an usual use case.

**Comment by Vishalk91-4** [comment]
> I know this bug, duplicate #333 I'm not sure it's a good idea to take risk to fix it since it's not an usual use case.

The one issue you mentioned, I guess that is something which could occur less, but I guess the one where it overflows the box, that is something I guess could be worked upon

**Comment by llaske** [comment]
I don't want to take risk of loosing iOS compatibility to fix an issue in an unusual use case.

**Comment by Vishalk91-4** [comment]
> I don't want to take risk of loosing iOS compatibility to fix an issue in an unusual use case.

Yes, that shouldn't be lost at all times
Children are obviously less likely to perform things like this
