### ISSUE TITLE
Chat Prototype works, but the connection between me and the neighborhood is slow

### ISSUE THREAD

**Issue by ZhanieyaP** [llaske/sugarizer#154]
![screenshot 3](https://user-images.githubusercontent.com/33292904/33955354-3c78e2cc-e009-11e7-936f-41f00701851d.png)

    

The Chat Prototype works, but the neighborhood that I'm responding takes them forever to respond back to my response. A way they can reproduce this issue is to get the neighborhood I'm having a conversation with in a quicker and faster connection so we can have ongoing conversations.

**Comment by llaske** [comment]
Of course the response speed depend of the connection speed.
It's why for school with a slow internet connection (or no internet connection), it's possible to deploy a Sugarizer Server on the local network.
