### ISSUE TITLE
The Text-box disappears when zooming out beyond a certain level, and it does not reappear when zooming back in.

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1542]
@llaske 
The text box disappears when zooming out beyond a certain level, and it does not reappear when zooming back in.
**Activity-LabyrinthJS** 

https://github.com/llaske/sugarizer/assets/154233802/0c978578-3668-408b-81bf-42928d6e27ea

**Comment by llaske** [comment]
Not sure to understand how you are zooming. Guess you're not using the zoom in the toolbar.

**Comment by d1vyanshu-kumar** [comment]
@llaske I’ve noticed that when I zoom out using my PC touchpad, after a certain point, the text-box is disappears. I believe we should set a limit so that zooming out beyond that point is restricted

**Comment by llaske** [comment]
Not sure what sort of zoom it is since it zooms the drawing zone but not the toolbar.
On my side everything zoom uniformly and nothing disappears.
 
![a2fMlWdoHL](https://github.com/llaske/sugarizer/assets/981841/22ccb409-78f1-438a-9255-dfc3fe2a41c1)

**Comment by d1vyanshu-kumar** [comment]
@llaske yes you are right got it. Thanks for the review. can you please check this issue?
https://github.com/llaske/sugarizer/issues/1543
