### ISSUE TITLE
To enhance user experience, implementing a sliding bar that allows users to review their initial input / Auto resize Text Area.

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1543]
@llaske 

To enhance user experience, I want to implement a sliding bar that allows users to review their initial input. This feature would enable users to scroll back and forth through their written content, ensuring accuracy and clarity.

https://github.com/llaske/sugarizer/assets/154233802/47da4dc4-cec7-4a73-9b8c-f366010fd0d2

**Comment by llaske** [comment]
The activity is for children who are not supposed to do long sentences in a mind map.
Plus a simple workaround is to reduce the font size.
