### ISSUE TITLE
right Text-Box is not movable or not fill the empty space cause by left one.

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1544]
https://github.com/llaske/sugarizer/assets/154233802/1ca80037-9bdd-42be-835f-20f6da8f28eb

@llaske when the size of the left text box is reduced the space is not filled by the right box. we can make the right box movable/resizable. This way, users can adjust the proportions as needed.

**Comment by d1vyanshu-kumar** [comment]
@llaske I also see that the left text box overlaps with the right one. can I start working on this issue?

https://github.com/llaske/sugarizer/assets/154233802/c535dcb1-eac0-453b-9e30-93c174c1e703

**Comment by d1vyanshu-kumar** [comment]
@llaske if this issue looks genuine then can I work on this?

**Comment by llaske** [comment]
Markdown is deprecated - replaced by Write. It has no interest to invest more on it.
