### ISSUE TITLE
FotoToon enhancements

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1545]
- Undeletable text when trying to delete while editing in FotoToon
![gif1](https://github.com/llaske/sugarizer/assets/64434937/af9b2b16-2ed2-41a6-8141-9537326800da)

- It would be nice to be able to dismiss the edit by clicking outside of the box? As it is natural in modern UI's.

- Size adjustability for images

- Ability to add a blank/white page

- Images go under other images sometimes when dragging
![gif2](https://github.com/llaske/sugarizer/assets/64434937/95f94973-f3d1-4cc1-a705-f8b476365b87)

**Comment by llaske** [comment]
I'm agree for these enhancements except for the "Add blank page", I don't see the interest here.
Will be better to split this issue in different issues.
