### ISSUE TITLE
[v2] Language Settings: En cannot be selected

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1546]
@llaske
In v2, the language en, present as popup-title cannot be selected on changing the language

https://github.com/llaske/sugarizer/assets/116670999/c36a1d4b-4474-4900-9293-8992c4d94e15

**Comment by llaske** [comment]
You're right.

**Comment by d1vyanshu-kumar** [comment]
@Vishalk91-4 I am interested in solving this issue, can I work on this issue?

**Comment by llaske** [comment]
> @Vishalk91-4 I am interested in solving this issue, can I work on this issue?

No need to ask. Feel free to send a PR to a fix, see https://github.com/llaske/sugarizer/blob/dev/CONTRIBUTING.md

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1548
