### ISSUE TITLE
Dismissal of text box in Fototoon

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1550]
It would be nice to be able to dismiss the edit by clicking outside of the box? As it is natural in modern UI's.
![Screenshot 2024-03-09 at 2 15 50 AM](https://github.com/llaske/sugarizer/assets/64434937/1b7d7054-ecde-46af-9f8d-0f9f413b875c)
Currently you have to click on the Icon again to close.

**Comment by ManasMadan** [comment]
@llaske Can i work on this ?

**Comment by llaske** [comment]
@ManasMadan, sure. No need to ask as mentioned here https://github.com/llaske/sugarizer/blob/dev/CONTRIBUTING.md

**Comment by llaske** [comment]
It's the standard behavior of Sugar UI.

**Comment by VishnuVardhanBR** [comment]
The issue has been solved. Unnecessary now.
