### ISSUE TITLE
In Tank Operation the defeat music persists even after returning to a previous screen.

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1553]
Restart Button: Adding a “Restart” button directly on the game over the screen would be convenient for players. This way, they won’t need to navigate back and then click the start button. It streamlines the process and makes restarting quicker.

The defeat music continues even after returning to the previous screen.
@llaske does this issue look good?  can I start working on this?

Activity name: Tank-operation.

https://github.com/llaske/sugarizer/assets/154233802/a6bc0588-00f1-4e81-b7ae-0a74f1883536

**Comment by llaske** [comment]
> Restart Button: Adding a “Restart” button directly on the game over the screen would be convenient for players. 

I'm not in favor of changing the game play.

> The defeat music continues even after returning to the previous screen.

You're right, it's a bug.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1556
