### ISSUE TITLE
One  Block is missing in a  5 * 5  grid

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1554]
@llaske 

https://github.com/llaske/sugarizer/assets/154233802/f0fc630e-042c-4a83-8f65-a834131c224e

**Comment by d1vyanshu-kumar** [comment]
@llaske If this issue appears satisfactory, may I proceed with working on it?

**Comment by d1vyanshu-kumar** [comment]
<img width="641" alt="Screenshot 2024-03-10 at 1 20 53 AM" src="https://github.com/llaske/sugarizer/assets/154233802/e62ff661-2a14-46dd-acb3-de01ba54a0a7">

in 6 * 6 grid 4 box where is missing.

**Comment by llaske** [comment]
Because it's a memory game where items are paired, the number of items should be even.
So the current behavior is the one expected.
