### ISSUE TITLE
After pausing the tutorial and resuming it, it restarts from the beginning instead of continuing from the section where we left off.

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1557]
In the activity named “Abecedarium.activity”, when we pause the tutorial and then resume it, it restarts from the beginning instead of continuing from the section where you left off. It would be more convenient if it could pick up from where we stopped.

@llaske please review this issue if this issue looks genuine then I would like to work on this issue.

https://github.com/llaske/sugarizer/assets/154233802/f8b474e1-95f3-4ed5-8f0f-72e6a4242f57

**Comment by llaske** [comment]
It's not a tutorial, it's just a button to play each item in sequence.
So, the button is more a stop than a pause.

**Comment by llaske** [comment]
> We should replace it with a stop icon rather than pause. what are your thoughts on this?

It's not needed.
