### ISSUE TITLE
After a certain time the undo button becomes disable.

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1559]
@llaske ,

In the Paint activity, the undo button becomes disabled after some time. Additionally, there is no shortcut key available for undo and redo actions. Could you please investigate this issue? If it appears to be a genuine problem, I would like to work on resolving it.

Thank you!

https://github.com/llaske/sugarizer/assets/154233802/bfa047ac-ee81-419c-ae63-9bec6b77a195

**Comment by llaske** [comment]
Yes the undo is limited for memory reason.
Short cuts is useless because it's too complex for children and most of the time Sugarizer is use on tablets.
