### ISSUE TITLE
Blockrain ~ Game can start before pressing play button 

### ISSUE THREAD

**Issue by hharshas** [llaske/sugarizer#1563]
If pressed any keys or clicked any buttons, game starts automatically and also shows "game over" at the end, even when play button is on the top from starting.
Also down arrow button don't help much as we have click multiple times unlike down arrow key. So when button clicked down it should work the same.

**Comment by llaske** [comment]
You're right.
It's not a problem to let the user start playing the game just by keys/click but the Play button should disappear and the toolbar button state should be changed.

**Comment by hharshas** [comment]
Hmm, Disappearing play button will be more user friendly approach.

**Comment by llaske** [comment]
Yes the idea is to allow to start the game by clicking the Play button or by pressing a key.
In both case the Play button should disappear.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1566
