### ISSUE TITLE
In the title box, the text overflows the container. We need to either set a character limit or incorporate a slider within the box

### ISSUE THREAD

**Issue by d1vyanshu-kumar** [llaske/sugarizer#1565]
@llaske 
In the Fototoon activity, the title text exceeds the container boundaries. We should consider implementing either a character limit or a slider within the box.
please review this issue if it looks genuine then I would like to work on this issue:

https://github.com/llaske/sugarizer/assets/154233802/d944de4b-6304-4012-926a-3521cd6f8376

**Comment by llaske** [comment]
No. The user can easily change the font size to adapt to the right.
It's with this sort of thing that children learn to fix bugs.
