### ISSUE TITLE
Update WebL10n to i18next in tutorials

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1571]
WebL10n is still used in the tutorials for the Pawn activity. Should it be updated?

**Comment by llaske** [comment]
Yes the Vanilla tutorial need to be updated : https://github.com/llaske/sugarizer/blob/dev/docs/tutorial/VanillaJS/step5.md
The Vue.js one is okay.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1575
