### ISSUE TITLE
Set stricter zoom limits to 'Color my world'.

### ISSUE THREAD

**Issue by DarkFalc0n** [llaske/sugarizer#1572]
Currently there seem to be zoom (in/out) limits set, however, they allow too much zoom activity. Zooming out too much causes the world map to appear tiled, and hence have repeating elements which may be misleading. Maybe some checks could be implemented or tiling could be disabled in the map.

**Comment by llaske** [comment]
Zoom gesture is not so easy for children so there is few risk that they zoom too much.
At worse it's the type of experience that learn the notion of bugs.
