### ISSUE TITLE
Moon Activity: fix css in chrome mobile version

### ISSUE THREAD

**Issue by Swadhin2001** [llaske/sugarizer#1576]
The user interface (UI) of MoonActivity on the Chrome mobile version needs improvement. 

Image:
<img width="1703" alt="Screenshot 2024-03-28 at 8 08 57 PM" src="https://github.com/llaske/sugarizer/assets/95471286/5d0761c6-c5b3-4e10-9006-188b5ea6e911">

**Comment by llaske** [comment]
No, it's not a real use case. See https://github.com/llaske/sugarizer/issues/422
Avoid sending a PR without having validation on the issue.

**Comment by Swadhin2001** [comment]
Thank you for the clarification.
