### ISSUE TITLE
The Record Activity doesn't work in the HTTP version of Sugarizer

### ISSUE THREAD

**Issue by aryan-02** [llaske/sugarizer#159]
When you open sugarizer from the "Try Now" button on http://sugarizer.org/ , it links to http://try.sugarizer.org/ . In the HTTP version, the Record activity doesn't work (since Google Chrome considers it unsafe, it directly blocks access to the computer's microphone and camera).
However, it works perfecty in the HTTPS version at https://sugarizer.org/ , since in the media is being transferred with a Secure Socket Layer.
Here's how I think this can be fixed.
Make the "Try Now" button link to https://sugarizer.org/ .

**Comment by llaske** [comment]
Yes, you're right.
It's why the dev branch now support HTTPS.
Could be tested on https://dev.sugarizer.org and will be integrated in v1.0.

**Comment by llaske** [comment]
Released in https://github.com/llaske/sugarizer/releases/tag/v1.0
