### ISSUE TITLE
Ability to increase the downward speed of the ball in the Fraction Bounce Activity

### ISSUE THREAD

**Issue by SamarthBagga** [llaske/sugarizer#1591]
Sometimes in this actvity the user may bring the ball to the correct position but has to wait for the ball to take its time to bounce. This functionality will address this issue. It will look something like this -

[318216024-f7362c6a-6615-4ed5-8f48-3fed9dd0cd64.webm](https://github.com/llaske/sugarizer/assets/69239707/e14b5b90-252f-4898-b521-f310c535413b)

**Comment by SamarthBagga** [comment]
I have linked a draft PR to show how this feature will look like.

**Comment by llaske** [comment]
I don't think it's useful since the board is small.
Plus Sugarizer is mostly use on tablets so arrow key is useless.
