### ISSUE TITLE
[v2] Password section - Empty Password Works

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer#1594]
In the Password section in V2 even with empty password it allows the clicking to next and with enter key,
It should be restricted

https://github.com/llaske/sugarizer/assets/116670999/8ca78835-94c4-4477-8a34-424c99725ded

**Comment by llaske** [comment]
:open_mouth: Well done!
The minimal size should even be checked: https://github.com/llaske/sugarizer/blob/dev/js/firstscreen.js#L183

**Comment by Vishalk91-4** [comment]
> 😮 Well done! The minimal size should even be checked: https://github.com/llaske/sugarizer/blob/dev/js/firstscreen.js#L183

Yes, I was thinking of adding that, even if it wasn't mentioned
The minimal size should be kept to 4 right

**Comment by llaske** [comment]
> The minimal size should be kept to 4 right

Yes this is the default minimal size but the server keep the control on the real minimum.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1599
