### ISSUE TITLE
Fotoon globe also get deleted with the deletion of image

### ISSUE THREAD

**Issue by hharshas** [llaske/sugarizer#1597]
![fototoonissue](https://github.com/llaske/sugarizer/assets/125907752/a33e9a52-eb4b-47bb-b9ba-069dab2a54d3)
The globe added earlier behaved correctly, the issue only persists with the globe added after inserting an image. @llaske

**Comment by llaske** [comment]
Not sure to understand where is the issue.

**Comment by hharshas** [comment]
@llaske When I insert an image and then add a globe, deleting the image also deletes all the globes added after it. However, the globe added before inserting the image remains staged. To clarify, in the above gif, when I press the delete button for the image, the globe added after that image also gets deleted.

**Comment by llaske** [comment]
Yes but one page is one image. It has no sense to have a globe without an image.
So it's the expected behavior.

**Comment by hharshas** [comment]
My mistake, I didn't consider that inserting a new image creates a new page. The globe will have no context without that page. I am closing the issue.
