### ISSUE TITLE
DOM-based XSS vulnerability in the Get Things Done Activity

### ISSUE THREAD

**Issue by aryan-02** [llaske/sugarizer#160]
If you type HTML/CSS/JavaScript code as a to-do list item, it runs perfectly and can even be used to modify elements of the UI.
Here's how to replicate:
Open the "Get Things Done" Activity
Copy and paste the following as an item in the To-Do list, and enjoy watching the UI get ruined:
```
<style>*{background:red!important;border: 5px solid green!important; transition: all 0.5s; }*:hover{transform: scale(1.01)translateX(5px)}</style> <button style="color:white!important;background:black!important;" onclick="alert('Hello World')">Click Me!</button>
```

Here's how I think this can be fixed:
When enter is pressed, use JavaScript to generate an iframe whose contents will be the text (or code) entered in the textarea. This will make sure the styles are applied only to what's there inside the box and not what's in the rest of the UI.
This should help in the implementation:
https://www.tutorialrepublic.com/faq/how-to-insert-html-content-into-an-iframe-using-jquery.php
https://www.tutorialrepublic.com/codelab.php?topic=faq&file=jquery-inject-html-into-an-iframe-from-the-textarea

**Comment by llaske** [comment]
Nice.

**Comment by Survivor75** [comment]
The XSS attack can be handled by replacing any text ,that appears to be code(HTML/CSS/JavaScript)
by replacing it with an empty string.

**Comment by llaske** [comment]
Code of Get Things Done activity is located https://github.com/llaske/sugarizer/tree/dev/activities/GetThingsDone.activity

**Comment by aryan-02** [comment]
@Nepaltechguy2 I suppose yes.

**Comment by aryan-02** [comment]
Closing the issue, since it's fixed.
