### ISSUE TITLE
Multiple loading notifications

### ISSUE THREAD

**Issue by VishnuVardhanBR** [llaske/sugarizer#1606]
Multiple notifications even when all the list items have been loaded. 

https://github.com/llaske/sugarizer/assets/64434937/78ee7008-4fe4-4722-852d-7e5359fa1d43

**Comment by llaske** [comment]
It's related to lazy loading of items.
Each scroll launch a load of a set of 10 items.
We can't consider it's a bug or even a problem for users.

**Comment by VishnuVardhanBR** [comment]
Understood.
