### ISSUE TITLE
Activity Idea : Minesweeper

### ISSUE THREAD

**Issue by kunal-mohta** [llaske/sugarizer#162]
Since it is not available on the newer Windows versions, I think this could be good activity to be included.

**Comment by llaske** [comment]
Why not. Should be compatible however with a touch interface so not a too small grid.

**Comment by kunal-mohta** [comment]
Okay. I'll get to work then.

**Comment by cosmicAsymmetry** [comment]
Hey @kunal-mohta! Are you still working on this?

**Comment by kunal-mohta** [comment]
@cosmicAsymmetry Yes.
See #164 in Pull Requests.

**Comment by llaske** [comment]
Finally not pertinent to include in Sugarizer.
