### ISSUE TITLE
Paint activity not working

### ISSUE THREAD

**Issue by kunal-mohta** [llaske/sugarizer#163]
Unable to perform any action after starting Paint activity (not even able to exit the activity).
Console shows this error.

![screenshot 2017-12-27 18 27 46](https://user-images.githubusercontent.com/30414954/34382288-d67c8376-eb33-11e7-96dd-e20abe79e03f.png)

**Comment by llaske** [comment]
Unable to reproduce. Could you tell more about your environment.

**Comment by kunal-mohta** [comment]
Operating System - Ubuntu 15.10
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by llaske** [comment]
Sorry unable to reproduce. Could you start a new instance "Start new" in activity menu, and try to reproduce it.

**Comment by kunal-mohta** [comment]
Got it working.
Thanks for helping.
