### ISSUE TITLE
[v2] Listview lines spacing/padding is wrong

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#1650]
The list view in v2 has wrong spacing/padding compared to v1.
Specifically: the favorite icon is too close to left size, lines are not centered vertically, ...

![lqQPiAq658](https://github.com/user-attachments/assets/b5389dcb-e45e-47b0-9a34-a50bf0f96daf)

**Comment by MdSaifAliMolla** [comment]
@llaske fixed it. #1653

**Comment by UtkarshSiddhpura** [comment]
@llaske @MdSaifAliMolla The change in listview is made in v1 not v2, To make changes in v2 listview see https://github.com/llaske/sugarizer/blob/feature/v2/js/listview.js

**Comment by MdSaifAliMolla** [comment]
@UtkarshSiddhpura check #1656

**Comment by UtkarshSiddhpura** [comment]
> @UtkarshSiddhpura please check #1656

Yes changes in #1656 are done in v1 not v2 listview

**Comment by AdityaKrSingh26** [comment]
On my local setup both v1 and v2 list view appears to be same. @llaske is the issue fixed ?
v1 -> 
![image](https://github.com/user-attachments/assets/8c141b5e-386b-4276-add0-dd3d07e6b60f)
v2 -> 
![image](https://github.com/user-attachments/assets/778d183e-ddd0-4ba5-a483-bb43f6e448c5)

**Comment by llaske** [comment]
@AdityaKrSingh26 the issue is still here. Are you sure you use http://localhost:8080/v2 when you test the v2?

**Comment by AdityaKrSingh26** [comment]
@llaske could you please help me with how start sugarizer on localhost. I have been using it using command "npm start -- --window --sdebug" or chrome --allow-file-access-from-files file:\\\<Directory>\sugarizer\index.html

**Comment by llaske** [comment]
@AdityaKrSingh26 you must install Sugarizer Server, see https://github.com/llaske/sugarizer-server/tree/dev

**Comment by AdityaKrSingh26** [comment]
Hey @llaske i have created a pr for v2 where i have resolved the issue. Do let me know if there are any other changes required.
![image](https://github.com/user-attachments/assets/0d267e8f-1edf-4b59-8f4c-5bf4d2585164)

**Comment by llaske** [comment]
@AdityaKrSingh26 that's better for alignment but the space between lines is now too huge.
We can display 3 fewer lines than before.

[Capture vidéo du 2024-11-05 21-54-08.webm](https://github.com/user-attachments/assets/5f0d537e-4376-41db-9423-2c6894d47416)

**Comment by AdityaKrSingh26** [comment]
Fixed : #1669
