### ISSUE TITLE
Hover effect over story books 

### ISSUE THREAD

**Issue by Monu2114** [llaske/sugarizer#1665]
Children would love story books to be popped up when clicked... So i wanna implement hover effect over the book items
![image](https://github.com/user-attachments/assets/51c8d14c-4d33-41a5-ac50-2caf28adaaf2)

**Comment by llaske** [comment]
Hover effect is not interesting on Sugarizer because most of users use touch devices where hover has no sense.

**Comment by a19hu** [comment]
@Monu2114 please assign this issue to me.

**Comment by Monu2114** [comment]
@a19hu dudeee i am not the owner lol

**Comment by a19hu** [comment]
> @a19hu dudeee i am not the owner lol

lol
