### ISSUE TITLE
Improve Visibility of Final Score Display in SprintMath by Changing Font Color

### ISSUE THREAD

**Issue by SnehalSrivastava27** [llaske/sugarizer#1668]
In the SprintMath activity, the final score displayed after the game ends is unreadable. The score text appears to blend with the background, making it difficult to view clearly.

**Steps to Reproduce:**

1.Complete a SprintMath activity.
2.Wait for the final score to be displayed.
**Observed Behavior:**
The final score text does not have sufficient contrast, making it hard to read.

**Suggested Solution:**
Changing the font color of the score display to black should improve readability and ensure it stands out against the background.

Environment:
Web and MacOS

Here's the screenshot for reference
<img width="1440" alt="Screenshot 2024-10-29 at 12 57 38 AM" src="https://github.com/user-attachments/assets/88ee2831-74d4-4847-b0bf-2b2438b3f6a0">

**Comment by SnehalSrivastava27** [comment]
<img width="1440" alt="Screenshot 2024-10-29 at 12 28 48 PM" src="https://github.com/user-attachments/assets/f223c473-6891-4042-a2f8-41a41eb84b63">
UI after changing text color to black

**Comment by llaske** [comment]
The message color depend of the buddy's colors.
For example:

![image](https://github.com/user-attachments/assets/7ebb7804-0f7c-4eb4-aa31-0cef215cb36c)

![image](https://github.com/user-attachments/assets/400a9cfc-5e0a-49ed-b779-6204d8fea5f0)

So it's most of the times readable.
Plus, the SprintMath activity is too basic so it's deprecated.

**Comment by SnehalSrivastava27** [comment]
Got it 
Thankyou so much
