### ISSUE TITLE
CONTRIBUTING.md has wrong instructions for "send your Pull Request"

### ISSUE THREAD

**Issue by TexZ-GenZ** [llaske/sugarizer#1672]
Current instructions in CONTRIBUTING.md

So to send your Pull Request:

 Clone this repository,
 Fork the dev branch of your new repository,
 Update this new branch with your contribution and commit your changes,
 Send a pull request from your new branch to the dev branch of this repository.

 The instuctions are wrong and confusing!
 Here's the corrected version of the instructions for sending a Pull Request:

  Fork this repository .
  Clone your forked repository .
  Create a new branch from the dev branch .
  Make your changes and commit them with clear and descriptive commit messages.
  Push your changes to the new branch on your forked repository .
  Create a Pull Request (PR) from your branch on your forked repository to the dev branch of the original repository.

**Comment by llaske** [comment]
These are basic instructions to do a PR on a repo.
We don't want to explain in detail what is a PR and how to submit a PR.
There is plenty of site that explain how to do a PR. For example: https://github.com/firstcontributions/first-contributions/

**Comment by TexZ-GenZ** [comment]
Actually i just got confused by the instructions and just wanted to point that out. I am just a beginner and when i saw the instructions saying clone the repository and then fork the dev branch of the new repository , it was actually quite confusing .
just wanted to point that out. Sorry for the trouble.

**Comment by llaske** [comment]
@TexZ-GenZ that's fine. Thanks.
