### ISSUE TITLE
[v2] Unable to preview the icons of activities.

### ISSUE THREAD

**Issue by utkarshdev2411** [llaske/sugarizer#1676]
While reviewing the v2 version, it was observed that icons are not visible for all activities.

![Screenshot from 2024-12-12 15-41-37](https://github.com/user-attachments/assets/de179469-6965-4f2c-8749-9a9ec48bbf01)

![Screenshot from 2024-12-12 15-41-46](https://github.com/user-attachments/assets/8c95a439-5974-4ccc-b569-99038fdd1a0b)

**Comment by llaske** [comment]
As explained in the [README](https://github.com/llaske/sugarizer/tree/feature/v2/v2) a symbolic link should be created.

**Comment by utkarshdev2411** [comment]
Okay. Thank you.

**Comment by utkarshdev2411** [comment]
Okay. Thank you.
