### ISSUE TITLE
Try version of certain activities do not work

### ISSUE THREAD

**Issue by amannaik247** [llaske/sugarizer#1682]
I wanted to try some activities , I went through this link https://sugarizer.org/activities.html to try certain activities. But some of them had an issue like they did not work at all or the '?' icon did not provide any context to how we are supposed to engage in the activity.
Some i tried were:
XO activity : Does not work
My Vue: '?' icon does not provide any context
![image](https://github.com/user-attachments/assets/0afb0b59-27e7-41dc-86a8-698b779d0a49)
Tangram: '?' icon does not provide any context
![image](https://github.com/user-attachments/assets/25c6fb31-48cd-4249-8688-e36619409bb4)

Software:
Using Chrome

**Comment by llaske** [comment]
Hmmm. You're right. Thanks.

**Comment by amannaik247** [comment]
@llaske it would be a better to route these links to sugarizer website instead , directly opening the activity. If possible, please let me know what folders and repos should I work on to change the routing.

**Comment by llaske** [comment]
> it would be a better to route these links to sugarizer website instead , directly opening the activity.

That was the idea but there was a bug when users never visit Sugarizer before.
I've just fixed it on https://github.com/llaske/sugarizer/commit/ec01927b7074536d7884ce8c0581e81e50d5a8f3
