### ISSUE TITLE
Add a font size drop down

### ISSUE THREAD

**Issue by Vishvsalvi** [llaske/sugarizer#1688]
# Add a font size drop down to select the desired font size

A drop down menu would be a better option to chose the font size instead of clicking on the IncreaseFontSize option

![{4988BF9E-A1D5-45F6-A1C3-CD888A4FAC3F}](https://github.com/user-attachments/assets/e461f61d-0e2d-4aa9-9b7b-c2253ab90a48)

**Comment by SaniyaBorkar** [comment]
I think the current implementation is better as it focuses on ease of use for children. It's easier to enlarge and shorten the font with just a click. If the suggested implementation is acceptable to @llaske , I would like to work on this.

**Comment by llaske** [comment]
You're right @SaniyaBorkar , the current implementation with two buttons is better for children.
Plus, drop down with a list size is something for users who can count. It's not the case for all Sugarizer users.
