### ISSUE TITLE
Content overflow in Home screen

### ISSUE THREAD

**Issue by cosmicAsymmetry** [llaske/sugarizer#170]
![a](https://user-images.githubusercontent.com/8233952/34653736-2a7bf43a-f416-11e7-93eb-98260a74c4f7.png)
Upon resizing the video we get to see that the description box overflows while there's ample space on the left.
![b](https://user-images.githubusercontent.com/8233952/34653739-35bcb56e-f416-11e7-951c-ec1f57902e72.png)

**Comment by llaske** [comment]
Responsive design is always complex but the principle of Sugarizer home is that window width should be larger than window height. Here it's not the case.
