### ISSUE TITLE
Activity Proposal: A white noise machine.

### ISSUE THREAD

**Issue by cosmicAsymmetry** [llaske/sugarizer#171]
While working I tend to put on some white noise as it blocks out other sounds and boosts productivity on https://www.noisli.com, It'd be pretty cool to have something like this on Sugarizer.(and even cooler if we can get the sounds to continue after the user leaves the activity.)

**Comment by llaske** [comment]
Why not. But more pertinent to integrate to [MusicBlocks](https://github.com/walterbender/musicblocks).
