### ISSUE TITLE
Typo in one of the help messages

### ISSUE THREAD

**Issue by CaptainDaVinci** [llaske/sugarizer#175]
![sugarizer](https://user-images.githubusercontent.com/21019116/34722357-904afe9e-f56c-11e7-8033-38040689e0f9.png)

**Comment by llaske** [comment]
You're right. A bad copy/paste.

**Comment by RosaGeorge31** [comment]
I'd like to fix this bug. Is anyone working on it?

**Comment by llaske** [comment]
Sure. Let's go.

**Comment by RosaGeorge31** [comment]
How do I edit the Etoys-Tiles.mo file?

**Comment by CaptainDaVinci** [comment]
Wouldn't correcting the typo in this [file](https://github.com/llaske/sugarizer) work?

**Comment by llaske** [comment]
Look like it's not a typo. It's just that the same message is used for two different things.
You have to dig into [tutorial.js](https://github.com/llaske/sugarizer/blob/dev/lib/tutorial.js) to learn more on that.

**Comment by llaske** [comment]
Merge in https://github.com/llaske/sugarizer/commit/a89c9d9c92bed93ae32eacf65057f13bf37f0631

**Comment by ritjoe** [comment]
So, can this be closed?

**Comment by llaske** [comment]
No, I close issue only when the version is released.

**Comment by llaske** [comment]
Released in https://github.com/llaske/sugarizer/releases/tag/v1.0
