### ISSUE TITLE
environment.user is undefined in tutorial

### ISSUE THREAD

**Issue by cosmicAsymmetry** [llaske/sugarizer#176]
Hello! I'm testing out the tutorial and I cannot seem to get past this error. The following is a screenshot of my console and my activity.js file

![image](https://user-images.githubusercontent.com/8233952/34736718-e7902878-f599-11e7-855e-ef867650a0ac.png)

```.js
define(["sugar-web/activity/activity", "sugar-web/env"], function (activity, env) {
  // Manipulate the DOM only when it is ready.
  require(['domReady!'], function(doc) {

		// Initialize the activity.
		activity.setup();

		// Welcome user
    env.getEnvironment(function(err, environment) {
			document.getElementById("user").innerHTML = "<h1>"+"Hello"+" "+environment.user.name+" !</h1>";
	});

  });

});

```
![image](https://user-images.githubusercontent.com/8233952/34736797-21d8f370-f59a-11e7-9f0f-006ceba5b171.png)

Everything else seems to be working fine. I personally don't know why it's undefined. Any help to understand this issue would be great.

Thank you!

Sidhant Bhavnani

**Comment by llaske** [comment]
Hmm. Are you sure you retrieved the dev branch of the repository ? The user could be undefined if you cloned the master branch instead.

**Comment by llaske** [comment]
Just to be clear: the env.js was updated in latest version of ActivityTemplate in dev branche. The issue you described make me think that you're using an old version of ActivityTemplate. So my advice is to clone the dev branch and to restart the tutorial with the right version.

**Comment by cosmicAsymmetry** [comment]
I removed the repo from my computer and tried to start off fresh. I recloned this repo and all its branches and checkedout to dev.

I seem to have more errors now. :p Now the homepage isn't loading. :/

![image](https://user-images.githubusercontent.com/8233952/34794488-cc17de2a-f674-11e7-8385-7334c8930fde.png)

**Comment by cosmicAsymmetry** [comment]
Nvm, I just cleared my cache. Back to testing.

**Comment by cosmicAsymmetry** [comment]
It seems to be running just fine now. Thanks! 😄

**Comment by llaske** [comment]
Good news.
