### ISSUE TITLE
Can't close paint app

### ISSUE THREAD

**Issue by nikitaermishin** [llaske/sugarizer#177]
I've got one more bug. When I want to close paint app, I can't do it. It's looks weird, but I also can't draw anything there. 
Here is GIF:

![pee](https://user-images.githubusercontent.com/26204565/34839493-ccf5aa18-f712-11e7-8de3-b56ebb17275e.gif)

**Comment by llaske** [comment]
Can't reproduce it. Could you tell us detail about your testing environment. Could you have see if there is error message in browser console.
