### ISSUE TITLE
Activity Idea: Math Quiz

### ISSUE THREAD

**Issue by manki11** [llaske/sugarizer#187]
A MCQ based game with a timer and a score. The questions will be based on basic maths functions (ie addition, multiplication, division and subtraction). The questions will be randomly generated. It will be a good way to hone up maths skills in an interactive way.

A demo of what the activity might look like:

![screenshot-2018-2-11 math game](https://user-images.githubusercontent.com/25136650/36073489-8aae4464-0f57-11e8-9ec1-64f611e93914.png)

**Comment by llaske** [comment]
Look like https://github.com/llaske/sugarizer/issues/132

**Comment by divyabaid16** [comment]
I would like to work on this issue. Can you please guide me ?

**Comment by llaske** [comment]
Look like @manki11 already work on it: https://github.com/llaske/sugarizer/pull/195
