### ISSUE TITLE
Score functionality in Abecedarium activity

### ISSUE THREAD

**Issue by hardiked** [llaske/sugarizer#191]
In abecedarium activity, students can play very fantastic games and it is amazing but there is nothing that keeps track of student's score as well as accuracy. Students also know how they are doing.

**Comment by hardiked** [comment]
I have completed the task see # 192 .It works fine and gives expected results.

**Comment by llaske** [comment]
Why not? See my comment on your PR.

**Comment by utkarsh-raj** [comment]
https://github.com/llaske/sugarizer/pull/193#issuecomment-370570135

Much work is probably accomplished in the previous iteration. Current task is to resolve the conflicts and incorporate the scoring feature in the Abecedarium Activity. Any pointers this task or the discussed changes are fine @llaske ? I am starting to work on resolving the conflicts.

**Comment by llaske** [comment]
@utkarsh-raj hmmm, you could try to fix but it's a very old PR, should be reviewed to see if it's still make sense.

**Comment by llaske** [comment]
Not pertinent.
