### ISSUE TITLE
getDataStoreObject is null

### ISSUE THREAD

**Issue by manki11** [llaske/sugarizer#196]
I am trying to implement data store in the sprint math activity, my method is given below:

```
document.getElementById("stop-button").addEventListener('click', function (event) {
            console.log("writing...");
            object_store={
                play:play,
                score:score,
                action:action,
                timeremaining: timeremaining
            };
            var jsonData = JSON.stringify(object_store);
            activity.getDatastoreObject().setDataAsText(jsonData);
            activity.getDatastoreObject().save(function (error) {
                if (error === null) {
                    console.log("write done.");
                } else {
                    console.log("write failed.");
                }
            });
        });
```
The error occurs in:
```activity.getDatastoreObject().setDataAsText(jsonData);```
My console is logging the following error:

<img width="700" alt="screen shot 2018-03-08 at 12 30 37 am" src="https://user-images.githubusercontent.com/25136650/37112291-fd2edd64-2267-11e8-9103-7dc0881e1a45.png">

**Comment by llaske** [comment]
Hmmm. If the datatstore object is null, it probably mean that you don't call the "activity.setup()" function at startup.
See [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step2.md#customize-content) for an explanation. I suggest you to do the whole tutorial.
