### ISSUE TITLE
Development server not working

### ISSUE THREAD

**Issue by manki11** [llaske/sugarizer#197]
The development server https://dev.sugarizer.org is not working.

Here in my settings it shows connected:
<img width="1273" alt="screen shot 2018-03-10 at 7 36 24 pm" src="https://user-images.githubusercontent.com/25136650/37243405-9fe4f196-249e-11e8-9656-b47017a7dea8.png">

When i try to access the server:
<img width="1273" alt="screen shot 2018-03-10 at 7 36 41 pm" src="https://user-images.githubusercontent.com/25136650/37243411-b270120a-249e-11e8-83bd-952b32f6e10f.png">

**Comment by llaske** [comment]
You're right.
Was related to a lack of empty space on the server.
Fixed now.
