### ISSUE TITLE
Paint activity not responding

### ISSUE THREAD

**Issue by manki11** [llaske/sugarizer#198]
On the dev branch of sugarizer, when Paint activity is launched the following error pops up:

<img width="699" alt="screen shot 2018-03-19 at 6 26 29 pm" src="https://user-images.githubusercontent.com/25136650/37596799-551a50a0-2ba3-11e8-855c-0be1c6b963c0.png">

The activity stops responding to click, and the user is not able to close the activity also. This bug doesn't appear when sugarizer is run in the master branch.
@llaske can you look into it.

**Comment by llaske** [comment]
Can't reproduce it. For example on http://dev.sugarizer.org
Could you be more precise on the way to reproduce this issue: is it when you open a new instance of the activity ? or reopening an old instance ?
Recently the same issue happened when the instance was set to favorite into the journal. Next time the instance was open, the error happened. But it should be fixed now.

**Comment by manki11** [comment]
@llaske on my machine, it is happening  when the instance is new or old. As far as i can see it only happens with the paint activity. It is even taking place when no server is connected. In the console it points the error at the journalchooser.js, in which the activities array is null.

Is paint activity the only activity to be using the journalchooser.js file?

**Comment by manki11** [comment]
The above problem was solved using localStorage.clear() in the browser window.
