### ISSUE TITLE
Port the Fraction Bounce Sugar activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#205]
Port the [Fraction Bounce](http://activities.sugarlabs.org/en/sugar/addon/4488) Sugar activity (Python) to Sugarizer (JavaScript).
Follow the Sugarizer tutorial "[Create your own activity](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial.md)"  to create a new Fraction Bounce activity.

Guidelines:

- The activity should be correctly integrated into Sugarizer (the activity icon should adapt its color when launched from the Sugarizer home view) 
- The activity should be responsive (work on any screen size)
- The activity should work with the keyboard and with the mouse (to support touch screen)
- The activity should use localization library lib/webL10n.js 
- The activity should work on any browser (Chrome, Firefox, Safari and EDGE)
- The activity should not use Internet connection (link to local content only)
- The activity should implement all existing features of the original activity
- The activity should retrieve graphics elements (icons, images, ...) of the original activity

**Comment by ashish0910** [comment]
@llaske can I work on this ?

**Comment by llaske** [comment]
@ashish0910 sure.

**Comment by b18050** [comment]
@llaske Can I also work on this?

**Comment by llaske** [comment]
No one has to ask to work on an issue. See https://github.com/llaske/sugarizer/blob/dev/CONTRIBUTING.md

**Comment by Swayamsvk** [comment]
@llaske actually I am comfortable with the making of activities in sugarizer but I know a little bit of python. Should I try it?

**Comment by llaske** [comment]
@Swayamsvk you're welcome. Porting don't mean to translate Python/Gtk code to JavaScript/HTML5 code. You can just use the current activity as inspiration but write a totally different source code.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/683
