### ISSUE TITLE
Port the Falabracman Sugar activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#206]
Port the [Falabracman](http://activities.sugarlabs.org/en/sugar/addon/4215) Sugar activity (Python) to Sugarizer (JavaScript).
Follow the Sugarizer tutorial "[Create your own activity](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial.md)" to create a new Falabracman activity.

Guidelines:

-  The activity should be correctly integrated into Sugarizer (the activity icon should adapt its color when launched from the Sugarizer home view)
-  The activity should be responsive (work on any screen size)
-  The activity should work with the keyboard and with the mouse (to support touch screen)
- The activity should use localization library lib/webL10n.js
- The activity should work on any browser (Chrome, Firefox, Safari and EDGE)
-  The activity should not use Internet connection (link to local content only)
- The activity should implement all existing features of the original activity
- The activity should retrieve graphics elements (icons, images, sounds, ...) of the original activity

**Comment by utkarsh-raj** [comment]
I want to understand the working of Sugar and how to port the activities from Sugar to Sugarizer. The issue seems like a great start. Can I work on this ?

**Comment by llaske** [comment]
Sure. No need to ask. Let's go.

**Comment by NightKing-iitr** [comment]
@llaske I am new to open source and would like to work on this issue. Can you give me any suggestion from where to start ?

**Comment by llaske** [comment]
@NightKing-iitr I suggest you to start by installing Sugar on your laptop. See instruction [here](https://wiki.sugarlabs.org/go/Downloads#Do_you_use_GNU.2FLinux.3F). Then you could install the Falabracman activity from [here](http://activities.sugarlabs.org/en/sugar/addon/4215) and play with it to understand how it works.

Then play with [Sugarizer](https://sugarizer.org) and do the [development tutorial](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial.md).

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/583
