### ISSUE TITLE
Fototoon close icon missing in small screens

### ISSUE THREAD

**Issue by vjrj** [llaske/sugarizer#213]
It seems that the close icon is missing and does not works in Android.

https://imgur.com/a/fapv550

Thanks/merci!

**Comment by llaske** [comment]
What is the size of your screen ? Could you send a full screen capture ?

**Comment by vjrj** [comment]
Screen: 1080x1920

https://imgur.com/a/lg6HfMq

**Comment by llaske** [comment]
Unfortunately Sugarizer is not really adapted today to smartphone screens.
BTW it will be better to do a CSS media query to avoid hiding the Stop button in any case else it's just impossible to go back to home view.

**Comment by llaske** [comment]
Source code for Fototoon activity is located here https://github.com/llaske/sugarizer/tree/dev/activities/Fototoon.activity

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/c4853c0c5f9b9cb80bc118cf53dd2f8a2b4b9e8d
