### ISSUE TITLE
Change the Help icon in Flip activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#214]
The help icon in Flip activity is not consistent with others help buttons in Sugarizer.
It's not used to explain how to play but to solve one step into the game.
Transform the Help icon into the "Robot" icon use in Reflection activity: https://github.com/llaske/sugarizer/blob/master/activities/Reflection.activity/icons/robot-on.svg

**Comment by HarrisonLKatz** [comment]
#220 just replaces the image of the help icon with the robot on icon. This was tested in Google Chrome as an unpacked web app, and it worked.
