### ISSUE TITLE
Many functions do not work

### ISSUE THREAD

**Issue by Iumen** [llaske/sugarizer#217]
Several functions in the Calculate activity on https://try.sugarizer.org/ do not do what they are supposed to. Arcsin and arccos return values when you input numbers less than or greater than one. Functions like mul and div are also not recognized and return "undefined symbol <function>".

**Comment by llaske** [comment]
@mikklfr could you explain how evaluation is done ? I guess it's based on JavaScript eval function but there should be some parsing too.

**Comment by mikklfr** [comment]
Hey @Iumen thanks for the report.
Thanks @llaske for mentioning me.

I have a few questions :
- Which browser/platform are you using ?
- Could you give some samples of calculations ? Something like : "using Radian mode, with acos(0) as input, I got ... but expected ..."

Thanks !

**Comment by llaske** [comment]
No way to reproduce it.
