### ISSUE TITLE
Add changelogs

### ISSUE THREAD

**Issue by Matrixcoffee** [llaske/sugarizer#218]
Please consider adding changelogs to the project, either in the form of a `CHANGES.md`, or via https://github.com/llaske/sugarizer/releases

**Comment by llaske** [comment]
Yes, you're right. I'm going to fix it.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/b204e54260b4822787520a5a99e9fb6e1a3c443f
