### ISSUE TITLE
ChatPrototype activity does not sanitize input

### ISSUE THREAD

**Issue by yummypasta** [llaske/sugarizer#225]
The ChatPrototype activity is susceptible to arbitrary script injection, and by extension, XSS.
![Animated GIF of demonstration](https://i.imgur.com/YoOt2Hm.gif)

To fix this, either sanitize all HTML tags, or select for certain "whitelisted" tags.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/231

**Comment by llaske** [comment]
Please leave this issue open until it's officially integrated into the release.
