### ISSUE TITLE
Save Maze level in Journal

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#260]
In the Maze activity when the user stop the game the current level is not stored in the Journal. So at next restart the game start to the beginning.
Fixing this require also to add a new button in the toolbar to restart the game.

Source code for the Maze activity is available here: https://github.com/llaske/sugarizer/tree/dev/activities/MazeWeb.activity

**Comment by lohani2280** [comment]
@llaske I would like to work on this issue.

**Comment by llaske** [comment]
Why not. BTW it will be better to finish other issues you're working on.
I advice you also to complete tutorial, at least step 4.

**Comment by lohani2280** [comment]
@niravasher Hey, I am already working on this issue. Can you please look into some other issues to fix?

**Comment by llaske** [comment]
@niravasher @lohani2280 Open Source is a collaborative effort, not a competition. Everyone is free to propose a fix, and everyone could improve code from others.
So @niravasher, feel free to send a PR if you think that you've got a fix on this issue.

**Comment by lohani2280** [comment]
@llaske Sorry about that. I understood now.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/270

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
