### ISSUE TITLE
Increase size of items in StopWatch activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#261]
Items (time, buttons) are too small so the activity is not very usable on small screens or on tablet.
The idea is to double the size of each line: two lines for one.

Source code is of StopWatch activity is here: https://github.com/llaske/sugarizer/tree/dev/activities/Stopwatch.activity

**Comment by lohani2280** [comment]
@llaske I am a newcomer here and I would like to work on this issue. Can I take this up?

**Comment by niravasher** [comment]
Hey is this still open as I have solved this on my local and I am a newbie here.
![screenshot 17](https://user-images.githubusercontent.com/32176296/51846885-805d7b80-2340-11e9-9c66-16c53e170299.png)

**Comment by llaske** [comment]
@niravasher , does it work on all browser? Currently the problem is that WebKit(Chrome/Safari) and Mozilla don't give the same result. See https://github.com/llaske/sugarizer/pull/264#issuecomment-457821742

**Comment by niravasher** [comment]
Ok will try to make it compatible with all browsers @llaske

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/264

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
