### ISSUE TITLE
Add a delete button in the new idea input field of Labyrinth activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#262]
The new idea input field into the Labyrinth activity miss a delete button to delete the whole content of the field. So, it's difficult to completely remove the content, specifically on tablets.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/981841/51566745-b492f100-1e95-11e9-9060-b367417d28c3.png">

The idea is to add a delete button into the input field: the same button that the one in the Search activity in Sugarizer home view. 
Styles to do that are described in the sample here: http://sugarlabs.github.io/sugar-web-samples/iconinputtext.html

Source code for the Labyrinth activity is available here: https://github.com/llaske/sugarizer/tree/dev/activities/LabyrinthJS.activity

**Comment by lohani2280** [comment]
@llaske I would like to work on this issue.

**Comment by llaske** [comment]
Sure. Feel free to work on it.

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
