### ISSUE TITLE
Integrate presence in Labyrinth activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#263]
Integrate presence handling into Labyrinth activity to allow playing the activity with other users on the network. So users could create a collaborative mind map.

You should add the presence palette and integrate presence like explained in the tutorial here: https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step6.md
See code for Labyrinth activity here: https://github.com/llaske/sugarizer/tree/dev/activities/LabyrinthJS.activity
You could use the SharedNotes activity source code to see how handle presence in a similar context (Cytoscape framework). See code for the SharedNotes activity here: https://github.com/llaske/sugarizer/tree/dev/activities/SharedNotes.activity

**Comment by lohani2280** [comment]
@llaske I would like to work on this issue.

**Comment by llaske** [comment]
@lohani2280 Sure, you're welcome.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/274

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
