### ISSUE TITLE
Improve Record activity to see picture in real time

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#266]
In the Record activity (except on iOS/Android), when you take a picture, you don't see a preview of the picture. You just see a rolling spinner.

<img width="1127" alt="capture d ecran 2019-01-24 a 15 45 07" src="https://user-images.githubusercontent.com/981841/51686820-6c88e100-1ff1-11e9-94ce-937e9f95da9f.png">

Conversely, the QR Code activity allow user to take a picture of  QR Code and provide a real time preview of the picture. 
The idea is to improve the Record activity to display a real time preview of the picture.

The source code of the Record activity is here: https://github.com/llaske/sugarizer/tree/master/activities/Record.activity
The source code of the QR Code activity is here: https://github.com/llaske/sugarizer/tree/master/activities/QRCode.activity

**Comment by quozl** [comment]
On Chrome OS with Sugarizer v1.1 and Record, I see preview.  The preview is right-way up.  When taking photograph, it is upside down.  I did not check for left-right swap.

**Comment by quozl** [comment]
Thanks.  Tested again.
* QR Code activity preview is right-way up and is left-right swapped (good); the QR is correctly read, but not shown, so I don't know if it is upside down.
* Record activity preview is right-way up and is left-right swapped (good), but the draft photograph and kept photograph are upside down (not as good).

In both cases, Camera privacy light remains on after activity is stopped.

**Comment by niravasher** [comment]
Hey this issue is solved right? @quozl @llaske . If not what is kept photograph and draft photograph? and how can I solve this issue?

**Comment by quozl** [comment]
Sugarizer is multi-platform.  Problem is on some platforms, as I've proved by saying not Chrome OS.  _kept_ and _draft_ refer to the continued existence of the photograph.

**Comment by llaske** [comment]
@niravasher, this issue is still open.
@quozl mentioned the specific way of working on Chrome OS but it's very specific to this platforms. The fix is still need on browsers (Chrome/Firefox/Safari) for all other platforms (Linux/Windows/MacOS).
As I said, to solve this issue, the idea is to adapt code from QRCode activity into Record activity.

**Comment by ashish0910** [comment]
@llaske can I work on this ?

**Comment by llaske** [comment]
@ashish0910 sure.

**Comment by ashish0910** [comment]
@llaske please review https://github.com/llaske/sugarizer/pull/275

**Comment by ashish0910** [comment]
#275

**Comment by ashish0910** [comment]
@llaske now added support for Firefox 65 and Chrome 72 .tested on electron on macosx , chrome and Firefox also . #275

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
