### ISSUE TITLE
Add filtering to speaker Activity 

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer#273]
The speaker activity speaks whatever the user types . However we can add some filtering to it prevent it from speaking abusive words and show warning message to the user to not using such words.

**Comment by llaske** [comment]
Don't think it's pertinent, we can't forbid to say abusive words so we can't forbid them to write it.
Plus we don't want to handle an abusive words list for each language.

**Comment by quozl** [comment]
I agree with @llaske.  For the Speak activity in Sugar, we [removed the curse filter](https://github.com/sugarlabs/speak/commit/a28ca6bd7939f2fa66994dfff57bb4d7f0b738ef) for similar reasons.
