### ISSUE TITLE
Limiting the extent of zooming out in Color My World Activity

### ISSUE THREAD

**Issue by utkarsh-raj** [llaske/sugarizer#276]
In the Color My World Activity, there should probably be a limiting factor on the extent a user can zoom out.  The current behaviour shows an awkward many map view when zooming out.

The possible solutions could be - 

- Limit the zoom to show only one full world map, or,

- Zoom extent remains the same, and the extra space is filled with ocean color.

I am currently working on a fix for the behaviour.
![screenshot from 2019-02-21 01-21-53](https://user-images.githubusercontent.com/28586681/53120181-48300e00-3577-11e9-959d-40ed3cbbe041.png)

**Comment by llaske** [comment]
Not really an issue, it's the same behavior in Open Street Map for example.

**Comment by utkarsh-raj** [comment]
I was not aware that this is the expected behaviour. I thought that maybe the target audience might find it a bit weird or misleading. Should I further continue working on this @llaske or the issue can be closed ?

**Comment by llaske** [comment]
In my opinion, it could be close.

**Comment by quozl** [comment]
My opinion also is that this can close.  Target audience is children as learners.  They find everything weird or misleading until they learn from experience what the behaviour is.  :grin:

**Comment by utkarsh-raj** [comment]
All Right. I think that this can safely close. Thanks for the reviews :)
