### ISSUE TITLE
npm build for Sugarizer has deprecated dependencies

### ISSUE THREAD

**Issue by utkarsh-raj** [llaske/sugarizer#278]
Module dependencies for Sugarizer has deprecated dependencies. This is shown in the npm install console log. We can probably work out the current maintained versions of the dependencies @llaske ?
Some are more critical and might expose RegEx DoS vulnerabilities as well.

![screenshot from 2019-02-23 01-44-24](https://user-images.githubusercontent.com/28586681/53269146-20bf7980-370e-11e9-948f-d796e4a4cf2d.png)

**Comment by llaske** [comment]
@utkarsh-raj what's your node.js version?

**Comment by utkarsh-raj** [comment]
NodeJS v8.15.0
npm v6.4.1

Does the issue have to be related to the client environment ?

**Comment by utkarsh-raj** [comment]
I figured it. To log the solution for reference- 

This is probably that v1.0 does not support NodeJS v8.x and above. Downgrading to v6.x solves the fibers build issues. Also I noticed that this deprecation issues need to be addressed for v1.1, if it has not been done already. Since the deprecated modules will not conflict or show warnings with older NodeJS versions, but the codebase needs to incorporate the maintained modules.

@llaske thoughts ?

**Comment by llaske** [comment]
For Sugarizer App, node.js is need only on dev environment (specifically to minify files) and to generate the electron version for Windows/Linux/MacOS.
So it's not a critical issue but it should be fixed for sure.
BTW fixing the issue is not only upgrading deprecated libraries, it means carefully testing on all environment.

**Comment by utkarsh-raj** [comment]
@llaske Will require a bit of work for the testing. I am on it :)

**Comment by llaske** [comment]
It's fixed in the v1.4.0
