### ISSUE TITLE
Stopwatch Activity - Lap Timings vanish after a few recordings

### ISSUE THREAD

**Issue by utkarsh-raj** [llaske/sugarizer#280]
The lap record in the Stopwatch Activity can only record a few timings. If we click on record after this, the previous records vanish and no new records are added. This also looks awkward because record limit is not specified.

Probably not a major issue, and might also be platform specific.

![screenshot from 2019-02-24 15-34-09](https://user-images.githubusercontent.com/28586681/53297820-0a1e3d00-384a-11e9-8061-e6bd4b2a4b77.png)
![screenshot from 2019-02-24 15-34-15](https://user-images.githubusercontent.com/28586681/53297821-0db1c400-384a-11e9-9f82-33f6bc3dcb52.png)

**Comment by llaske** [comment]
This activity has been changed (resized), see https://dev.sugarizer.org 
Records are now added at the end of the line so this behavior has disappeared.

**Comment by utkarsh-raj** [comment]
I am facing similar issues in the dev version also. The activity has been resized and looks good, but still can only record almost 15 times in full screen view. After 15, the previous records vanish and no new records can be added.

The Developer Tools prove that new records are being added at the end of the line, but it is not visible in the viewing area of the browser @llaske .

**Comment by llaske** [comment]
I think that 15 records is more than enough.

**Comment by utkarsh-raj** [comment]
They are, but also you can verify that as the viewport gets smaller, the number of visible records get even lesser.

I suppose a logic ammend can fix the issue. Or alternatively, the issue can be safely ignored and closed. Thoughts ?

**Comment by llaske** [comment]
You could suggest a fix if you want.

**Comment by utkarsh-raj** [comment]
All Right. I am on it :)

**Comment by Scar26** [comment]
Same thing's happening to me.
Would love to work on a fix for this.

**Comment by utkarsh-raj** [comment]
Figured out a neat fix. Proposed solution in #283 .

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/283

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
