### ISSUE TITLE
Exerciser Activity - Improvement add confirmation delete dialogue Box.

### ISSUE THREAD

**Issue by saadpasta** [llaske/sugarizer#285]
In Exerciser Activity when we click on delete to delete any test the application deletes it immediately.
I think we should add Confirm box to confirm if they actually want to delete the test.

**Comment by Scar26** [comment]
Working on it

**Comment by Scar26** [comment]
Solved the issue.Can anyone guide me on how to merge it?
Sorry. I'm new here

**Comment by saadpasta** [comment]
I was also working on but it's okay.
First, push your code on your forked repo and then Create MR button and then choose your branch on which you have worked and then click create.

**Comment by saadpasta** [comment]
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
Read this.

**Comment by Scar26** [comment]
Was that correct?

**Comment by saadpasta** [comment]
Yeah Great 👍

**Comment by llaske** [comment]
Should be posted to Exerciser repo: https://github.com/llaske/ExerciserReact
