### ISSUE TITLE
Exerciser Activity - Image do not appear properly on big screen.

### ISSUE THREAD

**Issue by saadpasta** [llaske/sugarizer#287]
Screenshot Below.
![screen shot 2019-03-06 at 4 15 17 pm](https://user-images.githubusercontent.com/23307811/53877657-93dcc000-402b-11e9-8807-e78f2719c479.png)

**Comment by llaske** [comment]
Fixed here https://github.com/llaske/ExerciserReact/pull/5

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
