### ISSUE TITLE
Add gender and grade to sugarizer web site

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer#290]
This is a screen shot from the sugar linux iso in the **_About me_** settings tab. 
This feature to edit the user grade and gender is not available on the website.

![Sugar iso](https://user-images.githubusercontent.com/20889958/54128744-6326cd00-4415-11e9-8577-e77a670108ff.png)

**Comment by quozl** [comment]
We have removed gender question from Sugar for next release.  None of the activities needed to know the gender or age.  One activity used age.  I'd like to remove the age question as well.  I don't think Sugarizer needs to ask about gender or age.

**Comment by ahmedkrmn** [comment]
So removing this from the Linux image is the next step right ?

**Comment by quozl** [comment]
Once we have consensus, yes.  But talking about it in Sugarizer issues won't build that consensus.

**Comment by llaske** [comment]
Thanks @quozl. For privacy reason I don't want to handle this sort of information in Sugarizer.
So it has no sense in Sugarizer neither.
