### ISSUE TITLE
Display language settings in 2 languages

### ISSUE THREAD

**Issue by YJDave** [llaske/sugarizer#292]
Languages in `Language setting` should not be translated according to local/browser language. So "English" should be "English" even if my local language of browser is "French" or something else.

![image](https://user-images.githubusercontent.com/25907420/54201621-1fef5b80-44f4-11e9-9a00-8b5cc0b11cfc.png)

Why?
Suppose I change my local language to "French", languages list in setting also changed, and I am no longer be able to change language back to "English" as I couldn't understand which one of the option was "English" as all options were translated to "French".

**Comment by llaske** [comment]
I don't think it's a problem. English is at first and name of languages are understandable in most languages. 
I never seen this sort of double translation elsewhere. Did you?

**Comment by YJDave** [comment]
I was not sure whether double translation is the most suitable solution. But I do think that there should be some way that allows user to see languages names without translated to local language. 
I have seen this double-translated language list setting on Twitter, not checked other applications. 
![image](https://user-images.githubusercontent.com/25907420/54252939-d2660380-4572-11e9-9d24-f96197eabd27.png)

What could be the appropriate solution to this problem, according to you?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/0cd4903a18c6c35a81589e2ac916530a0710ed87

**Comment by YJDave** [comment]
Closing the issue as it is fixed!

**Comment by llaske** [comment]
I don't close issue before release of a new version.

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
