### ISSUE TITLE
Language Button in Sugarizer website shows a broken image

### ISSUE THREAD

**Issue by AndreaGon** [llaske/sugarizer#294]
I'm not sure where to report this as I cannot find the source code of the Sugarizer website in Github:

![bug1](https://user-images.githubusercontent.com/44361130/54248577-29baa280-4578-11e9-87dd-a8924560d8d2.PNG)

This is what shows on my computer when I visit Sugarizer website. If I choose a language, only then will the flag image appear.

**Comment by quozl** [comment]
https://github.com/llaske/Sugarizer_doc perhaps?  Repository title is "Source code for Sugarizer web site https://sugarizer.org"
