### ISSUE TITLE
Firefox: New User Resistration input color is white

### ISSUE THREAD

**Issue by iamsid2** [llaske/sugarizer#301]
![Screenshot from 2019-03-19 08-49-44](https://user-images.githubusercontent.com/23580835/54578120-8dcfe180-4a24-11e9-9f4e-8651e1255676.png)
While Inspecting I got this:
![Screenshot from 2019-03-19 08-55-39](https://user-images.githubusercontent.com/23580835/54578196-d091b980-4a24-11e9-8596-cf6f9d03b146.png)

This needs to be fixed

**Comment by llaske** [comment]
Strange, it's not the case on https://dev.sugarizer.org and I can't reproduce it locally.
Could you explain how you do that?

**Comment by iamsid2** [comment]
This happens only when we use firefox browser.
I Typed my name in Firefox Browser and its color is white
![Screenshot from 2019-03-22 08-39-38](https://user-images.githubusercontent.com/23580835/54798326-404eb100-4c7e-11e9-82ff-fa92112063ec.png)

To recheck it i seleced the text area 
![Screenshot from 2019-03-22 08-39-47](https://user-images.githubusercontent.com/23580835/54798354-63796080-4c7e-11e9-8b37-7db44af6d581.png)

It is a bug and i am trying to fix it.

**Comment by iamsid2** [comment]
It happens when we use https://dev.sugarizer.org  also

**Comment by llaske** [comment]
Can't reproduce it, what's the version of your Firefox

**Comment by llaske** [comment]
Unable to reproduce, including on Firefox into Ubuntu.
