### ISSUE TITLE
Idea for Chopsticks Activity

### ISSUE THREAD

**Issue by utkarsh-raj** [llaske/sugarizer#304]
I was working on a pure JS implementation of the Traditional Japanese Game Chopsticks for demonstration at the local School Students Meetup. It came to me that a Chopsticks Activity can be a good asset to Sugarizer.

Chopsticks is a very easy to learn and difficult to master game for small children. Originally played with both of the hands, the Activity will have two counter for each player. I have uploaded some screenshots of the current development version of the implementation. More information about the Chopsticks Game: [https://www.activityvillage.co.uk/chopsticks-game](url) .

Please let me know your thoughts @llaske ? If the activity has pedagogic element, I can work on the Sugarizer Port of my development version.
![Screenshot from 2019-03-23 18-49-54](https://user-images.githubusercontent.com/28586681/54866694-5901b880-4d9d-11e9-89c2-683f2fb50a48.png)
![Screenshot from 2019-03-23 18-50-18](https://user-images.githubusercontent.com/28586681/54866695-5e5f0300-4d9d-11e9-9bbd-d518adbfaeca.png)
![Screenshot from 2019-03-23 18-52-19](https://user-images.githubusercontent.com/28586681/54866696-628b2080-4d9d-11e9-8e75-819a9dc828b3.png)

**Comment by llaske** [comment]
Hmmm. Seems very similar to Last One Loses activity.

**Comment by utkarsh-raj** [comment]
ChopSticks is a fundamentally different game. The Last One Loses Activity is also played with numbers, but a lot of possibilities are there in the given game. I will request you to take a look at the source and maybe give the game a try ?

[ChopGame Source](https://github.com/utkarsh-raj/chopGame)

@llaske thoughts ?

**Comment by llaske** [comment]
More fun with hands than with a computer. Not pertinent.
