### ISSUE TITLE
Start command shows error in Ubuntu18.04

### ISSUE THREAD

**Issue by Anshuman71** [llaske/sugarizer#305]
The start command in docs 
`
chrome --allow-file-access-from-files index.html
`
gives an error, we need to find the exact version name for chrome and then substitute it in the 
![Peek 2019-03-24 16-29](https://user-images.githubusercontent.com/28081510/54878410-8197ba00-4e52-11e9-978d-519937e2852c.gif)
terminal command
`
google-chrome-stable --allow-file-access-from-files index.html
`

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/306
