### ISSUE TITLE
Error in taking correct order in FoodChain activity

### ISSUE THREAD

**Issue by prabhupant** [llaske/sugarizer#308]
In the build game of Food Chain Activity, the correct order is sometimes not taken as correct due to alignment problems i think.
It should be fixed to promote easy drag and drop functionality

![order not correct](https://user-images.githubusercontent.com/19776278/54973393-b07a7100-4fb5-11e9-8d42-abb5b906cf49.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19776278/54973688-ef5cf680-4fb6-11e9-8262-41461bf21c3d.gif)

**Comment by llaske** [comment]
Not sure to understand, in your sample the right order is Fox EAT Hen EAT Corn. So your answer is false.

**Comment by ashish0910** [comment]
@prabhupant You are taking the order in reverse manner that is why you are getting false . Species at top of chain comes first and species at lower level comes after them .
