### ISSUE TITLE
Change background colour of speak activity according to XO color

### ISSUE THREAD

**Issue by prabhupant** [llaske/sugarizer#310]
the background of speak activity always remains blue. According to me it should change with the XO colors in order to look more appealing and follow the design principles of sugar.

**Comment by ashish0910** [comment]
@prabhupant Looks like it does : 

![Screenshot 2019-03-26 at 2 25 30 PM](https://user-images.githubusercontent.com/30404493/54983820-96e82200-4fd3-11e9-9d24-09d083b9b0ac.png)
![Screenshot 2019-03-26 at 2 28 27 PM](https://user-images.githubusercontent.com/30404493/54983828-994a7c00-4fd3-11e9-99a2-16c100aeff5b.png)
![Screenshot 2019-03-26 at 2 28 52 PM](https://user-images.githubusercontent.com/30404493/54983832-9a7ba900-4fd3-11e9-8ea4-c45613dd9c0c.png)

The Logic it uses is that it takes fill color of the xoicon for the background color of Speak activity

**Comment by llaske** [comment]
@prabhupant it change color only if you change buddy colors then opening a new instance of the activity (from the activity list view or from the menu item "new instance" in activity menu item)

**Comment by prabhupant** [comment]
@llaske shouldn't it be instantly, like when you change the buddy color, the color of icons and this background color should change?

**Comment by llaske** [comment]
No, it don't. It's related to entries in the Journal. Old entries use old colors, new entries (or old entries reopen) use new colors.
