### ISSUE TITLE
Icon color doesn't change with XO color

### ISSUE THREAD

**Issue by prabhupant** [llaske/sugarizer#311]
Colours of the previously opened icons don't change after changing the XO colors. Rather this happens when new icons are clicked and their colors is changed only.

![Screenshot from 2019-03-26 12-13-12](https://user-images.githubusercontent.com/19776278/54977273-cfcbcb00-4fc2-11e9-9b72-a48f094dc2d3.png)

**Comment by ashish0910** [comment]
@prabhupant looks like it is done intentionally . 
However this can be resolved by changing this -
https://github.com/llaske/sugarizer/blob/0cd4903a18c6c35a81589e2ac916530a0710ed87/js/homeview.js#L356
To this :
`colorizedColor: null,`

**Comment by llaske** [comment]
Yes, it's intentional it will change color only if you change buddy colors then opening a new instance of the activity (from the activity list view or from the menu item "new instance" in activity menu item).

**Comment by prabhupant** [comment]
@llaske @ashish0910 okay :sweat_smile: It was my first time using Sugarizer this much and  I didn't know that

**Comment by llaske** [comment]
@prabhupant, no problem you're welcome to learn.
BTW I think you could close the issue.

**Comment by prabhupant** [comment]
@llaske looking forward to working with sugar labs.
closing the issue
