### ISSUE TITLE
audio bar not displaying in chrome when opening a audio file(.wav) through journal

### ISSUE THREAD

**Issue by AvinashAgarwal14** [llaske/sugarizer#312]
When a user tries to open an audio file in .wav format, no audio bar is displayed in the media viewer activity.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/320

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
