### ISSUE TITLE
Menu options are not responsive

### ISSUE THREAD

**Issue by sameerkdarshi** [llaske/sugarizer#313]
The clock [activity](https://try.sugarizer.org/activities/Clock.activity/index.html?aid=101db376-a6da-4042-9040-cd19945057fa&a=org.sugarlabs.Clock&n=Clock) is displayed as expected on desktop version (Image 1) but the menu options do not adapt properly for the mobile version (Image 2, the stop option is not visible to the user).

Image 1
![clock-activity-desktop](https://user-images.githubusercontent.com/30270872/55027784-186b9e80-502c-11e9-8937-bc9215a5a01a.png)

Image 2
![clock-activity-mobile](https://user-images.githubusercontent.com/30270872/55027864-4ea91e00-502c-11e9-8236-676c85c56908.png)

An approach to solve the issue is to stack the menu options as viewport width decreases

**Comment by sameerkdarshi** [comment]
I would like to work on this issue.

**Comment by llaske** [comment]
It's not an issue, Sugarizer is not adapter to smartphone in portrait mode. I suggest you to read more about that https://github.com/llaske/sugarizer/issues/106#issuecomment-466171717

**Comment by sameerkdarshi** [comment]
Thanks for insights
