### ISSUE TITLE
Cursor issue in calculator activity on Chrome

### ISSUE THREAD

**Issue by sameerkdarshi** [llaske/sugarizer#318]
After an expression is evaluated, the cursor gets placed at the start of the result which leads to unexpected behavior. Gif illustrates the issue.<br>
![calculator_capture](https://user-images.githubusercontent.com/30270872/55133368-70e58d80-514b-11e9-8e72-71f92b93e966.gif)
I would like to work on this issue.

**Comment by Scar26** [comment]
I didn't find any such issue.Infact, after I evaluate an expression,the next time I enter something,it overwrites what is already written

**Comment by sameerkdarshi** [comment]
@Scar26 I used the [Activity](https://try.sugarizer.org/activities/Calculate.activity/index.html?aid=e846d1af-bd78-4f00-9b1a-ef4ec69708a8&a=org.sugarlabs.CalculateActivity&o=ada1f74c-1b2d-4af8-8cfe-ee3affd8cdb7&n=Calculate%20Activity) on Chrome and the issue is there while using the keypad layout provided by the Activity. Which browser did you try it on ?

**Comment by Scar26** [comment]
I tried it first on Firefox. Just tried it on chrome and there it was. 
Got the same issue as you.

**Comment by sameerkdarshi** [comment]
@Scar26 for your kind information I was working on this issue.

> ......
> I would like to work on this issue.

**Comment by Scar26** [comment]
> @Scar26 for your kind information I was working on this issue.
> 
> > ......
> > I would like to work on this issue.

I'm really sorry.
I really didn't notice. I wouldn't have done it if I knew

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/321

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
