### ISSUE TITLE
Smileys not displayed properly in chat prototype activity

### ISSUE THREAD

**Issue by Scar26** [llaske/sugarizer#322]
![sugarizer](https://user-images.githubusercontent.com/41830515/55273015-8db8c700-52eb-11e9-941f-dc42aa267981.JPG)

Working on this

**Comment by llaske** [comment]
Can't reproduce it. What's your browser?

**Comment by Scar26** [comment]
Chrome 68.This issue was noted on try.sugaizer.org as well as the electron version

**Comment by llaske** [comment]
Do you have the same issue on dev.sugarizer.org?
Could you do a small video to show how this issue happens?

**Comment by Scar26** [comment]
Yes the issue is there on dev.sugarizer.org as well
![chat](https://user-images.githubusercontent.com/41830515/55287612-d2666000-53c8-11e9-8bfc-611e7f5265f2.gif)

**Comment by Scar26** [comment]
Is there anything I should fix or test further regarding this issue @llaske ?

**Comment by llaske** [comment]
I've finally reproduce the issue on another computer with Chromium.

Fixed in https://github.com/llaske/sugarizer/pull/323

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
