### ISSUE TITLE
Jappy Activity print preview popup

### ISSUE THREAD

**Issue by AvinashAgarwal14** [llaske/sugarizer#326]
After clicking on clear the canvas toolbar button in Jappy Activity, print preview window gets opened.

**Comment by llaske** [comment]
Very strange. This popup clearly should not be here.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/327

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
