### ISSUE TITLE
Gear colours are reset on resume

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#336]
When an assembly of gears is made, then the activity quit, and resumed, the colours of the gears have changed.

Save the colors with the journal entry and restore them on resume.

Duplicate from https://github.com/sugarlabs/gears-activity/issues/2

**Comment by Scar26** [comment]
Working on it

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/340

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
