### ISSUE TITLE
Grid Paint Activity screen not working properly on Firefox

### ISSUE THREAD

**Issue by AndreaGon** [llaske/sugarizer#342]
Grid activity does not completely fill the screen on Firefox, and it shows a black background to the right:

![image](https://user-images.githubusercontent.com/44361130/56013826-3839dc80-5d25-11e9-8b71-77e5a8869b74.png)

![image](https://user-images.githubusercontent.com/44361130/56013851-56074180-5d25-11e9-94a4-a56aedd48566.png)

It works properly on Chrome.

**Comment by Scar26** [comment]
Working on it

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/99ed20d71c4f18635efacf0d61b2da383fc28b76
