### ISSUE TITLE
No erase button for recordings in Record activity

### ISSUE THREAD

**Issue by Scar26** [llaske/sugarizer#344]
Currently there is no way to delete a picture,video or audio recording in the record activity.

![record1](https://user-images.githubusercontent.com/41830515/56235695-8a705a00-60a5-11e9-95ac-6079195abb93.jpg)

**Comment by llaske** [comment]
Why not? But the UI should be simple and usable with a mouse or on a touch screen.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/345

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
