### ISSUE TITLE
Grammatical Errors in the Documentation

### ISSUE THREAD

**Issue by IbukunF** [llaske/sugarizer#347]
While I was going through the Sugarizer tutorial, I noticed some areas in the tutorial and the application with grammatical errors:

1. [Step 6 of the tutorial](https://github.com/llaske/sugarizer/blob/master/docs/tutorial_step6.md):

 - There is a line that says "Suppose that Michaël, an user connected on the same server than you want to Chat." that could be better written as "Suppose that Michaël, a user connected on the same server as you wants to Chat.".

- There is another line that says "Then, once the activity will be open, he will share the activity by clicking on the toolbar Neighborhood button in the Network palette." which could also be better written as "Then, once the activity is open, he can share the activity by clicking on the toolbar Neighborhood button in the Network palette."

2. [Step 4 of the tutorial](https://github.com/llaske/sugarizer/blob/master/docs/tutorial_step6.md):

- Says "So an user could expect to retrieve the same number of pawns when he reopen the activity" which could be changed to "So a user could expect to retrieve the same number of pawns when he reopens the activity"

3. [README of EbookReader activity](https://github.com/llaske/sugarizer/tree/master/activities/EbookReader.activity):

- There is a line that says "An user could change this URL by clicking on the Settings icon of the toolbar." which could be "A user ..."

4. Finally, In the second screen of the popup modal tutorial, the sentence "First, you need an user to associate your content." could also be changed to "First, you need a user to associate your content with."

**Comment by IbukunF** [comment]
The screen mentioned in 4 is shown here ![image](https://user-images.githubusercontent.com/32366708/58381657-89c4c080-7f8d-11e9-92c3-2c34b20eca22.png). I think this can be fixed by modifying the file called [template.pot
](https://github.com/llaske/sugarizer/blob/master/po/template.pot) at line 1302 but I would like some feedback first before making that change. The other changes have been made in a pull request.

**Comment by llaske** [comment]
Thanks. Please send a PR on the dev branch.
Regarding error on tutorial screen, the file to update is locale.ini. PO/POT files in Sugarizer are generated from the .ini file. See https://github.com/llaske/sugarizer/tree/dev#localization for more.

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
