### ISSUE TITLE
Add a pause button to the Physics activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#354]
Would be nice to add a pause button on the Physics activity to stop current movement of items. 
The button could be transformed into a Play button to continue movement.

Source code for Physics activity is here: https://github.com/llaske/sugarizer/tree/dev/activities/PhysicsJS.activity 

(Suggestion by [Sameer Verma](https://twitter.com/sameerverma/status/1132768962511495168?s=20))

**Comment by phorical** [comment]
Opened a pull request to fulfill this request: #355 .

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/355

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241
