### ISSUE TITLE
Build Application for android not working

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer#368]
While following [documentation](https://github.com/llaske/sugarizer/tree/dev#build-application-for-android-and-ios) for building Android application using Cordova 
This Error is generated : 

Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Error validating package name. Must look like: `com.company.Name`. Currently is: `org.olpc-france.sugarizer`

Steps To reproduce : 
Follow [documentation](https://github.com/llaske/sugarizer/tree/dev#build-application-for-android-and-ios) Steps . On running `cordova platform add android` above issue is generated .

**Comment by llaske** [comment]
Recent versions of Cordova don't allow using "-" character into name, it should be updated to "_".
So a substitution should be done like:

`sed -i -e "s/org.olpc-france.sugarizer/org.olpc_france.sugarizer/" config.xml`

A full script file to build Sugarizer on Android could be found here: https://github.com/llaske/sugarizer-apkbuilder/blob/master/src/make_android.sh

BTW I suggest to use [Sugarizer APK Builder](https://github.com/llaske/sugarizer-apkbuilder) to avoid the need to set up a full Android Cordova environment.

**Comment by llaske** [comment]
Documentation updated to point on APK builder script.
