### ISSUE TITLE
Presence palette implementation in Memorize is non standard

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#374]
The Presence palette implementation (located in `activities/Memorize.activity/lib/sugar-web/graphics/presencepalette.js`) in Memorize activity is nonstandard.
It's not conform to the standard implementation in `activities/ActivityTemplate/lib/sugar-web/graphics/presencepalette.js` and it's mixed with the code to display a popup.
The standard file should be used and the code to display the popup should be moved in the code of the activity.
Take inspiration on the implementation of this feature in Maze activity.

**Comment by utkarsh-raj** [comment]
Possibly fixed in #386

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/776
