### ISSUE TITLE
Add dead cells in Game of life activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#379]
Add a new toolbar icon in the Game of life activity to see dead cells.
When this icon is selected the board display dead cells in a specific colors.
See an example on http://www.conwaylife.com/

**Comment by prakashujjwal1010** [comment]
like when we have this 
![Screenshot from 2020-01-05 19-37-36](https://user-images.githubusercontent.com/40318927/71781303-05422200-2ff3-11ea-925a-849e47f5a8a8.png)
if we click the toolbar icon it gets
![Screenshot from 2020-01-05 19-37-32](https://user-images.githubusercontent.com/40318927/71781317-4803fa00-2ff3-11ea-87c6-b25dc5256627.png)

**Comment by llaske** [comment]
Yes, exactly

**Comment by prakashujjwal1010** [comment]
cool.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/558
