### ISSUE TITLE
Allow to control speed generation in Game of Life activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#380]
Add icons to control speed of generation in the game of life activity.
It could be for example a fast forward and fast backward button to a double and divide by 2 the current speed.

**Comment by prakashujjwal1010** [comment]
@llaske , I would like to work upon this issue.
I am thinking to add two toolbar buttons fast backward and fast forward. and I think i should avoid storing the speed value in datastore .

**Comment by llaske** [comment]
Sounds good. Do not hesitate.
You're right, you don't need to store the speed value in the datastore. BTW I think you should display it when it will change.

Note that there is no need to ask permission to work on an issue. See [here](https://github.com/llaske/sugarizer/blob/master/CONTRIBUTING.md).

**Comment by llaske** [comment]
Nice start. By the way I'm not a big fan to have one button only. It means that to slow the generation you should first accelerate it. It's counter intuitive. 
Alternatively may be we could use a slider instead of buttons.
Something like the one used to control rate in the Speak activity.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/981841/66136147-4513fa80-e5fb-11e9-9077-700c9b87d8e6.png">

It's used here: https://bitstorm.org/gameoflife/

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/bfe50cb516df1b85492265bd43f53e7d61d98bb9
