### ISSUE TITLE
Add a synth keyboard mode in TamTam Micro activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#389]
The idea of this enhancement is to add a keyboard mode into the TamTam Micro activity to allow user to play like a keyboard with the sound he choose. It will transform the activity into a mini synth keyboard.

To do that there is three things to do:

- Replace the current audio implementation [here](https://github.com/llaske/sugarizer/blob/dev/activities/TamTamMicro.activity/audio.js) using HTML5.Audio by the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Simple_synth)
- Integrate a Piano keyboard in the activity. Could be [this one](https://github.com/FreddieN/sugarizer/tree/master/activities/Piano.activity).

![uOQpaJI](https://user-images.githubusercontent.com/981841/66698475-c4ca5500-ecde-11e9-8914-7b4386044e67.gif)

- Implement synth instructions: could be something like [this](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Simple_synth).

**Comment by pidddgy** [comment]
@llaske would you want something where you can right click on a sound and a popover appears, with a button that goes to the piano view?

**Comment by llaske** [comment]
Hmmm. Right click is not a good idea because Sugarizer could be use on a touch screen.
Instead I'm thinking to:

- Update the activity to allow to "select" a sound. The selected sound will be the most recently used.
- Add a button to switch to a "Piano mode" in the toolbar. In Piano mode the list of sounds will be replaced by the piano view.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/544
