### ISSUE TITLE
Image selection error in Write activity after scrolling 

### ISSUE THREAD

**Issue by tk315** [llaske/sugarizer#390]
WHEN I WAS SCROLLING AFTER SELECTING THE IMAGE . I FOUND THIS BUG
![writeactivity](https://user-images.githubusercontent.com/56471793/66711501-c7927c00-edaa-11e9-9a92-0f6200f4135b.PNG)

**Comment by ashish0910** [comment]
@tk315 can you please create a pull request for its fix ?
Just add this
`this.quill.root.addEventListener('scroll', this.hide, false);` 
Below [this](https://github.com/ashish0910/quill-image-resize-module/blob/master/src/ImageResize.js#L39) and produce new minified file and replace it with current file [here](https://github.com/llaske/sugarizer/blob/master/activities/Write.activity/lib/quill/modules/image-resize.min.js)

**Comment by tk315** [comment]
@ashish0910 I had done the suggested changes in ImageResize.js and also created a pull request 
![Capture12](https://user-images.githubusercontent.com/56471793/66714375-a1350680-edd3-11e9-9862-b30c046dbfd9.PNG)
now what i have to do with minified file ? Will you please ellaborate it  ?

**Comment by ashish0910** [comment]
@tk315  replace current file  [here](https://github.com/llaske/sugarizer/blob/master/activities/Write.activity/lib/quill/modules/image-resize.min.js) with the new minified file and create a pr for it on this repository .

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/394
