### ISSUE TITLE
Add a button which pops up the "My Settings" panel

### ISSUE THREAD

**Issue by erilyth** [llaske/sugarizer#40]
To open the my settings panel, currently I am having to go to the neighborhood view and then access it from there. Since there is no popping frame from the edges (like in Sugar) where such buttons can be accessed from, I think it might be useful if we add this button somewhere.

**Comment by llaske** [comment]
No, the settings panel is accessible from the popup menu of the home view or the neighborhood view.

**Comment by erilyth** [comment]
@llaske how can we access the popup menu of the home view?

**Comment by llaske** [comment]
Right click on the buddy icon and the popup menu will appear.
