### ISSUE TITLE
Add a fullscreen button in the Maze activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#400]
The idea is to add a fullscreen button in the toolbar to increase the size for activities contents on small devices.

The complete process is describe in https://github.com/llaske/sugarizer/issues/399

**Comment by felipebrunetti94** [comment]
Working on it.

**Comment by NathanDimmer** [comment]
Working on it!

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/482
