### ISSUE TITLE
Package for SandStorm.io

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#41]
As the serverside part of Sugarizer grows in complexity - and importance! - it becomes more and more pressing to make setting up Sugarizer servers straightforward. 

I would therefore like to propose packaging Sugarizer for [SandStorm.io](https://SandStorm.io)

**Comment by llaske** [comment]
Hmmm. Not sure to understand how it could be use and what the impact could be on the current way of working of the server.
