### ISSUE TITLE
Add a fullscreen button in LastOneLose activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#418]
The idea is to add a fullscreen button in the toolbar to increase the size for activity content on small devices.

The complete process is describe in #399

**Comment by sarthak-g** [comment]
Yeah, I also feel the same.Can I work on this?

**Comment by pidddgy** [comment]
is this really necessary? space already seems to be used pretty well.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/30125762/70396641-ceb7be00-19d8-11ea-87eb-cb62826e3d61.png">

**Comment by llaske** [comment]
See my comment [here](https://github.com/llaske/sugarizer/pull/479#issuecomment-562862247 ), you will see a case where just hiding the toolbar without resize give a bad result.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/5e2a5035fa63ec7f3861f723d14517c135794208
