### ISSUE TITLE
gh-pages branch?

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#43]
In https://github.com/llaske/sugarizer/branches I see there is a gh-pages branch, not updated for 2 years. I suggest to remove it, or, perhaps better, to merge master into it and then set gh-pages to the default branch in https://github.com/llaske/sugarizer/settings and then remove the master branch from https://github.com/llaske/sugarizer/branches :)

**Comment by llaske** [comment]
You're right I've removed it. I don't to use gh-pages any more because since Sugarizer Server include node.js and MongoDB it can't work only in a simple HTTP server.
