### ISSUE TITLE
Add a tutorial to the LastOneLose activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#447]
Add a tutorial to the LastOneLose activity following tutorial 9 in Sugarizer development tutorial: https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step9.md

The tutorial:
* [ ] Should display a welcome message to explain the activity (could reuse the help message describing the activity in Sugarizer activities List view)
* [ ] Should explain usage of each button in the toolbar
* [ ] Should explain usage of each element in the UI
* [ ] Should be localized
* [ ] Should respect the Sugarizer UI, as explained in tutorial

**Comment by Ismailtlem** [comment]
Hi,

I'm interested in working on this issue

**Comment by llaske** [comment]
You're welcome.
BTW you don't need to ask to work on an issue and it don't prevent others to work on this issue too.
See https://github.com/llaske/sugarizer/blob/master/CONTRIBUTING.md

**Comment by carpecodeum** [comment]
hey can i ask what is the tech of this repo?

**Comment by llaske** [comment]
Regarding Sugarizer it's full HTML5/JavaScript but with a framework depending of each activity. See more [here](https://github.com/llaske/sugarizer/blob/dev/docs/architecture.md).
For LastOneLose activity, the EnyoJS framework is used.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/504
