### ISSUE TITLE
Move to github.com/sugarlabs?

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#47]
Why is this project in https://github.com/llaske and not https://github.com/sugarlabs ? :)

cc @walterbender

**Comment by llaske** [comment]
Historically the project started here and he stayed here. Will be happy to move it to sugarlabs but I'm not a sugarlabs committer.

**Comment by davelab6** [comment]
Do you know who admins it?

**Comment by llaske** [comment]
Guess it's @dnarvaez.
However my previous attempt to merge - specifically Sugar-Web, see https://github.com/sugarlabs/sugar-web/pull/110 and https://github.com/sugarlabs/sugar-web/pull/111 - was unsuccessful.

**Comment by walterbender** [comment]
Let me upgrade your status on github.com/sugarlabs and your should be able
to do the transfer.

On Mon, Apr 4, 2016 at 6:21 AM, Lionel LASKE <notifications@github.com>
wrote:

> Guess it's @dnarvaez <https://github.com/dnarvaez>.
> However my previous attempt to merge - specifically Sugar-Web, see
> sugarlabs/sugar-web#110 <https://github.com/sugarlabs/sugar-web/pull/110>
> and sugarlabs/sugar-web#111
> <https://github.com/sugarlabs/sugar-web/pull/111> - was unsuccessful.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/llaske/sugarizer/issues/47#issuecomment-205231039>
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by davelab6** [comment]
On 4 April 2016 at 06:21, Lionel LASKE <notifications@github.com> wrote:

> However my previous attempt to merge - specifically Sugar-Web, see
> sugarlabs/sugar-web#110 <https://github.com/sugarlabs/sugar-web/pull/110>
> and sugarlabs/sugar-web#111
> <https://github.com/sugarlabs/sugar-web/pull/111> - was unsuccessful.
>
Migrating the repo from user to org is not the same as make a pull request
to merge your commits upstream :)

**Comment by davelab6** [comment]
@llaske I upgraded your account so you can now do the transfer :)

**Comment by llaske** [comment]
@davelab6, @walterbender already send me the right to do that. I plan to do the transfer for the next Sugarizer version.

**Comment by davelab6** [comment]
Great!! (Actually he added you as a member, not an owner, so I upgraded your account to 'owner' level :)

**Comment by llaske** [comment]
Now on https://github.com/sugarlabs/sugarizer
