### ISSUE TITLE
Importance of unit testing?

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#49]
It seems that `/test` has not been updated for 4 months. 

For the next 'stable' release of Sugarizer, how important is it that the unit tests be updated? 

(I wondered about this since testing was mentioned in https://github.com/mattlag/Glyphr-Studio/issues/234)

**Comment by llaske** [comment]
4 months is the release date of the last stable version of Sugarizer.
We could hope that new unit tests will be include in the next release.
BTW Sugarizer unit testing currently cover:
- For client side: Datastore and Presence,
- For server: Activities, Users and Journal.

So there is not automated unit testing of the UI today.

**Comment by llaske** [comment]
Sugarizer Server not included full dedicated unit testing https://github.com/llaske/sugarizer-server/
