### ISSUE TITLE
Fix the clean all button in the Fototoon activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#513]
The clean all button in the Fototoon activity toolbar is supposed to remove all content.

![image](https://user-images.githubusercontent.com/981841/71306424-555c9a00-23e0-11ea-9dab-a0232253e902.png)

Currently, it does nothing.
The objective of this issue is:

* [ ] Fix the non working clean all button
* [ ] Add a confirmation box before effectively cleaning all the content

The confirmation box should look like a standard confirmation box in Sugarizer (don't use the standard browser dialog box). Text of the dialog box should be localized.

![image](https://user-images.githubusercontent.com/981841/71306463-edf31a00-23e0-11ea-9dd3-144ea97dce77.png)

**Comment by sarthak-g** [comment]
Clean all button is working properly. See:
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/42293606/71370478-05462900-25d4-11ea-98df-36a78acf626f.gif)

I think only confirmation box has to be added.

**Comment by llaske** [comment]
Hmmm, look like it works when the activity is reopened from the datastore but not when it was just created. See below:

![Peek 24-12-2019 23-49](https://user-images.githubusercontent.com/981841/71426306-13657980-26a8-11ea-941f-5341f0c3adcc.gif)

**Comment by sarthak-g** [comment]
You want "clean all" button should bring "3 of 3" to "1 of 1"(as in above) ?

**Comment by llaske** [comment]
Yes it should be "1 of 1" because the only remaining page should be the first one with title.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/554
