### ISSUE TITLE
Make responsive the toolbar in Write activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#515]
In Sugarizer it's important that whatever could be the screen size the Stop button is always visible to be sure the user will be able to quit the activity. So responsive activities use media queries in CSS file to hide other toolbar buttons depending of the window size. See for example Paint activity behavior:

![Peek 21-12-2019 11-03](https://user-images.githubusercontent.com/981841/71306559-1e878380-23e2-11ea-8bbf-f12881c1db7a.gif)

The Write activity toolbar is not responsive as you could see below:

![Peek 21-12-2019 11-04](https://user-images.githubusercontent.com/981841/71306562-3101bd00-23e2-11ea-9693-28e862503845.gif)

**Comment by NathanDimmer** [comment]
Working on it!

**Comment by NathanDimmer** [comment]
It looks like this was already implemented.

**Comment by llaske** [comment]
No it's not, the Stop button disappears like in the video capture above

**Comment by NathanDimmer** [comment]
It only does in my instance when the bar is showing only the Write save icon on the far left and the share icon, at least in my dev instance.

Should it continue to collapse smaller than 274px across, getting rid of the save and share icons?

**Comment by llaske** [comment]
The problem is not related to the activity icon or to the share icon, the problem is that the Stop button should be visible. As you could see in the screen capture below, the Stop icon is not visible

![image](https://user-images.githubusercontent.com/981841/71314087-92597880-2442-11ea-8403-170f4ec1c7a0.png)

**Comment by NathanDimmer** [comment]
We have different versions of Sugarizer running then, because this is what I see...

![Resizing GIF](https://user-images.githubusercontent.com/43499958/71314604-3e866980-2419-11ea-8dbc-7d881f882a24.gif)

**Comment by llaske** [comment]
Interesting the issue comes probably from https://github.com/llaske/sugarizer/pull/497 or https://github.com/llaske/sugarizer/pull/505 because it appears in the dev branch.

By the way, it's better if you've got the latest version of the dev branch to be able to reproduce an issue.

**Comment by NathanDimmer** [comment]
Ahhh, sorry, I didn't realize I had become out of date. Thank you!

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/528
