### ISSUE TITLE
Make responsive the toolbar in Physics activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#516]
In Sugarizer it's important that whatever could be the screen size the Stop button is always visible to be sure the user will be able to quit the activity. So responsive activities use media queries in CSS file to hide other toolbar buttons depending of the window size. See for example Paint activity behavior:

![Peek 21-12-2019 11-03](https://user-images.githubusercontent.com/981841/71306592-9ce42580-23e2-11ea-8df6-85322a6ceb69.gif)

The Physics activity toolbar is not fully responsive as you could see below:

![Peek 21-12-2019 11-09](https://user-images.githubusercontent.com/981841/71306595-a1a8d980-23e2-11ea-955e-d5ab04227b80.gif)

**Comment by NathanDimmer** [comment]
Working on it!

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/529

**Comment by Swayamsvk** [comment]
Is this issue open?

**Comment by llaske** [comment]
Issues are open until integrated in a release but as mentioned above by the "Fixed in #XXX" and the tag "to be release", no action is need on this issue.
