### ISSUE TITLE
Update etoys in Sugarizer

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#54]
Looks like there is already a port of etoys to js :) 

http://bertfreudenberg.github.io/SqueakJS/etoys/

**Comment by davelab6** [comment]
http://snap.berkeley.edu/snapsource/snap.html also fun

**Comment by llaske** [comment]
Etoys is already in Sugarizer ! thought not in the favorite view because it's not fully working on all platforms.

**Comment by davelab6** [comment]
Great! And snap? :)

**Comment by llaske** [comment]
Ooops not seen Snap. Will test it.

**Comment by davelab6** [comment]
Also http://lively-kernel.org

**Comment by davelab6** [comment]
l-k moved on to http://lively-web.org and is being actively developed

Great intro: https://www.youtube.com/watch?v=QTJRwKOFddc

**Comment by davelab6** [comment]
Also http://tinlizzie.org/chalkboard/#Home

**Comment by davelab6** [comment]
So, Lively is done by "the" Dan Ingalls, who was the guy who actually implement Smalltalk in the 70s and 80s with Alan Kay. http://lively-web.org/projects.html is a list of examples of it in use.

**Comment by davelab6** [comment]
Snap led me to http://bjc.berkeley.edu - very nice.

**Comment by davelab6** [comment]
http://aprt.us also very nice

**Comment by davelab6** [comment]
https://github.com/cdglabs/moonchild from the appertus org

**Comment by llaske** [comment]
Hmm. Most of these projects are not responsive and for most projects I don't see a clear way to integrate it directly into Sugarizer. I think it's better to let them run side by side with Sugarizer.
Plus, on Android for example, we could find Scratch JR which is most interesting than Snap in my opinion.
It's why I'm expect to have in Sugarizer OS a way to launch directly a native application from Sugarizer. So we could have the Scratch JR icon on the Sugarizer home view without the need to really integrate it into Sugarizer.

**Comment by davelab6** [comment]
>> Etoys is already in Sugarizer
> 
> Most of these projects are not responsive

Is http://server.sugarizer.org/activities/Etoys.activity/index.html responsive? 

> I don't see a clear way to integrate it directly into Sugarizer

Is Etoys integrated directly into Sugarizer?

> It's why I'm expect to have in Sugarizer OS a way to launch directly a native application from Sugarizer. 

:) My idea of #55 is that "Sugarizer Thin Client" ("Sugarizer Web"? :) would also launch directly related non-activities.

**Comment by davelab6** [comment]
>> Snap led me to http://bjc.berkeley.edu - very nice.
> 
> Scratch JR which is most interesting than Snap in my opinion.

If we integrate Snap, we could perhaps form a good relationship with the BJC project... :)

**Comment by llaske** [comment]
> Is http://server.sugarizer.org/activities/Etoys.activity/index.html responsive? 
No, it's why I've decided to put it in the "beta zone", i.e. not visible directly from the home view.

> Is Etoys integrated directly into Sugarizer?
For the moment, yes because it's an "legacy" Sugar activity and because it mimic the Sugar UI.
But once again I'm not sure that it will stay here for a long time. It's really not usable except on a PC.

> :) My idea of #55 is that "Sugarizer Thin Client" ("Sugarizer Web"? :) would also launch directly related non-activities. 
Okay I understand. So something like launching an external URL from the home view ?
But what is the difference with a favorite in your browser ?
In the context of Sugarizer OS where the whole application launcher will be replaced by Sugarizer, it make sense because there will be no way to launch other app. But in Sugarizer Web where you are in a browser I don't see the advantage to launch an external URL from the home view instead of launch it from your favorite bar (of from... Google :-) ).

**Comment by davelab6** [comment]
Per thread `[Sugar-devel] Javascript Activities` the SqueakJS version used can be updated

**Comment by bertfreudenberg** [comment]
This version works a lot better, but it doesn't use the JS Sugar API yet. Is that documented anywhere?

**Comment by davelab6** [comment]
AWESOME! Thanks Bert!!

On 3 May 2016 at 11:54, Bert Freudenberg <notifications@github.com> wrote:

> This version works a lot better, but it doesn't use the JS Sugar API yet.
> Is that documented anywhere?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/llaske/sugarizer/issues/54#issuecomment-216574394>
>



-- 
Cheers
Dave

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/pull/64
