### ISSUE TITLE
Add a home button in Grid Paint activity

### ISSUE THREAD

**Issue by s-mag** [llaske/sugarizer#546]
A home button should be added on toolbar so that a palette or drawing board can be changed instead of the small round button in the corner...

I guess this should avoid confusion and will improve UI.

![Grid Paint](https://user-images.githubusercontent.com/44548987/71645006-674f0e80-2cf7-11ea-8bef-97ff83d59641.gif)
 
<img width="960" alt="gp" src="https://user-images.githubusercontent.com/44548987/71645547-1b549780-2d00-11ea-92d8-df2e10e5eb63.png">

Currently tested in Firefox...
What do you think @llaske @FreddieN ?

**Comment by llaske** [comment]
I'm agree that the meaning of the small green circle is not clear.
BTW I'm not sure adding a button in the toolbar is a good idea. May be we can just transform the circle in a more significant icon. Do you have any suggestion?

**Comment by s-mag** [comment]
> I'm agree that the meaning of the small green circle is not clear.
> BTW I'm not sure adding a button in the toolbar is a good idea. May be we can just transform the circle in a more significant icon. Do you have any suggestion?

We can just change the icon to a home or kinda of a back button....

**Comment by llaske** [comment]
Let's try a back button

**Comment by s-mag** [comment]
> Let's try a back button

So should I choose a icon myself under free to use license and make a PR

**Comment by llaske** [comment]
Try to the use the < icon (see in Calligra activity on dev branch)

**Comment by s-mag** [comment]
> Try to the use the < icon (see in Calligra activity on dev branch)

I guess adding a button in toolbar would be better as the round button is drawn [here](https://github.com/llaske/sugarizer/blob/master/activities/Gridpaint.activity/js/gridpaint.js#L219).
What are your thoughts on this..
Or we can add the back button in upper left corner of the board...
It will be easily accessible.

**Comment by llaske** [comment]
Let's try to put the back button in upper left corner

**Comment by s-mag** [comment]
> Let's try to put the back button in upper left corner

Moreover there is a issue that if we click around the button it works....
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44548987/71664328-9ceb0a80-2d7e-11ea-81c6-e0a218ad0dc5.gif)

So it would  be nice to remove it.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/565
