### ISSUE TITLE
Resize function gives error in TankOp Activity

### ISSUE THREAD

**Issue by s-mag** [llaske/sugarizer#549]
I guess there is a bug in the code of play.js file.
It is due to the last commit with respect to the issue #404 .
Error comes in an infinite loop.
<img width="957" alt="Error" src="https://user-images.githubusercontent.com/44548987/71746333-9a79d500-2e92-11ea-81d6-9a341cba8695.png">

The error arises after we change modes of the game and the game stops working.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/44548987/71746609-59ce8b80-2e93-11ea-80f6-04ee7ff3038a.gif)

@llaske Can you replicate this Issue?

**Comment by s-mag** [comment]
Due this issue I was not able to resize screen while fixing issue #547 
I am working on it...

**Comment by llaske** [comment]
Hmmm. You're right.

**Comment by s-mag** [comment]
@llaske should I recreate resize function in play.js

**Comment by sarthak-g** [comment]
@s-mag thanks for raising this issue.
Fixed this issue in pull request #552

**Comment by s-mag** [comment]
@sarthak-g there is a new error coming
see here..

<img width="957" alt="Error2" src="https://user-images.githubusercontent.com/44548987/71763234-a8b20a80-2eff-11ea-93a5-a6f524cf959b.png">

Kindly fix this error as well...

**Comment by s-mag** [comment]
I have fixed this issue in #553

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/552
