### ISSUE TITLE
Sugarizer Server Sisters

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#55]
A number of other projects very similar to Sugarizer Server exist. 

It would be great for them to be integrated with Sugarizer Server in some way.... Here's the 2 I'm aware of so far:
- http://solarspell.org
- https://learningequality.org/ka-lite/

**Comment by llaske** [comment]
I know KA Lite, I used it to develop the KA View activity currently included in Sugarizer.
But I find KA Lite too complex both for users and to deploy on a server. My wish was only to have a browser to explorer Khan Academy videos and had a way to just copy videos somewhere on a basic HTTP Server. I had to deconstruct KA Lite to finally do that and just point on a server where video are deployed (see https://github.com/llaske/kaexplore for more).
BTW Sugarizer Server is not today a content manager. For example, you could deploy Khan Academy videos on a Sugarizer Server using an Apache root but it's not managed directly by Sugarizer Server. Transforming Sugarizer Server into a deployment server where teachers could deploy content to give it access to learners is interesting but it's not in the feature lists for the moment.

Bastien in CC https://github.com/bzg

**Comment by davelab6** [comment]
> Transforming Sugarizer Server into a deployment server

Hmm. That's not quite what I had in mind... but that phrasing gives me another idea :)

www.Sandstorm.io is a deployment server system, a good one. 

Perhaps Sugarizer Server should be packaged as a Sandstorm.io package (SPK)? 

Then if KA Lite and SolarSpell are also packaged as SPKs, it would be easy for schools to run them all.

**Comment by llaske** [comment]
Deployment server was not the right word that I had in mind. I'm thinking more about a "content server".
I'm not a big fan of the approach of mix tools together without building a real bridge between them.
Sure it could be easy with tools like www.Sandstorm.io but it's easy to deploy, not easy to use !
If a teacher have plenty of tools to admin  (Sugarizer Server, KA Lite, Solar Spell, ...) with each time a different UI, a different users administration, a different set features ... it will be very complex for him to use it.

**Comment by davelab6** [comment]
Sure. Many schools will also be running Moodle or something like that too, I guess. 

How many schools are using Sugarizer Server today? :)

**Comment by llaske** [comment]
Hmmm.
I guess: none :-)

**Comment by davelab6** [comment]
hehe :) Are the stats for server.sugarizer.org available?

**Comment by llaske** [comment]
Not yet. It was precisely what I've described in the GSoC project "Sugarizer Dashboard Server".
But because we don't have a token for that this year, @mikklfr tell me that it could work on it ;-)

**Comment by davelab6** [comment]
Okay cool :) Are any stats being collected for later analysis?

**Comment by llaske** [comment]
Very few. Hope that it will be improved with the start of the Dashboard project.

**Comment by davelab6** [comment]
Okay cool :)
