### ISSUE TITLE
Next Button in Fototoon activity disapperars for smaller screens

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#561]
Next Button in Fototoon activity disapperars for smaller screens.See below:
![nextbuttonFOTOTOON](https://user-images.githubusercontent.com/42293606/72208255-ad119100-34c6-11ea-9f27-f2f083f36bf9.PNG)

**Comment by llaske** [comment]
You're right but I think it has no sense to use Sugarizer on screens with a width less than 640px.
Look like the behavior you describe is for width < 550px.

**Comment by sarthak-g** [comment]
Yeah, you're right.
