### ISSUE TITLE
Font size of Title reduces in fototoon activity

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#563]
Font size of Title( only after applying all three color, bold, italic) reduces in fototoon activity on adding objects from datastore. See below:
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/42293606/72277732-77041680-3658-11ea-9ec8-fc3d9b4f4119.gif)

**Comment by s-mag** [comment]
Moreover the buttons does not work afterwards...
See here
![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/44548987/72332532-3223c280-36e0-11ea-8bdb-2aabbb8139b5.gif)

**Comment by sarthak-g** [comment]
> 
> 
> Moreover the buttons does not work afterwards...
Yeah, I forgot to mention that

**Comment by llaske** [comment]
Interesting. Very strange.

**Comment by anshuldutt21** [comment]
Hi , I would like to work on this issue.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/587
