### ISSUE TITLE
Improve responsiveness of TankOp activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#566]
On small screens the responsiveness of TankOp activity could be improved.
Specifically:
* [ ] The title in the toolbar is truncated
* [ ] One the home page the mission selection and mission completed texts override the image
* [ ] One the play page the wave and score texts are override by the LCD screen

The idea of this issue is to use media queries to change text font size/margin or image size to improve support of small screens.

![Peek 18-01-2020 10-58](https://user-images.githubusercontent.com/981841/72662065-6817be00-39e2-11ea-93b4-e994149ceb68.gif)

**Comment by b18050** [comment]
I will work on this issue.

**Comment by anshuldutt21** [comment]
Hi @llaske please review the PR to the dev branch. #573

**Comment by Swayamsvk** [comment]
I was trying this on my system and I am not having any idea how to change the size of the screen. Can you help me?

**Comment by hr1sh1-coding** [comment]
@llaske could I work on this issue, maybe help those already on it?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/905
