### ISSUE TITLE
 Distance block in TurtleBlocks Js.

### ISSUE THREAD

**Issue by b18050** [llaske/sugarizer#574]
While we can calculate distance, it is a bit clumsy. A distance block would be handy. By default, it should measure the distance between the turtle x,y and  mouse x,y

![distanceblock](https://user-images.githubusercontent.com/45814442/72981215-49f6f700-3e02-11ea-8a39-7b6af7000bbf.png)

**Comment by b18050** [comment]
![dis](https://user-images.githubusercontent.com/45814442/72985075-31d7a580-3e0b-11ea-9bfe-45704de613ad.png)

**Comment by llaske** [comment]
TurtleBlock is maintained in another repository.
This issue should be declared [here](https://github.com/sugarlabs/turtleblocksjs).
