### ISSUE TITLE
Improve design of Text Palette in Fototoon activity

### ISSUE THREAD

**Issue by anshuldutt21** [llaske/sugarizer#575]
The Bold and Italic buttons should get highlighted when selected so that the user knows that the text is selected bold or italics. Same can be done for the color codes. It can solved by doing minor changes in the toon.js file.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45336622/73075533-24411f00-3ee2-11ea-94da-7c42a56b3550.gif)

**Comment by llaske** [comment]
Yes, good idea.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/578
