### ISSUE TITLE
Improve Sugarizer spiral in home view

### ISSUE THREAD

**Issue by anshuldutt21** [llaske/sugarizer#579]
I think The activity icons on the main page are a little bit packed between 2 different radiuses. They need to be seperated a little bit to give the spiral feels which can be accomplished by improving the css of the main panel. Also the journal icon must be a little above and should look different than the usual activities.
![Screenshot from 2020-01-26 17-07-45](https://user-images.githubusercontent.com/45336622/73134603-68f1c500-405e-11ea-887a-fbcb17b02cbb.png)

**Comment by llaske** [comment]
I'm not comfortable with "Design issue" because design is not a technical problem.
BTW to answer to your suggestion: nothing is related to CSS in the Sugarizer main page. Everything is computed in JavaScript [here](https://github.com/llaske/sugarizer/blob/dev/js/homeview.js#L286). Feel free to send a PR if you think you could improve the current algorithm.
Regarding Journal icon appearance it comes from Sugar and it's where/how users expect to find it, it's not something we plan to change.

**Comment by Swayamsvk** [comment]
@anshuldutt21 do you want it to be a little bit spaced so that they could look more arranged and even?

**Comment by llaske** [comment]
You could improve the spiral like in Sugar:

![GetImage](https://user-images.githubusercontent.com/981841/73789916-f2607000-479f-11ea-9b9b-925c4c1ed4ef.png)

![GetImage(1)](https://user-images.githubusercontent.com/981841/73789924-f5f3f700-479f-11ea-8a08-779d7bbaf104.png)

**Comment by Swayamsvk** [comment]
Working on it.

**Comment by Swayamsvk** [comment]
I have already made the necessary changes but when I open a pull request It shows older commits.
![Screenshot from 2020-02-06 04-13-59](https://user-images.githubusercontent.com/42679893/73890189-66ca0a80-4897-11ea-9431-c918f71d9f2b.png)

What should I do?

**Comment by Swayamsvk** [comment]
Can you please tell me what should I do next because I have tried everything but it's not working?

**Comment by anshuldutt21** [comment]
@Swayamsvk are you making a pull request on the dev branch of sugarizer?

**Comment by Swayamsvk** [comment]
Actually at first, I have made my own separate branch named dev and then made a pull request it shows the same problem and then I made a separate branch dev1 and switched to it and made a PR and it also showed the same problem. I don't know exactly about sugariser dev branch. Should I make a comparison with it or what?

**Comment by anshuldutt21** [comment]
You have to make the pull request to the dev branch of sugarizer not the
master one. For now git pull the dev branch and merge your changes with it.
Then make a pull request to the dev branch.

**Comment by Swayamsvk** [comment]
Actually, at first I was launching the desktop application using electron. But when I open it in chrome the  spiral looks like this
![Screenshot from 2020-02-12 02-43-53](https://user-images.githubusercontent.com/42679893/74280022-f2cdad80-4d41-11ea-9e52-955715398f7c.png)
Is there a way of obtaining the full spiral in chrome. For better editing

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/e24a3d80fb23dbb06fb1e8fd8a25e9c929eaa139
