### ISSUE TITLE
KA View Activity, audio does not stop playing on exit

### ISSUE THREAD

**Issue by erilyth** [llaske/sugarizer#58]
When I play a video and then close it, the audio does not stop playing. On playing another video, the previous audio and the current audio get played together.

Also at times when I play a video, 2 audio sequences start playing simultaneously with a small time delay. On pausing the video, one of them stops but the other one still keeps running.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/releases/tag/v0.8
