### ISSUE TITLE
Disappearance of clock in set time mode in clock activity

### ISSUE THREAD

**Issue by anshuldutt21** [llaske/sugarizer#581]
The clock vanishes when in set time mode.
![sc](https://user-images.githubusercontent.com/45336622/73135928-36e85f00-406e-11ea-800a-fd57b0a4328b.gif)

**Comment by llaske** [comment]
It's true but it vanish only when the Clock style is "Nice clock". Nothing happen in "Simple clock" mode.
It's related to https://github.com/llaske/sugarizer/pull/531

**Comment by anshuldutt21** [comment]
I could work on this issue.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/582
