### ISSUE TITLE
Database doesnt store images in Fototoon Activity

### ISSUE THREAD

**Issue by anshuldutt21** [llaske/sugarizer#584]
After closing the Fototoon activity with an image opened, it does not store the image. So when the activity is opened once again, the image data is lost.
![Screencast 2020-02-03 19_04_08](https://user-images.githubusercontent.com/45336622/73657407-3e37ea00-46b8-11ea-9eef-7630096dc48b.gif)

**Comment by llaske** [comment]
Can't reproduce it. Try by yourself on https://try.sugarizer.org or https://dev.sugarizer.org
Are you sure you're on the latest dev branch?

**Comment by anshuldutt21** [comment]
@llaske I am on the latest dev branch. I tried it on https://dev.sugarizer.org also but the same problem persists. It should automatically open with the picture present but it doesnt. I even verified it with the code written which doesnt have this property.

**Comment by llaske** [comment]
@anshuldutt21 the "1 of 5" number in the bottom right of the screen means that you've got multiple images in your comic. I think you're expecting that the comic is reopen on the last image but it's not the case.
So click on the arrows buttons in the toolbar and you could find "missing" images.
Have a look on the tutorial to understand how the activity works.
