### ISSUE TITLE
reappearance of tutorial on resizing window after clicking next button on last step of tutorial 

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#590]
When we click "next" button in the last step of tutorial and resize the window, tutorial reappears, causing unwanted flickering of screen.
 
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/40318927/74106757-39c77180-4b8f-11ea-8937-562bd35ba44e.gif)

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/40318927/74106775-67acb600-4b8f-11ea-8b24-25aa50b18b13.gif)

This bug is everywhere where tutorial is used.

### Reason:
because the tutorial didn't end after clicking the next step.

### Solution :
there are number of solution for this bug like we can remove next button in last step but as we have to submit the template in constructor, so we should not do it.
so another solution can be to end the tutorial on clicking next ,

we can add onNext function in last tutorial step to end the tutorial 

example:
`	{
				element: "#solve-button",
				placement: "bottom",
				title: l10n.get("TutoSolveTitle"),
				content: l10n.get("TutoSolveContent"),
				onNext: function () {
					tour.end();
				}`

**Comment by llaske** [comment]
Hmmm. Not really a big issue.
It has no sense for the user to click on the Next button if he really want to end the tutorial.
Plus the tutorial will restart only if the window is resized and it doesn't really matter if the tutorial restart.

BTW if you find a simple fix for this. You could propose a PR.

**Comment by prakashujjwal1010** [comment]
yes, its not a big issue. but still i think its good to fix.
for example, user don't know about which step is the last step so he keeps clicking next button.
and then he plays the activity, do some work, and when he try to resize the window after some time, tutorial reappears from nowhere. it can become little annoying.

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/40318927/74142127-3deea000-4c1e-11ea-84de-5049f3441602.gif)

plus , we can fix this issue by just adding one line tutorial.js [see here](https://github.com/llaske/sugarizer/pull/591/files)

I have fixed the issue for color my world. see #591 
i can fix other activities also if you say.

**Comment by llaske** [comment]
Not really an issue.
