### ISSUE TITLE
Develop a new chess activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#592]
> This issue is a challenge for students to the [GSoC 2020](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2020.md). Every student interested to be candidate to GSoC 2020 Sugarizer projects must complete this task.

Develop **a new chess activity** for Sugarizer.

![image](https://user-images.githubusercontent.com/981841/74162843-b9058580-4c21-11ea-89ee-972268e78f79.png)

Detailed features expected:
- [ ] The activity should be playable against computer or against another user on the network (using presence).
- [ ] The activity should display the list of move during play.
- [ ] The UI of the activity should be simple, self-explanatory and respect Sugar standards.
- [ ] The activity should be correctly integrated into Sugarizer and use buddy colors when possible.
- [ ] The activity should be integrated with Journal (save its context in the Journal).
- [ ] The activity should use localization.
- [ ] The activity should include a tutorial to explain the UI and an interactive tutorial to explain how each pieces move on a chessboard.
- [ ] The activity should be responsive (work on any screen size) and should include a fullscreen button.
- [ ] The activity should work on any browser (Chrome, Firefox and Safari) and in Electron.
- [ ] The activity should not depend of an Internet connection (use local content only).
- [ ] The activity should work with mouse, touch and possibly keyboard.
- [ ] Every content/library used in the activity should rely on a Free Libre Open Source license.

Technically speaking, the activity could be written using pure JavaScript or using Vue.js inline (as in the [Calligra activity](https://github.com/llaske/sugarizer/tree/dev/activities/Calligra.activity)). JavaScript ES6 syntax should be avoided.

The activity should be based on [Chessboard JS](https://chessboardjs.com/) for the UI  and  [P4wn](https://github.com/douglasbagnall/p4wn) for the engine.

**Comment by sarthak-g** [comment]
I've two doubts:
1. "pawn promotes to" and "computer level" feature should be there or we can skip them using their default value?
2. Computer playing for both sides should be allowed?

**Comment by ashish0910** [comment]
1. Pawn should promote on reaching the end like in normal chess game . 
2. No I don't think we need computer vs computer . There should be computer vs Player or Player vs Player .

**Comment by Hemansh31** [comment]
can we use libraries other than P4wn for the engine?

**Comment by llaske** [comment]
You could if it match the rule above. Specifically: it work on any browser, it's open source, it not depends from a server side, it don't use ES6 syntax and feature (Service Worker, ...).

**Comment by Hemansh31** [comment]
@llaske I have submitted a PR #640 Please review....

**Comment by Swayamsvk** [comment]
Actually I was developing this activity and when I opened sugarizer I noticed this error.
![Screenshot from 2020-02-25 18-48-02](https://user-images.githubusercontent.com/42679893/75250911-7d60e300-57ff-11ea-97ca-baf16514307f.png)
As I haven't changed any internal file I don't know what's going wrong.

**Comment by Hemansh31** [comment]
@Swayamsvk  could you elaborate more as to what exactly you did and if maybe possible share the code

**Comment by Swayamsvk** [comment]
Is this due to internet connection.
I am having this error in the terminal.
![Screenshot from 2020-02-25 21-24-14](https://user-images.githubusercontent.com/42679893/75264408-6200d280-5815-11ea-847c-13d2364e4980.png)

**Comment by sarthak-g** [comment]
> Is this due to internet connection.
No, sugarizer works offline.
Is this working fine in firefox with about:config as false?

**Comment by Swayamsvk** [comment]
It works fine on firefox. But showing problem on chrome.

**Comment by llaske** [comment]
@Swayamsvk I suggest you to clean your browser cache

**Comment by Hemansh31** [comment]
@Swayamsvk try closing all tabs on your browser and then just running index.html from terminal

**Comment by Swayamsvk** [comment]
Thanks a lot @llaske it helped.

**Comment by ksraj123** [comment]
Few questions, 
- what if the user plays the game vs computer for a while and then shares the activity, what is the expected functionality here? Should the game continue in multiplayer from the same state or should it reset?
- if one user exits from multiplayer mode, should the game reset or the other user should be able to continue it with the computer?

**Comment by ashish0910** [comment]
- Yes the game will continue from same state . Although there will be reset button to restart game 
- Yes if the number of users reaches one , you should be playing against computer .

**Comment by ksraj123** [comment]
@ashish0910 thanks for the reply, I have another question related to the multiplayer mode, what happens when two people have already joined the activity and another person attempts to join it? Should the third person be not allowed to join? or maybe he could join but not do anything, just watch the game.

**Comment by ashish0910** [comment]
Yes the third person should be allowed to join the game as spectator . But if one of the user leave the game then the spectator can take place of the player

**Comment by llaske** [comment]
Thanks to all participants.
BTW we've decided that the winner of the challenge is https://github.com/llaske/sugarizer/pull/702
Anyone could propose improvements on the activity.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/702
