### ISSUE TITLE
Add a tutorial to the Chat activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#594]
Add a tutorial to the Chat activity following tutorial 9 in Sugarizer development tutorial: https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step9.md

The tutorial:

* [ ] Should display a welcome message to explain the activity (could reuse the help message describing the activity in Sugarizer activities List view)
* [ ] Should explain usage of each button in the toolbar
* [ ] Should explain usage of each element in the UI
* [ ] Should be localized
* [ ] Should respect the Sugarizer UI, as explained in tutorial

**Comment by Hemansh31** [comment]
@llaske I was working on this issue but i am facing a issue which is my tutorial isn't localizing even after I followed exactly what was given in the tutorial. Could you help me out a bit?

**Comment by Hemansh31** [comment]
![Screenshot from 2020-02-22 03-16-47](https://user-images.githubusercontent.com/48997514/75074510-d986e700-5521-11ea-9e79-2d3ee7fb19f7.png)
This is the code

**Comment by llaske** [comment]
@Hemansh31, it's hard to say without seeing your code. 
Send a PR, I will have a look on it.

**Comment by Hemansh31** [comment]
@llaske I have sent a PR, please do have a look!!

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/645
