### ISSUE TITLE
Add a fullscreen button in the Exerciser activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#602]
Sugarizer activities don't look good on devices with small screen - for example smartphones.
On these devices, the toolbar could sometimes take 1/4 of the screen.

To increase the size for activities contents, the idea is to add a fullscreen button in the toolbar  like in the QRCode activity. When clicked, the fullscreen button hide the toolbar and display only an unfullscreen button. When clicked, the unfullscreen button show again the toolbar.

This features is implemented here: https://github.com/llaske/sugarizer/blob/dev/activities/QRCode.activity/js/activity.js#L144-L160

The objective of this issue is to implement the same feature in the Exerciser activity.

The Exerciser activity is maintained in a specific repository so the issue should be fixed [here](https://github.com/llaske/ExerciserReact/issues/92).

**Comment by abhishektanwar** [comment]
@llaske I have fixed this issue and created a PR regarding the same in ExerciserReact repository
https://github.com/llaske/ExerciserReact/pull/93

**Comment by ksraj123** [comment]
@llaske I was also working on the same issue, it is fixed and created a PR. I used a different approach and implemented the resizing part similar to the qr code activity so created a PR even tough one was open already. https://github.com/llaske/ExerciserReact/pull/94
Please go through the PR and share feedback. Please consider merging it if it suited to the needs.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/45056b0e5773ab994bdcdfe019ec191d67a39db6
