### ISSUE TITLE
Stop Watch Activity is not responsive and has text overflowing problem. 

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#604]
stop watch activity has text overflowing problem.

![Screenshot from 2020-02-13 19-20-17](https://user-images.githubusercontent.com/40318927/74441935-9d56e500-4e96-11ea-9a0d-b48479c8d749.png)

the activity is not responsive also. so user will face problem on small screens.

![Screenshot from 2020-02-13 19-20-25](https://user-images.githubusercontent.com/40318927/74441993-bc557700-4e96-11ea-835f-bb5200232ca3.png)
![Screenshot from 2020-02-13 19-21-00](https://user-images.githubusercontent.com/40318927/74441998-be1f3a80-4e96-11ea-9581-67aa76eeae8f.png)

**Comment by llaske** [comment]
I think your issue duplicate https://github.com/llaske/sugarizer/issues/422 and https://github.com/llaske/sugarizer/issues/599

**Comment by prakashujjwal1010** [comment]
okay, but in large screen devices, the problem also persists

![Screenshot from 2020-02-13 20-15-00](https://user-images.githubusercontent.com/40318927/74446540-0d1c9e00-4e9e-11ea-8f33-5e99face71f5.png)

![Screenshot from 2020-02-13 20-19-22](https://user-images.githubusercontent.com/40318927/74446592-26254f00-4e9e-11ea-8b62-b484dc29c974.png)

**Comment by llaske** [comment]
Not everyone need so much time laps 😄

**Comment by llaske** [comment]
BTW you're right, the screen should at least be correct on the iPhone 6/7/8 resolution.

![image](https://user-images.githubusercontent.com/981841/74569326-72de5800-4f7a-11ea-8bec-379e3ea485bf.png)

**Comment by Swayamsvk** [comment]
We could fix this by limiting the number of time laps to 4.But its not going to solve the problem for small devices. Another option is we could increase the size of a partition for more than 4 time laps, reduce the size of buttons a little-bit and accordingly do it in smaller devices. Here, the only problem is it's not going to look good.

**Comment by dhruvmisra** [comment]
In my pull request #642, I have created a container for the stopwatch marks, which can scroll to accommodate new values. Also fixed some styling to make the design more responsive.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/623
