### ISSUE TITLE
Improve search results in sugarizer homepage

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#609]
Instead of only highlighting the activity after search it would be better if we could provide the result of the search in a textual manner.

**Comment by llaske** [comment]
Not a good idea. Sugarizer target child and some don't know how to read.

**Comment by Swayamsvk** [comment]
But when someone is typing something in the search bar he should expect some sort of text it should be easy for him. We can enable both the features by adding a drop-down in the searches and highlighting the required activity.

**Comment by llaske** [comment]
You could have the exact same result on the activity list view.

**Comment by Swayamsvk** [comment]
That's right but if we at least show the highlighted activity and its name on one of its side I think it would be better. What's your opinion about it @llaske.

**Comment by llaske** [comment]
I don't think so. Keep It Simple and Stupid is the rule in Sugarizer :-)

**Comment by Swayamsvk** [comment]
I think you are right @llaske
