### ISSUE TITLE
Add Button and Pawns invisible in Pawn Activity tutorial

### ISSUE THREAD

**Issue by pvsharshith** [llaske/sugarizer#612]
While I was going through step3 of creating Pawn Activity tutorial, I was unable to reproduce the following steps:

- Inserting an Add button in toolbar.

-  No icons of pawns being added to screen on clicking Add button(after adding functionality to Add button as per tutorial).

My screen after trying to reproduce both the steps above:
[MyScreen](https://github.com/pvsharshith/sugarizer/blob/master/actualScreen.png?raw=true)

But, expected screen as per tutorial:
[ExpectedScreen](https://github.com/pvsharshith/sugarizer/blob/master/expectedScreen.png?raw=true)

I felt this could be an issue to newbies trying to create an activity from tutorial.

**Comment by llaske** [comment]
You've decided to put the `icons` sub directory into the `activity` directory but it's not what mentioned in the tutorial [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step3.md#create-a-new-toolbar-button). As for other activities the `icons` sub directory should be at the root of the activity.
So there is no issue in the code mentioned in the tutorial.

**Comment by Swayamsvk** [comment]
It actually works perfectly you should follow the steps properly in order to get the results. It's not an issue in the tutorial.

**Comment by pvsharshith** [comment]
Oh I'm so sorry for that! I should have checked the tutorial properly once
more. I went wrong somewhere.
Anyways, I'll not let this repeat. Thanks for letting me know!
