### ISSUE TITLE
Nell Balloons, Nell Colors

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#62]
- [ ] http://nell-balloons.github.cscott.net
- [ ] http://nell-colors.github.cscott.net

**Comment by llaske** [comment]
Nell's Colors is very similar to Paint activity. I do like the idea to draw letters and the program recognize the right letter. I think it could be interesting to get this idea to write a dedicated activity to learn writing (at least for touch screens).

Nell's Balloons is nice. GCompris include a very similar activity to learn colors. Note that Nell's Balloons it don't work on Firefox and is very slow to launch.

What the idea to open an issue on that ? Inspiration ?

**Comment by davelab6** [comment]
I open such issues to suggest we Sugarizer-ize such edutech

**Comment by NikolayOG** [comment]
I would like to work on the idea for letter recognition. Does the design has to be similar to nell-colors. Also can I use libraries or the code from nell-colors.

**Comment by llaske** [comment]
Hi NikolayOG, Nice.
It's better to use the same UI than other Sugarizer activities.

**Comment by NikolayOG** [comment]
What about the libraries also can I use the code from nell-colors.  Also I was considering doing the letter  recognition with machine learning. What do you think?

**Comment by llaske** [comment]
Honestly I don't have any idea how to do that. May be you could ask to the author ?

**Comment by NikolayOG** [comment]
Ok, I will do some research and try to implement something.

**Comment by hardiked** [comment]
It could be easily be implemented with the help of machine learning. If no one is working on this and if it is still open I would like to implement this activity. Let me know as soon as possible.Thank you.

**Comment by llaske** [comment]
Sugarizer is written in HTML and JavaScript, should be multi-platforms and should write without internet connection. If you could implement machine learning with this constraint, sure, let's go.

**Comment by utkarsh-raj** [comment]
Hi, this idea seems great and looks deserted for now. Can I give it a try ?

**Comment by llaske** [comment]
@utkarsh-raj, sure. No need to ask.

**Comment by Hemansh31** [comment]
@llaske is this idea still in queue for implementation, I would love to work on this?

**Comment by llaske** [comment]
@Hemansh31 you could propose something

**Comment by Swayamsvk** [comment]
I don't know much about machine learning but I think the original code of nell -balloons don't have any ML implementation. By the way @Hemansh31 are you working on this because I just want to give it a try?

**Comment by Hemansh31** [comment]
@Swayamsvk I am working on Nell colours

**Comment by Hemansh31** [comment]
@llaske can I change the UI of the Nell colour activity while implementing it in Sugarizer?

**Comment by llaske** [comment]
@Hemansh31 yes, it's not all compatible with the Sugar UI

**Comment by Swayamsvk** [comment]
Actually, I was trying to run nell-balloons cloned from the actual Github repo and it failed. Have you faced the same problem @Hemansh31 in nell-colors?

**Comment by llaske** [comment]
Exploration of this new feature is not convincing.
