### ISSUE TITLE
Time laps in stopwatch activity should be reset when reset button is clicked

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#624]
The time-lapse feature in the stopwatch activity should save the time-lapse in a  continuous manner without any interruptions. But currently, as the reset button exists it creates a problem. The reset button is responsible to reset the time in the middle of a time-lapse
![Screenshot from 2020-02-21 18-30-13](https://user-images.githubusercontent.com/42679893/75037904-34e1b680-54db-11ea-8805-6c2cd9fff20a.png)
 and it may create a problem if it is being used to record time-lapse in an actual event.

**Comment by prakashujjwal1010** [comment]
@Swayamsvk , I think, a quick and simple fix can be just clearing all the timelapses whenever the reset button is clicked. See [here](https://www.timeanddate.com/stopwatch/) :)

**Comment by Swayamsvk** [comment]
@prakashujjwal1010 it seems like a good idea.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/625
