### ISSUE TITLE
Wrong text appears upon hovering on buttons in Blockrain activity

### ISSUE THREAD

**Issue by abhishektanwar** [llaske/sugarizer#627]
Text should appear as "Rotate Block" instead of "Up Arrow"

![blockrain_issue_1](https://user-images.githubusercontent.com/40486188/75089283-38c61500-557d-11ea-9da2-3641c6250972.gif)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/628
