### ISSUE TITLE
"Sugarizer objectives for 2016" minutes

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#63]
I thought I'd post this here as I found it in the semi-private XSCE weekly call minutes, and got permission from Adam Holt to re-publish. 

---

On Dec 30, 2015 Lionel Laske did a guest talk for the XSCE community on "Sugarizer objectives for 2016":
- 4 strong legacy activities now much-strengthened in Sugarizer, thanks to hard work in 2015: 1 Memorize, 2 Paint, 3 Calculate, 4 Record.
- Bonus Physics activity now uses accelerometer, Record publishes to Journal, Khan Academy Explorer can use online or offline link to content, dramatic TurtleJS enhancements since earlier this year, Labyrinth activity, Etc.  While there’s no Pippy activity of course (Javascript has replaced Python!) one could imagine integrating brython.info’s Python 3 implementation for client-side web programming.
  Per-user Memory/CPU footprint unclear to date as servers will need to scale to larger schools, but “Write your own web activity” Development Kit is here: https://github.com/sugarlabs/sugar-docs/blob/master/activity.md
- Lionel hoping for “full Android launcher” thanks to his Paris student Michael during summer-of-2016 Google Summer of Code?  Permitting seamless launch of Android apps like GCompris from Sugar wheel!  Many of other Google Code-in students working on activities as well.
- Sugar’s Frame (border around screen) is not relevant today; Sugarizer’s top-banner is sufficient for now, given each activity is largely a self-contained experience triggered by an index.html (that could potentially change, restoring OS-like visuals on the bottom of the screen as Sugar 0.10x have increasingly offered in recent years, for highlighting/Speaking phrases in any activity to say them out loud with Ctrl+Alt+S and other OS-level visuals/quick adjustments, not requiring the full “My Settings”.
- Lionel very impressed by Tim’s XSCE+Sugarizer integration live demo, which just works with multi-user “collaboration” (Journal) and live “presence” inter-user messaging etc too!  WARNING: while “My Settings” on above server shows Sugarizer 0.7, this is not yet 100% final -- for now it’s in fact “Sugarizer 0.7 Pre-Release” would be more correct, and it should probably be labeled as such.
- http://Sugarizer.org itself remains at stable release 0.6 for just a bit longer: hopefully not that many days/weeks until 0.7 is official!  Even with Sugarizer.org being a small web instance, it should be able to handle 20 simultaneous users during Los Angeles’s large conference Jan 21-24: https://www.socallinuxexpo.org/scale/14x
- Conclusion: Sugarizer can be a platform to (re)engage and turn on new developers, potentially in very large numbers, with a code-to-testing-to-active-learning experiential loop closer to so many people’s modern Android/iOS/RPi/NUC/etc realities!
- Lionel clarifies how straightforward installation truly is (certainly Sugarizer Server without Presence/Collaboration).  So just copy/paste Sugarizer source code into a directory exposed from a HTTP server.  That's all: http://XSCE/sugarizer_directory_exposed
- Sugarizer Server integration with Presence/Collaboration is slightly more complex because a node.js + MongoDB process is needed. Detail @ https://github.com/llaske/sugarizer/blob/master/README.md#server

Tim’s questions and comments:
- would ejabberd work for presence? (already installed)
- we have one other nodejs app; can there be conflicts?
- had to change 8080 to another port because conflicts with idmgr
- is there a release branch/tag we should use to install rather than master?
- should we leave in web root or put in /opt or /library? (currently 485M)

Lionel’s replies:
- about docs mentioning port 80, while ini file has 8080 on XO-1.5 testing?  In fact, the current implementation of Sugarizer server with collaboration rely on two HTTP server: Apache2 and node.js:
  - Apache2 is use to serve all static contents (by default on port 80)
  - Node.js is use to server dynamic content: RESTful API of the Sugarizer server (by default on port 8080)
- The link between those two HTTP servers is in the .htaccess  (eg https://github.com/llaske/sugarizer/blob/master/api/.htaccess ) This file asks Apache2 to redirect all calls to Sugarizer api directory to the node.js server.  So http://server/ will go to Apache2 but http://server/api will go first to Apache2 then will be redirected to node.js.

Caryl’s questions for Lionel: 
- Additional Sugarizer priority Activities. My choice: TamTam… What would be needed to get universally working versions on Sugarizer for: TamTam Mini… a playable onscreen keyboard with at least one octave similar to some of the Apps available in the app stores… but with the ability to use the many different voices available on our TamTam suite. A “drum kit” similar to the one in TamTam would be nice too. It would probably need a screen of its own for set up. So there would be (at least) 3 screens needed… one to choose the instrument voice (already have that in TamTam Micro), one to set up the drum kit, and one with the keyboard to play along.  (Others can add their own favorite Activities for additions here too…)

Jerry’s question for Lionel: 
- Any plans to distribute sugarizer via pre-compiled packages such as rpms or debs?  (Not at this time?)

**Comment by llaske** [comment]
Outdated information. No more useful here.
