### ISSUE TITLE
Add Fullscreen on Sprint Math Activity

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#633]
There should be a full-screen button on Sprint Math activity for proper viewing on small devices.

**Comment by llaske** [comment]
The activity is full playable on small devices.

![image](https://user-images.githubusercontent.com/981841/75099022-34b9e780-55bd-11ea-9fe2-0d6c16b86e60.png)

Plus the toolbar is needed to restart the game.

**Comment by Swayamsvk** [comment]
But still, as we are adding the full-screen functionality on each event this is going to create uniformity among them that why I created this issue. It completely depends on the user whether to use it or not.

**Comment by llaske** [comment]
In usual software you're probably right but in the context of Sugarizer where users are children: less is better. So if a button is not need we could remove it.
I've created issues for activity where fullscreen button is needed.

**Comment by Swayamsvk** [comment]
What about scratch activity I think we need a full screen and a tutorial there.

**Comment by llaske** [comment]
Scratch activity already has a fullscreen button in its UI.
Regarding tutorial, it has no interest to try to describe the Scratch UI. Lot of Scratch tutorial already exist.
