### ISSUE TITLE
Unnecessary display of time lapse when stopwatch not started

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#638]
In stopwatch activity, unnecessary time-lapse is shown when mark button is clicked.
![Screenshot from 2020-02-23 20-40-48](https://user-images.githubusercontent.com/42679893/75114627-abb6b500-567d-11ea-8d6a-b5a48d5bac80.png)

**Comment by llaske** [comment]
Okay. Not a serious issue but it seems that you're a fan of the Stopwatch activity :smiley:

**Comment by Swayamsvk** [comment]
Actually, I was observing this particular activity and raising issues, gonna raise issues in other activities soon.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/639
