### ISSUE TITLE
Journal functions not visible on mobile

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#646]
After selecting an activity, the Erase activity function is not visible on mobile devices including iPhone 6/7/8 Plus. (Also the 'Copy to your device' feature in smaller devices)
This affects major functionalities as the user might not be able to delete unnecessary activity instances.

iPhone 6/7/8 Plus:
![Annotation 2020-02-26 001405](https://user-images.githubusercontent.com/40134655/75278130-5b7f5480-582f-11ea-92ce-9d8e9593e319.jpg)

Pixel 2 XL:
![Annotation 2020-02-26 001613](https://user-images.githubusercontent.com/40134655/75278420-d7799c80-582f-11ea-9c5f-3ef7c213a051.jpg)

**Comment by dhruvmisra** [comment]
I have solved this issue in my pull request #647.

**Comment by llaske** [comment]
You're not in normal condition: https://github.com/llaske/sugarizer/issues/422
