### ISSUE TITLE
Erratic sizing of the Calculator

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#649]
The calculator displays irregular responsiveness for different screen sizes, filling only half the screen on mobiles. Makes the calculator harder to operate and see results.

![before](https://user-images.githubusercontent.com/40134655/75288083-97231a00-5841-11ea-9f70-00fee97764e5.gif)

**Comment by llaske** [comment]
You're not in normal condition. See https://github.com/llaske/sugarizer/issues/422

**Comment by s-mag** [comment]
@dhruvmisra Sugarizer activities are not meant or designed to work in small screens. See #422 
There is no need to correct all these activities as no one will use them in such a small screen size.These activities work perfectly in normal conditions...
