### ISSUE TITLE
Sugarizer Scratch

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#65]
Seems there was "something" and there will be a real html5 runtime soon :D 

https://github.com/LLK/scratch-html5/issues/112

**Comment by llaske** [comment]
Nice news. Can't wait to see that.

**Comment by davelab6** [comment]
https://github.com/LLK/scratch-blocks/

**Comment by llaske** [comment]
Very cool. Only the editor for the moment and without Scratch blocks. But very promising.

**Comment by llaske** [comment]
A first integration has been realized by Emily. It's available [here](https://github.com/EmilyOng/Scratch.activity) and will be integrated in v1.0.

**Comment by llaske** [comment]
Released in https://github.com/llaske/sugarizer/releases/tag/v1.0
