### ISSUE TITLE
Add an option to navigate back to Contents in Ebook Reader

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#651]
In the Ebook Reader, once we navigate to a page of a book, there is no option to go back to Contents (Index). The only 2 ways are either by closing the entire activity and opening a new one, or by pressing the previous page button enough times to navigate back.

**Problematic Scenario**:
A user accidentally clicked on the wrong page number in contents.
![ebookIssue](https://user-images.githubusercontent.com/40134655/75347538-f37c4d00-58c6-11ea-982e-8a8f13834820.gif)

**Potential solution**:
Adding a button in the toolbar to navigate back to contents or the start of the book.

**Comment by llaske** [comment]
Why not.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/652
