### ISSUE TITLE
Text not visible in search bar of Calligra Activity

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#661]
Can't see inputted text in the search bar while inserting item.

![calligraTextIssue](https://user-images.githubusercontent.com/40134655/75990866-89455700-5f1b-11ea-9ba1-8ffc3c2e04d9.gif)

**Comment by llaske** [comment]
You're right. Good point.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/662
