### ISSUE TITLE
No option to reset the template in Calligra

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#663]
Once items are deleted in edit mode, there is no option to bring them back. Only way to get them back is starting a new instance of the activity.

**Problematic scenario**
Someone accidentally deletes some/all items.

![calligraResetIssue](https://user-images.githubusercontent.com/40134655/76002454-a5052900-5f2c-11ea-8bbe-dd426f5aba02.gif)

**Potential solution**
Adding a button in toolbar to reset the current template.

**Comment by llaske** [comment]
Hmmm. I don't think it's useful. It's a very rare scenario.
Few users will create new templates and it will be only experimented users.
If your scenario occurs to others users, it will be easy to create a new instance of the activity to retrieve the original templates list.

**Comment by dhruvmisra** [comment]
I agree @llaske that it wouldn't happen often but as the active users being children and the edit mode being easily accessible, there could be many instances where the kids accidentally remove items. So I believe an option to reset could  save time and improve user experience.

**Comment by llaske** [comment]
@dhruvmisra once again, we don't need any new button: just close the activity, display the Calligra activity menu and click on "Start new".

**Comment by dhruvmisra** [comment]
@llaske Definitely, I understand thanks.
