### ISSUE TITLE
XO Editor Activity is Cut on Wide Desktop Windows

### ISSUE THREAD

**Issue by AndreaGon** [llaske/sugarizer#665]
XO Editor Activity does not fit on wide desktop windows. See here:

![xo](https://user-images.githubusercontent.com/44361130/76037038-bed05b80-5f80-11ea-95d9-4c192268d33a.gif)

**Comment by dhruvmisra** [comment]
Is someone working on this? I have a potential solution for it.

**Comment by AndreaGon** [comment]
@dhruvmisra Feel free :)

**Comment by llaske** [comment]
@AndreaGon I don't think it's an issue. Having colors distributed all around the screen is the spirit of the activity. Plus the user could rearrange colors if he want.
I specifically dislike your fix @dhruvmisra : most of the screen is now white, it's not the idea!

**Comment by dhruvmisra** [comment]
Sure I understand @llaske. Learning more about Sugarizer everyday with these little bugs and fixes!

**Comment by AndreaGon** [comment]
@llaske Hmmm, if this is the case, I will close this issue.
