### ISSUE TITLE
Activity Port Proposal: Hangman Game

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#666]
I wanted to work on porting the popular Sugar activity Hangman. It is a fun classic game popular among kids.

**Comment by llaske** [comment]
I don't think it has a pedagogical interest to add it.
No teacher I know asked for it.

**Comment by dhruvmisra** [comment]
@llaske Alright, is there any other activity that needs to be ported from Sugar? I'd love to work on it.

**Comment by llaske** [comment]
Yes, there is Fraction Bounce. See https://github.com/llaske/sugarizer/issues/205
