### ISSUE TITLE
Issues in game of life activity

### ISSUE THREAD

**Issue by ksraj123** [llaske/sugarizer#668]
Here are some issues found in game of life activity
- Issues with Tutorial
    - Tutorial backdrop disappears for some steps, the steps are supposed to point at the game board
![bug game of life activity backdrop dissappears in tutorial](https://user-images.githubusercontent.com/39027928/76117277-84fb6580-6011-11ea-9125-efb73e2b5fa3.gif)

- Issues with responsiveness of the activity, on mobile resolutions - 

    - The help button disappears
    - The canvas element overflows over the Generation count element.
![help button hides and the board comes over score](https://user-images.githubusercontent.com/39027928/76117931-d0624380-6012-11ea-8b3d-3b957c4a2228.png)

I am working on the issues will open associated PRs soon.

**Comment by ksraj123** [comment]
@llaske Issue with tutorial fixed in #669
![Peek 2020-03-07 02-32](https://user-images.githubusercontent.com/39027928/76122867-26d47f80-601d-11ea-9bfb-cc5b5dbfd6a0.gif)

**Comment by llaske** [comment]
Please fill an issue with several problems even if it's related to the same activity.

I don't see an issue regarding the tutorial. It's not a problem that the step doesn't point to the board. It's perfectly clear that the popup is related to the board.

I don't see an issue regarding disappearance of the help button on small screens. On small screen some compromises should be done. The disappearance of the help button is a good one.

I'm agree regarding the overflow of generation number. It could be nice to propose something better.
