### ISSUE TITLE
Include ToonTalk in Sugarizer?

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#67]
https://github.com/ToonTalk/ToonTalk looks nice

**Comment by davelab6** [comment]
https://docs.google.com/presentation/d/1JuKLZ51Y1i99dbpWV8iz-DHM735dIe_hXtgsOntu__Y/edit#slide=id.p has a bit of history

**Comment by lovemehta** [comment]
Hello,
I was thinking of working on the open issues and found this one as a good start. 
Thanks

**Comment by Swayamsvk** [comment]
Can I give it a try?

**Comment by llaske** [comment]
I think it's too complex for the target users. Don't think it's a good idea.
