### ISSUE TITLE
Dialog box has no background in Markdown

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#671]
Background of hyperlink dialog box is transparent.

![markdownBGIssue](https://user-images.githubusercontent.com/40134655/76140995-36d47980-6086-11ea-9ee6-ffbea11371b8.jpg)

I'll make a PR fixing this.

**Comment by llaske** [comment]
You're right.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/672
