### ISSUE TITLE
Markdown link opens in frame which crashes the output

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#673]
If a link is clicked in output, it tries to open in the same frame, which crashes the output for rest of the activity duration.

![markdownLinkIssue](https://user-images.githubusercontent.com/40134655/76141278-ae0b0d00-6088-11ea-969c-76f7f7f938dc.gif)

I'll open a PR fixing this.

**Comment by llaske** [comment]
Good point.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/674
