### ISSUE TITLE
Responsiveness issue in Pomodoro Activity

### ISSUE THREAD

**Issue by ksraj123** [llaske/sugarizer#675]
On mobile resolutions in landscape mode responsiveness issues can be seen in Pomodoro Activity.
The work button gets hidden behind the toolbar and scrolling needed to get to break buttons.
 
![pondora activity issue](https://user-images.githubusercontent.com/39027928/76151022-35cb3880-60d6-11ea-801a-25ea7fad546a.gif)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/676
