### ISSUE TITLE
Export in Write Activity

### ISSUE THREAD

**Issue by Hemansh31** [llaske/sugarizer#677]
The export document should I believe directly copy it to the device but what it does is save it in the journal and one has to copy it to the device from there. Even if this has to be maintained an option to download it should be displayed after Export is complete then and there and also it should be mentioned in the tutorial which it isn't
![Write Activity - Sugarizer](https://user-images.githubusercontent.com/48997514/76158020-3e079000-6137-11ea-832f-a1de33061ae8.gif)
I am Working on associated PR's

**Comment by llaske** [comment]
That's the standard way of working of activities and it's perfectly clear in the tutorial. I don't see any issue here.
