### ISSUE TITLE
Improve UI of Calculate Activity

### ISSUE THREAD

**Issue by Hemansh31** [llaske/sugarizer#678]
- Options to show, hide and clear history would I think improve the UI.

- Option to integrate all scientific functions directly to basic calculator should be there as those functions aren't accessible in fullscreen mode, Basically a scientific and basic calculator option
![Calculate Activity - Sugarizer (2)](https://user-images.githubusercontent.com/48997514/76158309-a441e200-613a-11ea-8494-b824162d7f12.gif)

Working on associated PR's

**Comment by llaske** [comment]
We don't need that. Simple is better.
