### ISSUE TITLE
TamTam Micro Activity Piano Mode Not working in Chrome in file:///

### ISSUE THREAD

**Issue by Hemansh31** [llaske/sugarizer#679]
![TTM](https://user-images.githubusercontent.com/48997514/76158466-0ea75200-613c-11ea-976c-9032b086dcee.gif)

**Comment by llaske** [comment]
Can reproduce it only when launched locally from the browser using file:///

**Comment by llaske** [comment]
Raised an error in Tone.js library [here](https://github.com/Tonejs/Tone.js/issues/628)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/28e634cce8d0f8e7a63c667c27e3690c27ca54ee
