### ISSUE TITLE
Get Things Done: Reorder Items

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#68]
http://server.sugarizer.org/activities/GetThingsDone.activity/index.html doesn't currently allow for reordering items; I suggest this is the next biggest improvement needed

**Comment by NikolayOG** [comment]
I would like to work on this. Shall I do it so that the user can drag and drop the tasks to the correct place?

**Comment by llaske** [comment]
Yes, it could be a good idea.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/ae37157933edeef46275e4bd5a1b0bb64410d02b
