### ISSUE TITLE
Add a way to restart game in Abecedarium

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#680]
In the Play section of the Abecedarium activity, when the fourth guess is ended, the activity go back to the game selection. So the user need to reselect the game to replay. Teachers ask us a way for children to replay the current game more easily.

![image](https://user-images.githubusercontent.com/981841/76161708-2bd92200-6136-11ea-91be-f803c22a55eb.png)

So, the idea is to don't go back automatically to the game selection screen and to add a button to restart the current game.

**Comment by ksraj123** [comment]
@llaske on finishing the game, maybe a congratulations message with options to either go back to the game selection or replay the currently selected game? Also, there is no scoring in this game, I guess scoring (which will depend upon the number of wrong and right choices) can be added as well and the same can be displayed on the congratulations message page. What do you think?
Working on this issue.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/681
