### ISSUE TITLE
Add a Simon mode game in TamTam activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#686]
The idea is to add a new game mode into TamTam micro activity to play to the famous [Simon game](https://en.wikipedia.org/wiki/Simon_(game)).

<img width="491" alt="image" src="https://user-images.githubusercontent.com/981841/76427499-aad79000-63ac-11ea-885a-1020c33e018c.png">

Like for the Piano mode, this new Simon mode will use the current selected instrument to play classic Simon notes.
Both notes and color should be inspired by the 4 items in the original game : E-note (blue, lower right), C#-note (yellow, lower left), A-note (red, upper right), E-note (green, upper left, an octave lower than blue).
The UI should be simple and attractive and as for other activities:

- [ ] Should be correctly integrated into Sugarizer and use buddy colors when possible.
- [ ] Should be integrated with Journal (save its context in the Journal).
- [ ] Should use localization.
- [ ] Should include a tutorial to explain the UI.
- [ ] Should be responsive (work on any screen size) and in fullscreen mode.
- [ ] Should work on any browser (Chrome, Firefox and Safari) and in Electron.
- [ ] Should not depend of an Internet connection (use local content only).
- [ ] Should work with mouse, touch and possibly keyboard.
- [ ] Every content/library used should rely on a Free Libre Open Source license.

**Comment by sarthak-g** [comment]
working on this

**Comment by ksraj123** [comment]
working on this. There is another issue #679 related to this. I think the same problem will appear in the new game mode as well unless the underlying problem is solved first.

**Comment by llaske** [comment]
@ksraj123 I think the issue #679 is related to a Tone.js issue. So yes, the same problem should be there too. BTW if it bother you during development, a work around is to develop with a running Sugarizer Server or with Electron.

**Comment by ksraj123** [comment]
@llaske Please review PR #687 - basic functional simon mode implemented.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/687
