### ISSUE TITLE
Password Tutorial targets the wrong element

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#689]
Password tutorial targets the entire row which leads to the tutorial being pushed to the side. See here:

![passwordTutIssue](https://user-images.githubusercontent.com/40134655/76543190-24a27300-64ac-11ea-8543-9909f8a9222d.jpg)

This would make for a bad user experience. I'm working on the fix.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/690
