### ISSUE TITLE
MazeWeb: Show Red Face On Start

### ISSUE THREAD

**Issue by davelab6** [llaske/sugarizer#69]
IN http://server.sugarizer.org/activities/MazeWeb.activity/index.html the starting state has a grey circle for the player and a bright flashing color for the exit. 

This is confusing because it brings attention to the exit at the start instead of the player. 

<img width="1750" alt="screen shot 2016-07-09 at 12 11 39" src="https://cloud.githubusercontent.com/assets/261579/16708847/54f8fcbe-45ce-11e6-8426-8ac8b2c82002.png">

I suggest having the red face of the player rendered in the starting state, rather than having it appear:

<img width="1752" alt="screen shot 2016-07-09 at 12 11 46" src="https://cloud.githubusercontent.com/assets/261579/16708849/57dbb340-45ce-11e6-9c77-f6db32936bf1.png">

**Comment by SudhanvaMG** [comment]
Hey , i would like to work on this .
Can you let me know how do i proceed ?

**Comment by llaske** [comment]
You had to explore the code of the activity and try to understand where is the face changing.
Send a PR when you've done

**Comment by DarkPrince304** [comment]
@llaske In case of two player, which players face should we show? Given both are of different color?

Or should the solution be to have the red colour nevertheless?

**Comment by rajeevravindran** [comment]
How about this? I've set the initial position as a red player.
![screenshot_20170313_155006](https://cloud.githubusercontent.com/assets/10564476/23850336/fbe6cb98-0804-11e7-80a5-3876745b4bc1.png)

Becomes gray after the player moves.
![screenshot_20170313_155056](https://cloud.githubusercontent.com/assets/10564476/23850357/0d4a46da-0805-11e7-9b6f-6794b4a55db1.png)

**Comment by rajeevravindran** [comment]
@llaske Worth a pull request?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/cc8fabeebc6938769e4d728efb92a3a1d9be4907
