### ISSUE TITLE
Add a Toolbar Button to mute or unmute the falabracman Game

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#691]
Add a Toolbar Button to mute or unmute the background music or sound of falabracman Game like other sugar activities have.

**Comment by llaske** [comment]
No other activities have a mute/unmute sound button.
The philosophy of Sugarizer is to let the sound control to the device.

**Comment by prakashujjwal1010** [comment]
cool. thanks for clarification.
