### ISSUE TITLE
Tutorial error in Shared Notes Activity

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#693]
When open Shared Notes Activity after ending of tutorial of home screen then tutorial of activity points to empty area for "Name in Journal" and "Share". See:
![ezgif com-video-to-gif(6)](https://user-images.githubusercontent.com/42293606/76560055-558fa180-64c6-11ea-8c63-c97815456ab6.gif)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/694
