### ISSUE TITLE
Add a feature to change difficulty of falabracman activity

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#695]
- add a feature to change difficulty of falabracman activity like easy, medium, hard.
- changing difficulty may includes changing no of obstacles and changing player's speed
- setting screen may get updated for this.

**Comment by llaske** [comment]
I don't see the interest of this. Falabracman should stay a very simple activity.
Plus, it's a young activity (not yet released), will be better to wait feedback from the field.

**Comment by prakashujjwal1010** [comment]
okay, thanks.
