### ISSUE TITLE
Text not showing under erase button in qr-code activity

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#700]
Erase button in the input area is hiding some text under it.
![Screenshot from 2020-03-14 00-38-49](https://user-images.githubusercontent.com/42679893/76653407-a10d8280-658e-11ea-99c3-3fa1b7c6f61f.png)

**Comment by Swayamsvk** [comment]
@llaske I have fixed this issue In #701 please check it and tell me if any change is required

**Comment by Swayamsvk** [comment]
@llaske I have added the features as you have suggested, please review #701 .

**Comment by Swayamsvk** [comment]
@llaske I have fixed the issues as you have suggested please merge this.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/701
