### ISSUE TITLE
Bug While Resizing game screen after resizing setting screen in Falabracman activity

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#703]
-Bug While Resizing game screen after resizing setting screen in Falabracman activity

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/40318927/76660187-53991180-659e-11ea-9970-ec95b916a9b7.gif)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/704
