### ISSUE TITLE
Implode activity for Sugarizer

### ISSUE THREAD

**Issue by abhishektanwar** [llaske/sugarizer#710]
Implode activity of sugar can be a very good addition to  Sugarizer in terms of the values it can inculcate in young students .It is a game based on 'tetris'. Implode activity can help the young ones to develop mental strength and improve their thinking abillity and help them think in different paths without actually performing actions. 
One of the biggest values it can inculcate in a young mind is the power of retention as one need to remember the sequence of steps followed in case a situation is experienced in which no further moves can be made.In that case game will have to be started from beginning and the user will have to analysed where did he/she go wrong and rectify it .

**Comment by llaske** [comment]
I'm agree. I love the Implode activity.
Currently, Sugarizer include a BlockRain activity that is a Tetris like but will be nice to have the equivalent of the original Sugar Implode activity: http://activities.sugarlabs.org/fr/sugar/addon/4086

**Comment by abhishektanwar** [comment]
Working on it . If anybody is interested in working on this I would be more than happy because currently I am working on #709 and I think this activity needs to be completed irrespective of who does it. I will share the algorithm. 
If anybody wants to work on this issue, please let me know so that I can provide you with the head start.

**Comment by Swayamsvk** [comment]
I want to work on this.

**Comment by Swayamsvk** [comment]
First, let me understand the code I will start my coding very soon. I will ask you if I need anything.

**Comment by Swayamsvk** [comment]
@abhishektanwar can you please provide me the algorithm you made. Actually it is hard to understand the code most probably after getting the algorithm may speeds things up.

**Comment by abhishektanwar** [comment]
@Swayamsvk glad to hear from you.
The idea is to start building the problems in the reverse order that is from solution to questions unlike any other problem  First, blocks of a number greater or equal to three of different colors without any other random blocks are to be developed in a random way such that when the problem is solved all the blocks are collapsed. As of now, there does not exist a unique sequence of actions made by users which can lead to the complete collapse of all blocks.
Now, we have to add random blocks in reverse order to the above set of blocks such that there exist only one unique sequence of actions that can lead to collapsing of all the blocks.

**Comment by Swayamsvk** [comment]
@abhishektanwar working on it,would ask you if I need any help.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/784
