### ISSUE TITLE
Proposal for new sugarizer activity - I know my world

### ISSUE THREAD

**Issue by ksraj123** [llaske/sugarizer#712]
The colour my world activity on sugarizer is nice but the children only learn about the position of countries through it. There are a few popular activities on sugar similar to colour my world.
- [I know America](http://activities.sugarlabs.org/fr/sugar/addon/4464)
- [I know Madagascar](http://activities.sugarlabs.org/fr/sugar/addon/4719)
- [I know India](http://activities.sugarlabs.org/fr/sugar/addon/4587)
- [I know sri lanka](http://activities.sugarlabs.org/fr/sugar/addon/4600)
- [I know Rawanda](http://activities.sugarlabs.org/fr/sugar/addon/4653)

Through the above sugar activities children learn not only about the position of their respective countries but also about various state/territories within them with detailed information about both. I think creation of a new **I know my world** activity which incorporates all existing "I know xyz" activities on sugar with added support for continents like Europe, Africa, Asia etc and new countries as well would really help children learn geography better. The name of country/continent can be selected or searched in the menu and the activity can be started on it. I think this activity would really help children learn geography and support for more countries can be added to it in future instead of creating new I know activities, eventually covering the globe.

I would like to work on this.

Requesting suggestions.

**Comment by llaske** [comment]
I do like the I know xyz activities in Sugar. BTW it's too specific to a country so it has sense only for a specific deployment and currently no Sugarizer deployment asked for it. 
Plus, regarding search for countries in a continent, the interactive mode of the Color My World already do the job today.

**Comment by ksraj123** [comment]
Ok, Thanks.
