### ISSUE TITLE
Calculate activity : Sugarizer android app

### ISSUE THREAD

**Issue by abhishektanwar** [llaske/sugarizer#716]
Seems like buttons in the bottom two rows are not accessible due to irresponsive or non-scrollable screen.

**Comment by llaske** [comment]
Hmmm. Sounds like the screen is no longer scrollable.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/981841/77223731-79568580-6b5f-11ea-930a-fc35d4dff468.png">

**Comment by utkarsh-raj** [comment]
I can't reproduce the issue. Can you tell me the configuration of the test system?

**Comment by s-mag** [comment]
I also can't reproduce this issue.
Version used: 1.3.0
Mobile used: OnePlus 6T
![20200420_142830](https://user-images.githubusercontent.com/44548987/79733937-83f96b80-8313-11ea-98a7-a233acc6de80.gif)

**Comment by llaske** [comment]
Look like it's not reproducible. @abhishektanwar, feel free to reopen the issue if it happen again.
