### ISSUE TITLE
Localization for Markdown Activity

### ISSUE THREAD

**Issue by afmachado** [llaske/sugarizer#72]
There is currently no attempt at localizing any of the text in the Markdown Activity. 

Specifically, the following files have hardcoded text on them:
https://github.com/llaske/sugarizer/blob/master/activities/Markdown.activity/lib/Markdown.Editor.js
https://github.com/llaske/sugarizer/blob/6c8472c2aa95b978cb45eabfe16f3c0c64ff1e60/activities/Markdown.activity/js/activity.js

I would like to request that these files be changed to allow for localization, since most other activities (and sugarizer itself) already allow this.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/c8163c6f907a5901723fb275519d074fa5e8a123

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/releases/tag/v0.8
