### ISSUE TITLE
Enhancement in LOL activity multiplayer mode

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#722]
If host leaves in the middle of game then game gets stuck for the connected user i.e. connected user can't continue the game. He can only press stop button.
Possible solution:
1. Game ends for connected user as well when host leaves.
2. Connected user can continue to play with computer(similar feature for host although he can start new game).
@llaske your views on this?

**Comment by llaske** [comment]
In that case, I think the user can just start a new game or just quit the activity.
Considering the duration of a LOL game, I don't think we need more.

**Comment by sarthak-g** [comment]
> Considering the duration of a LOL game, I don't think we need more.

Considering duration, 2nd solution will be of no use but I think 1st is still valid(automatic game quit).
Agree?

**Comment by llaske** [comment]
Automatically quit the game will be very disturbing for the user. I’m not in favor of that

**Comment by sarthak-g** [comment]
Okay
