### ISSUE TITLE
Falabracman only accepts a specific letter in case of repeated letters in a word

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#725]
When a word contains repeated letters, only a specific letter can be accepted and all others are treated as different letters. See here:

![FalabracmanMultipleLetters](https://user-images.githubusercontent.com/40134655/77233155-8d37d100-6bcb-11ea-8999-89d0de1684ef.gif)

![FalabracmanMultipleLetters2](https://user-images.githubusercontent.com/40134655/77233174-bf493300-6bcb-11ea-8349-65a010c34ecd.gif)

Shouldn't all repeated letters also be accepted? What do you say @llaske?
I'm working on a fix for this.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/726
