### ISSUE TITLE
Video Viewer shows tutorial for a feature not available on small screen

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#731]
Video Viewer shows tutorial for Search which is not available on the android app.

![Screenshot_20200322-211138](https://user-images.githubusercontent.com/40134655/77254390-b6696780-6c86-11ea-8360-34bc7dd5a916.jpg)

**Comment by llaske** [comment]
It's not related to Android, it's related to the size of the screen

**Comment by dhruvmisra** [comment]
That's right, I mentioned the Android as it's the platform which mostly uses those resolutions and would pertain the issue.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/732
