### ISSUE TITLE
Labyrinth shows tutorial for functions not available on small screens

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#733]
Labyrinth activity shows tutorial for Font, Increase Font and Decrease Font on small screens, specifically Android. See here:

![labyrinthButtonsIssue](https://user-images.githubusercontent.com/40134655/77412192-8e434b00-6de3-11ea-8b41-a6cb2f67359a.jpg)
![labyrinthButtonsIssue2](https://user-images.githubusercontent.com/40134655/77412207-91d6d200-6de3-11ea-881d-52556007da35.jpg)

I would actually propose keeping these functions visible on small screens as well as there is ample space to accommodate them. Moreover, font resizing would be beneficial on small screens.
I'm working on a fix.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/734
