### ISSUE TITLE
Blockrain tutorial overflows off screen on smaller screens

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#736]
Blockrain canvas tutorial overflows that even the buttons are not visible. Issue on small screens (mainly the app).

![blockrainTutIssue](https://user-images.githubusercontent.com/40134655/77416034-635bf580-6de9-11ea-802d-480c74e7bca4.jpg)

Changing the position of the tutorial dialog should fix it. I'll add a PR to fix the issue.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/737
