### ISSUE TITLE
Translating to Portuguese Brazil

### ISSUE THREAD

**Issue by blueemily** [llaske/sugarizer#74]
Hi!

I'm working with my professor, @afmachado, here in UFRGS Brazil, translating free source educating programs. We would like to translate your program. I am just new to this and have not found a string.xml file. Can you tell me how can we do this?

Best regards,

Emily

**Comment by llaske** [comment]
Hi Emily,

Thanks for your proposal, strings to translate are in the file https://github.com/llaske/sugarizer/blob/master/locale.ini . You just have to create a new section with your translation. There is a "how to" here: https://github.com/llaske/Sugarizer#localization 
If you're not familiar with JavaScript, just translate strings in the locale.ini file and I will do the JavaScript part.

Best regards.

        Lionel.

**Comment by blueemily** [comment]
Hi Lionel, I've done the update of the files. Thank you very much.

**Comment by llaske** [comment]
Nice. Could you send a PR with your change so I could integrate it in the next release ?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/releases/tag/v0.8
