### ISSUE TITLE
Last row hidden in Grid Paint

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#743]
The last row of Grid Paint canvas is mostly hidden. The result is even drastic on smaller screen where the entire last row and colour is off the screen.

![gridPaintOverflowIssue](https://user-images.githubusercontent.com/40134655/77764823-492d4c00-7063-11ea-8621-ec1a4544c594.jpg)

Smaller screens (Android):
![gridPaintOverflowIssue2](https://user-images.githubusercontent.com/40134655/77764889-695d0b00-7063-11ea-8efd-8a58ceb68b6a.jpg)

**Comment by llaske** [comment]
That's true but it's only on the current dev branch, has been fixed [here](https://github.com/llaske/sugarizer/commit/b82b050e9554df2a9d1fb099ddd120c904ace62c) in the release currently in packaging.
