### ISSUE TITLE
Wrong arrow icon in Exerciser activity

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#748]
Arrow does not change when opening palette in Exerciser activity.
![arrow down](https://user-images.githubusercontent.com/42293606/77821838-468a2f80-7113-11ea-905a-de46e7a9a0d5.PNG)

![arrow down activity button](https://user-images.githubusercontent.com/42293606/77821890-b13b6b00-7113-11ea-8bc4-4de622cb4730.PNG)

**Comment by saurabhhere** [comment]
Hi @llaske, I have checked the graphic files for the Exerciser activity but haven't found why this bug is present. Is it something related to graphics or something else? Can you please help me with what may be the reason for this, it will help me a lot.
Thanks

**Comment by llaske** [comment]
Arrow visibility is controlled by Sugar-web styles [here](https://github.com/llaske/sugarizer/blob/dev/lib/sugar-web/graphics/css/sugar-96dpi.css#L78) and [here](https://github.com/llaske/sugarizer/blob/dev/lib/sugar-web/graphics/css/sugar-96dpi.css#L284).
Don't know why it doesn't work for this specific palette and works for others.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/ExerciserReact/pull/104

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/6d5b2b08aacc1ded2674bdf663442e067706f3b3
