### ISSUE TITLE
Changing buddy colors doesn't change old instance activity colors

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#749]
After changing the buddy colors, the activities in the spiral view and Journal do not change their color. Is this the expected behavior @llaske?

![colorChangeIssue](https://user-images.githubusercontent.com/40134655/77823417-08940800-7121-11ea-95be-5431ee103c13.gif)

**Comment by ashish0910** [comment]
@dhruvmisra Yes this is expected behaviour 
You can refer to #311

**Comment by dhruvmisra** [comment]
@ashish0910 Alright thanks, I'll close this issue.
