### ISSUE TITLE
Awkward placement of Labyrinth canvas tutorial

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#758]
The tutorial is compressed to the right. The exit button is hidden in smaller resolutions.

![labyrinthTutIssue](https://user-images.githubusercontent.com/40134655/77831930-3c3e5480-7158-11ea-9382-fe5269e876bc.jpg)

Changing the placement to top will fix it.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/759
