### ISSUE TITLE
Awkward positioning of contents in the searchfield of video viewer activity

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#761]
![Screenshot from 2020-03-30 04-32-25](https://user-images.githubusercontent.com/42679893/77863440-0eccd600-7240-11ea-96d1-e8251aed388f.png)

**Comment by llaske** [comment]
Right, the text could be center vertically.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/762
