### ISSUE TITLE
Size and speed palettes of game of life activity don't works on touch screen

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#766]
the sliders of size and speed palettes of game of life activity don't works on touch screen.

**Comment by llaske** [comment]
Can't reproduce it, neither on iOS, neither on Android, neither emulated devices on the browser.

**Comment by prakashujjwal1010** [comment]
![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/40318927/78069523-dfd97000-73b7-11ea-9f31-a205a88688b8.gif)
we can move the slider but its not working actually.
even the sugarizer app which is on play store is having same problem

**Comment by llaske** [comment]
Okay. I see. Good shot.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/767
