### ISSUE TITLE
toolbar in speak activity not responsive

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#772]
Whatever could be the screen size the Stop button should always visible to be sure the user will be able to quit the activity.
but here it is not in the case of speak activity.
![Screenshot from 2020-03-31 20-07-16](https://user-images.githubusercontent.com/40318927/78039250-81969800-738b-11ea-8996-37aa45dfa9ff.png)

**Comment by llaske** [comment]
The window size you're suggest doesn't match any real device and is not in landscape mode.
As mentioned [here](https://github.com/llaske/sugarizer/issues/422), activities are not suppose to be responsive in any condition.

**Comment by prakashujjwal1010** [comment]
like in physics ([here](https://github.com/llaske/sugarizer/issues/516)) write activity etc, we have this feature,
are they having the same feature because they are having more number of toolbar buttons . 
am i right?

**Comment by llaske** [comment]
The more toolbar buttons there are, the more it's important to handle the way the window is responsive. Specifically by hiding buttons to avoid a toolbar on two lines.
BTW it doesn't change the rules: the activity should try to be responsive for a "classic" smartphone in landscape mode. If it works for the "iphone 6/7/8" device in Chrome responsive mode, that's fine.
