### ISSUE TITLE
toolbar in constellation activity not responsive

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#774]
Whatever could be the screen size the Stop button should always visible to be sure the user will be able to quit the activity.
but here it is not in the case of constellation activity.
![Screenshot from 2020-03-31 01-31-25](https://user-images.githubusercontent.com/40318927/78040131-a8090300-738c-11ea-94ef-b299f1cdcb35.png)

**Comment by llaske** [comment]
The window size you're suggest doesn't match any real device and is not in landscape mode.
As mentioned [here](https://github.com/llaske/sugarizer/issues/422), activities are not suppose to be responsive in any condition.
