### ISSUE TITLE
Alignment of help button in some activities

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#777]
Some activities have help button on the left side instead of right side (standard in sugarizer). Is there any specific reason for this?

**Comment by llaske** [comment]
No there is no good reason for that. It was not in every activities at the beginning so each contributor has choose its position.
It will be better to have it at the same position in all activities.
Same for fullscreen button (when present).
Here's the correct position for these buttons:

![image](https://user-images.githubusercontent.com/981841/78398828-0daaf880-75f4-11ea-913a-cefbb311194d.png)

**Comment by sarthak-g** [comment]
Okay, I will raise pr for correction in each activity

**Comment by llaske** [comment]
Oops, I was wrong, sorry.
I've copied the wrong capture.
The right is this one.

![image](https://user-images.githubusercontent.com/981841/78508732-652e9d00-7789-11ea-9417-b99c99f78c65.png)

The idea is to have the help button easily accessible.
I think only Video Viewer and Moon should be changed.

**Comment by sarthak-g** [comment]
Corrected in #780

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/780
