### ISSUE TITLE
excessive zoom leads to text disappearence in Calligra Activity 

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#788]
![calligra](https://user-images.githubusercontent.com/42679893/80271340-f768f780-86dc-11ea-8549-ae87ec471dbb.gif)

**Comment by Swayamsvk** [comment]
I don't know the best solution to this as limiting the magnification leads to different sizes for different letters and even shapes. If anyone can suggest something please let me know.

**Comment by llaske** [comment]
It's not a bug in my opinion: whatever you zoom there is always a time where the object will be invisible.

**Comment by Swayamsvk** [comment]
How about we add a drag feature as in shared notes activity by this way we can view the shape by just dragging the screen.

**Comment by llaske** [comment]
Could be a good idea but difficult to implement because drag is already use for drawing

**Comment by Swayamsvk** [comment]
I think you are right @llaske .
