### ISSUE TITLE
Splitbar in toolbar of Clock activity are half sized in Chrome

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#789]
Splitbar use to separate buttons in Clock activity are half sized:

![image](https://user-images.githubusercontent.com/981841/80289216-80b01680-873d-11ea-9c37-16f14ed3ec43.png)

See the difference with splitbar in Shared notes activity:

![image](https://user-images.githubusercontent.com/981841/80289272-e6040780-873d-11ea-8831-86407f439bfb.png)

It works fine in Firefox.

**Comment by dhruvmisra** [comment]
I have proposed a solution for this in #790.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/790
