### ISSUE TITLE
Canvas overflows in Game of life Activity in chrome

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#793]
Canvas overflows and "Generation" not visible for width greater than 1000px in chrome.
![CanvasOverflowsGameOfLife](https://user-images.githubusercontent.com/42293606/80697442-94210000-8af6-11ea-897a-348cf565d1ce.PNG)

**Comment by llaske** [comment]
It's not related to the width but to the ratio between width and height.
But I'm agree that the responsiveness of Generation label could be improved.

**Comment by saurabhhere** [comment]
@llaske Issue fixed in #906

**Comment by llaske** [comment]
Thanks @saurabhhere.
Sound like I forgot to mention it in the release.
