### ISSUE TITLE
Name and XO visible even after removing in Memorize Activity

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#794]
In memorize activity, more than two users are not allowed. Users are automatically removed but their name and XO icon are still present.
In the image below, "sarthakGupta" and "hellomnop" are automatically removed but their name and XO are still present.
![NameAndXOMemorize](https://user-images.githubusercontent.com/42293606/80699348-70ab8480-8af9-11ea-9c58-e1053bc36d41.PNG)

**Comment by llaske** [comment]
Good shot. You're right.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/949
