### ISSUE TITLE
calculate activity outputs error checking funtion if graph function is changed to "f(y) ="

### ISSUE THREAD

**Issue by phoenix14113** [llaske/sugarizer#797]
function f(y) { if (arguments.length != 1) { throw new SyntaxError("Wrong number of arguments in function f (" + arguments.length + " provided, 1 expected)"); } return y }

This is output if you change the graphing function f(x) to another variable f(y). Numbers and symbols output the correct, right column, formatted error handling but letters, with the exception of x, output the actual code.

**Comment by hbkaye** [comment]
Same happen if you use anything other than 'f(x)' like g(x) or x(y).
Perhaps, input value is being checked against 'f(x)' to start graph.
Need to compare input with /^[a-z]\([a-z]\)/i or something similar.

**Comment by hbkaye** [comment]
Should I fix this ?

**Comment by phoenix14113** [comment]
it would be a nice quality of life improvement if it was fixed.

**Comment by llaske** [comment]
Because the function feature is to compute the y coordinate based on x value to draw the graph, I don't see why it could be pertinent to have something else than x.

**Comment by hbkaye** [comment]
Yes, that is right.
But it can have support for functions like g(x) or y(x) perhaps.

**Comment by phoenix14113** [comment]
and even if we don't decided to have support for other functions it would still be good to display the correct error message

**Comment by llaske** [comment]
@hbkaye no it has no interest.
@phoenix14113 you're right but it should be another issue.

**Comment by phoenix14113** [comment]
ok. will do. @llaske
