### ISSUE TITLE
calculate activity outputs the incorrect error message if variable is changed in function

### ISSUE THREAD

**Issue by phoenix14113** [llaske/sugarizer#798]
function f(y) { if (arguments.length != 1) { throw new SyntaxError("Wrong number of arguments in function f (" + arguments.length + " provided, 1 expected)"); } return y }

This is output when you change the x in f(x) to any other letter. the correct error message should be "invalid left hand side of assignment operator =".

**Comment by phoenix14113** [comment]
If you enter any character except x in the f(x) graphing utility for example:
![Error step 1](https://user-images.githubusercontent.com/64759516/83555486-34d25900-a4c3-11ea-98a3-1e94aa6fb641.PNG)
you get this error message inside of the input box:
![Error step 2](https://user-images.githubusercontent.com/64759516/83555630-64816100-a4c3-11ea-94b3-8b9851e57438.PNG)
and if you press enter when this error message is inside the input box you get this:
![Error step 3](https://user-images.githubusercontent.com/64759516/83555673-7c58e500-a4c3-11ea-962d-7a4e21238107.PNG)

**Comment by llaske** [comment]
Hmmm. Very specific fix. May be it could be possible to catch error in a more generic way?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/950
