### ISSUE TITLE
Calculate activity suggestion to put axes intersecting at the origin on the graph function

### ISSUE THREAD

**Issue by phoenix14113** [llaske/sugarizer#804]
I found it confusing for there to be no axes at the origin when functions were being graphed. The numbering at the sides of the screen is fine but having lines that represent x=0 and y=0 would be nice quality of life.

**Comment by llaske** [comment]
Not sure to understand, axis are there.

![image](https://user-images.githubusercontent.com/981841/82368892-6f91b700-9a16-11ea-9f18-51fd2216f342.png)

**Comment by llaske** [comment]
Not reproductible
