### ISSUE TITLE
Private button in presence palette shares the activity

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#811]
See here:

![presence1](https://user-images.githubusercontent.com/40134655/83321350-a49ad680-a26c-11ea-8929-99474d4804c1.gif)
![presence2](https://user-images.githubusercontent.com/40134655/83321357-a8c6f400-a26c-11ea-8d1c-254f8022b1f4.gif)

It happens in all other activities using the Presence palette. The styling of the palette also becomes erratic as connected user overflows and private/share buttons aren't disabled.

The problem might be linked to the file `lib/sugar-web/presence.js` which was updated recently to display connected users.

**Comment by llaske** [comment]
Should be fixed by https://github.com/llaske/sugarizer/pull/813
Could you check on your side?

**Comment by dhruvmisra** [comment]
Yes, it works well on my side too.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/95e9cd2b0f26d48a058b01fd7928c9ee97928467
