### ISSUE TITLE
Last One Loses activity is unplayable after sharing without second player

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#815]
Once you share the activity, the computer stops playing and the game is stuck waiting for the second player.

![lolNetworkIssue2](https://user-images.githubusercontent.com/40134655/83488433-74e90a00-a4ca-11ea-9cb9-1e15790bbf75.gif)

Also if the second player leaves during a game, first player is stuck again and can only play the game after restarting the activity.

![lolNetworkIssue1](https://user-images.githubusercontent.com/40134655/83488418-6f8bbf80-a4ca-11ea-820b-ac56ab10682c.gif)

Taken cue from #722

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/889293a5447ce8cbd31d5ce88890bb62e68bc653
