### ISSUE TITLE
Timer in chess activity stops on inactive tabs 

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#828]
The timer or clock in chess activity stops inactive tabs.
steps:
1. enable clock in activity
2. switch tab or minimize it.
3. open after some time.

**Comment by llaske** [comment]
Nice shot. A perfect feature for cheaters :smile:

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/829
