### ISSUE TITLE
Certain portion of circles get hidden in Reflection Activity (Improper Responsiveness)

### ISSUE THREAD

**Issue by jaggu21** [llaske/sugarizer#835]
Little portion of circles in the Reflection Activity are getting hidden when the window size is increased. 

**Smaller window size:**
![small](https://user-images.githubusercontent.com/56889104/88206100-6669d400-cc6b-11ea-83ca-ddc576ffafb3.png)

**Same window when enlarged:**
![large](https://user-images.githubusercontent.com/56889104/88206230-92855500-cc6b-11ea-9955-c0202bbb4c28.png)

Notice that certain portion of the lower row circles are getting hidden.

In certain cases ,the lower portion of circle is completely cut off .Kindly notice the lower row circles in the following image:

![size](https://user-images.githubusercontent.com/56889104/88206512-ff98ea80-cc6b-11ea-8acc-5d2c4760af7f.png)

**Comment by llaske** [comment]
Unfortunately, Sugarizer can't be responsive for any size of device. 
General rules are fixed [here](https://github.com/llaske/sugarizer/issues/422) and hiding the toolbar using Fullscreen button is the usual work around.
In your case it seems the the window has width < 600 and height < 200 that is a very uncommon size for a real device.

**Comment by jaggu21** [comment]
Yeah indeed these window sizes are uncommon so they shouldn't create much of an issue. 
Thanks for the clarification!
