### ISSUE TITLE
Drawing in GridPaint flash the screen on some Android devices

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#847]
On some Android devices, here a Lenovo TB2-X30F on Android 6.0.1, the screen is flashing when drawing in GridPaint activity.

![lenovo_gridpaint_flashissue_app](https://user-images.githubusercontent.com/981841/92651707-3e9f0000-f2ed-11ea-9656-f1358e6aa8ef.gif)

A work around is to go back to the list of drawing then clicking again on the drawing.
The flash disappears after few seconds.

This issue start with Sugarizer v1.3.0. 
Seems related to fix for https://github.com/llaske/sugarizer/issues/342

**Comment by hharshas** [comment]
@llaske I guess this issue is completed, You should close this.

**Comment by llaske** [comment]
You're right it's an old Android version and we don't see this behavior happen again recently.
