### ISSUE TITLE
Leaving Sugarizer app without leaving current activity cause some activities to become empty

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#850]
It's possible to leave Sugarizer when an activity is still running: by closing the browser or by quitting the app.
In that case when the activity is relaunch, the content of the activity is empty.
Of course it's not a good idea for the user to leave activity on this way because it could lost its current work but having an empty context is not a good experience.

![Peek 12-09-2020 22-32](https://user-images.githubusercontent.com/981841/93004531-1f4fdf00-f548-11ea-9d5f-d2fa6358571f.gif)

It happens (at least) in Vote, Curriculum, Ebook Reader, Exerciser activities.

**Comment by llaske** [comment]
@dhruvmisra, could you have a look on it? I guess it could be solve by saving the Journal instance when the context is load.

**Comment by dhruvmisra** [comment]
Hmmm, is the journal entry modified right after accessing it from the datastore? I'm not sure why that would happen.

**Comment by llaske** [comment]
I guess it's because the Journal entry is empty.
The Journal entry is created automatically by Sugar-web when a new instance is launched. So if the instance has no opportunity to save it - usually done on Stop event - the entry content is still empty.

**Comment by dhruvmisra** [comment]
Oh right, it's a new instance. Okay I'll save the context right when the activity (new instance) is loaded.

**Comment by llaske** [comment]
Fix for Ebook Reader, Vote and Curriculum in https://github.com/llaske/sugarizer/pull/851.
A specific issue has been opened for Exerciser here: https://github.com/llaske/ExerciserReact/issues/100
