### ISSUE TITLE
Wrong poll is displayed in Vote activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#854]
When there was some creation/remove of poll, it could happens that the wrong poll is displayed when clicking on it.

Steps to reproduce:
- Create a new Vote instance
- Add a new poll labeled 6
- Add a new poll labeled 7
- Remove poll labeled 6
- Create a new poll labeled 8
- Click on poll 8, the poll 7 is displayed instead

**Comment by llaske** [comment]
@dhruvmisra I guess it's related to the unique id generated for the new poll, it should depend of the number of current poll count. So when a poll is removed then a new poll created it could reuse the same id.

**Comment by dhruvmisra** [comment]
@llaske Yes you're right, the issue was caused due to the unique ID generated being *not so unique*. Added a PR to fix it.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/a6c461aa7dd89b22a333a2f30a9129a54e77278d
