### ISSUE TITLE
Add a more sign(pic)

### ISSUE THREAD

**Issue by anukaal** [llaske/sugarizer#856]
You can add a more sign under the activity list in the main page of sugarizer . to explore more activities but now three dots jpg file is not looking more interactive 

you can add other pics in that so that people can go and check it out the other activities as well , not o ly the main page activities

**Comment by llaske** [comment]
Not sure to understand which picture your talking about.

Activities displayed in the main page are activities marked as favorite.
If there is enough room in the window, activities are displayed in a spiral:

![image](https://user-images.githubusercontent.com/981841/94067443-27ccd300-fdee-11ea-856f-013b52818d8f.png)

If the window is too small, activities are displayed in a circle and three dots are displayed to scroll:

![image](https://user-images.githubusercontent.com/981841/94067560-5ba7f880-fdee-11ea-8c5f-91b02bb420ec.png)

In the List View (click on four horizontal lines icon) you could see all activities and choose which activities are favorites and which are not.

![image](https://user-images.githubusercontent.com/981841/94067813-af1a4680-fdee-11ea-9b90-854a71f9fd4e.png)

**Comment by llaske** [comment]
Close due to lack of response.
Feel free to reopen it if need.
