### ISSUE TITLE
Allow frog to move with arrow keys in FoodChain activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#857]
In the Play game of the FoodChain activity, it's possible to move the frog using I, J, K, L keys on the keyboard.
It will be better to be able to move it using arrow keys instead.

![image](https://user-images.githubusercontent.com/981841/94335932-59f15700-ffdf-11ea-9959-69eb24321674.png)

**Comment by ricknjacky** [comment]
I'll work on this

**Comment by ricknjacky** [comment]
hi @llaske did the changes 

https://github.com/llaske/sugarizer/pull/864#issue-496744402

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/9630d2973641b13e86db7992c97fe3b794f08257

**Comment by blank-27** [comment]
can i work on this issue ?
