### ISSUE TITLE
Improve frog control using touch/click in FoodChain activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#858]
In the Play game of the FoodChain activity, it's possible to control frog move using click on touch.
It works when click/touch is done far from the frog and in the center of the screen but there is several case where it could be improved:
- Click/touch near the frog
- Click/touch near the border of the board
- Click/touch outside of the board

![Peek 26-09-2020 10-04](https://user-images.githubusercontent.com/981841/94336029-2a8f1a00-ffe0-11ea-9be0-51b410c4662c.gif)

The idea is to improve the precision of the frog control.

**Comment by Keisuki** [comment]
I don't know how to link my pull request with the issue, so I'll just post the link here:
https://github.com/llaske/sugarizer/pull/860

**Comment by llaske** [comment]
> I don't know how to link my pull request with the issue, so I'll just post the link here
Just mention the issue in the body of your PR.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/860
