### ISSUE TITLE
Stop playing a video change to fullscreen in VideoViewer activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#859]
In VideoViewer activity, there is a button to switch to fullscreen mode.
On touch screen, when you play a video then touch the close button to go back to the main screen, the fullscreen mode is activated.
It happens on touch screen only.

![Peek 26-09-2020 10-13](https://user-images.githubusercontent.com/981841/94336160-392a0100-ffe1-11ea-9f05-8ebc13f94529.gif)

**Comment by Mrhb787** [comment]
*Seems like there is a bug in script*
**I would like to work on this issue can you give me a headstart!**

**Comment by llaske** [comment]
> Seems like there is a bug in script

I don't think it's related to a bug.
I think it's related to the UI: the close dialog button is located at the same place than the fullscreen button.
So the same touch raise two events: close then fullscreen. May be it's possible to stop the propagation of the [close dialog event](https://github.com/llaske/sugarizer/blob/dev/activities/VideoViewer.activity/dialog.js#L138). Else it will be need to move the button.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/888
