### ISSUE TITLE
In FoodChain Activity, the frog currently moves using the keys "I,J,KL" & generates an unexpected behavior 

### ISSUE THREAD

**Issue by ricknjacky** [llaske/sugarizer#865]
![gif](https://user-images.githubusercontent.com/50985033/94985016-0ac39d00-0570-11eb-87ff-bd43b06ba04a.gif)

The behavior is quite random and to be honest quite confusing, However this is in reference to the edits suggested in #857 
Creating this issue, to bring light on what was additionally wrong with using I,J,K&L

**Comment by ricknjacky** [comment]
Creating a new pull request that solves this and #857 too, waiting for feedback on the same.

**Comment by ricknjacky** [comment]
#866

**Comment by llaske** [comment]
Sounds like the same issue that https://github.com/llaske/sugarizer/issues/857.
So it should be fixed now on the dev branch by https://github.com/llaske/sugarizer/commit/9630d2973641b13e86db7992c97fe3b794f08257. Could you retry with the latest dev branch?

**Comment by ricknjacky** [comment]
closing the issue thanks for the clarification here 
https://github.com/llaske/sugarizer/issues/857#issuecomment-703069302
