### ISSUE TITLE
Add a popup when image is exported in Moon activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#867]
Moon activity allow generation of the current image of the Moon in the Journal by clicking on the dedicated icon in the toolbar (to the right on the screen capture below).

![image](https://user-images.githubusercontent.com/981841/94987323-efec2b00-0565-11eb-941e-e9573535f46d.png)

It will be nice to notify the user when this export is done.
The idea is to add a popup like in the QRCode activity.

![image](https://user-images.githubusercontent.com/981841/94987549-6ccbd480-0567-11eb-827b-4ac5f768e48a.png)

The popup should be displayed using `humane` library and the message should be localized. See [here](https://github.com/llaske/sugarizer/blob/dev/activities/QRCode.activity/js/activity.js#L157) the implementation in QRCode activity.

**Comment by ricknjacky** [comment]
@llaske I'd like to work on this issue can you give me a headstart?

**Comment by llaske** [comment]
Look on the source code I've pointed and do the tutorial on localization it should give you a good introduction. Do not hesitate to ask if you've got more specific questions.

**Comment by ricknjacky** [comment]
![Screenshot (164)](https://user-images.githubusercontent.com/50985033/94992245-45e0c300-05a6-11eb-9566-0a189d3f2fec.png)
I did as you advised me to. I now have an understanding of Localization and I refereed to the QR Code example, for some reason, When I run the activity(MoonActivity) now I am not getting the usual output we get, It's just a blank screen 

Can you please help me out here a bit? What mistake have I done and where should I improve upon?

**Comment by llaske** [comment]
`humane` library is not included in the activity, you should include the `js` file and the `css` file.
Plus you should reference it in the `define` section like explained in the tutorial [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial/VanillaJS/step2.md).
Then you will have to create a new string for the message in the `.ini` file.
I suggest you to complete the whole [tutorial](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial/VanillaJS/tutorial.md), it will help you a lot.

**Comment by ricknjacky** [comment]
I will rectify the mistakes and covey the new changes and yes will go through tutorials again 🙏 thanks for guiding 😊

**Comment by ricknjacky** [comment]
![Screenshot (166)](https://user-images.githubusercontent.com/50985033/95009908-0916d980-0643-11eb-8295-dab702fefc88.png)

@llaske I have did as you advised me to, I have added the  changes in .ini file and also included the js and html files 

I also have made one separate modal button project, that is just a simple popup on button click project. However here I am struggling a bit; please guide me, I am new to this 

ps:- adding the zip file of the separate project that serves the same functionality 
[modal.zip](https://github.com/llaske/sugarizer/files/5322819/modal.zip)

**Comment by llaske** [comment]
You should not just add `humane` in the define section, you should also add a `humane` parameter to host it.
Compare your code to the tutorial and to the QR Code activity to see differences.

**Comment by ricknjacky** [comment]
Thanks for guiding @llaske made changes

**Comment by ricknjacky** [comment]
#876 solves this, @llaske please review

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/882
