### ISSUE TITLE
Add a popup when image is exported in Shared Notes activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#868]
Shared Notes activity allow generation of the current work in the Journal by clicking on the dedicated icon in the toolbar (to the right on the screen capture below).

![image](https://user-images.githubusercontent.com/981841/94987639-1612ca80-0568-11eb-8824-a8db71b0a476.png)

It will be nice to notify the user when this export is done.
The idea is to add a popup like in the QRCode activity.

![image](https://user-images.githubusercontent.com/981841/94987549-6ccbd480-0567-11eb-827b-4ac5f768e48a.png)

The popup should be displayed using `humane` library and the message should be localized. See [here](https://github.com/llaske/sugarizer/blob/dev/activities/QRCode.activity/js/activity.js#L157) the implementation in QRCode activity.

**Comment by ricknjacky** [comment]
91750d0870c0cf2cf5cfc293b83d993593e8d43c

fixed this in here, please review

**Comment by ricknjacky** [comment]
@llaske please review changes

**Comment by ricknjacky** [comment]
#877 PR solves this issue

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/883
