### ISSUE TITLE
Add a popup when image/sound is exported in Abecedarium activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#870]
Abecadarium activity allow export of an image or a sound in the Journal by clicking on the dedicated icons in the toolbar (to the right on the screen capture below).

![image](https://user-images.githubusercontent.com/981841/94987767-152e6880-0569-11eb-904b-4b3fa1212b87.png)

It will be nice to notify the user when this export is done.
The idea is to add a popup like in the QRCode activity.

![image](https://user-images.githubusercontent.com/981841/94987549-6ccbd480-0567-11eb-827b-4ac5f768e48a.png)

The popup should be displayed using `humane` library and the message should be localized. See [here](https://github.com/llaske/sugarizer/blob/dev/activities/QRCode.activity/js/activity.js#L157) the implementation in QRCode activity.

**Comment by ricknjacky** [comment]
fixed, waiting for a feedback

**Comment by ricknjacky** [comment]
#879 fixes this

**Comment by ricknjacky** [comment]
![image](https://user-images.githubusercontent.com/50985033/95646151-26d0bc80-0ae3-11eb-8afb-4c64d03737ca.png)


I have to add the humane library in this file and particularly call it in the highlighted part of the code ?

**Comment by llaske** [comment]
Hmmm. In this activity all define are load one time [here](https://github.com/llaske/sugarizer/blob/dev/activities/Abecedarium.activity/js/activity.js#L3) and store in the `Abcd` global variable. I think it's better to do the same for the `humane` library.

**Comment by RinkiyaKeDad** [comment]
Hey @llaske! I'm new to Sugarizer development and would like to take this issue up. @ricknjacky are you still working on it? If yes would you like some help?

**Comment by llaske** [comment]
Hi @RinkiyaKeDad, sure you can complete the current work by @ricknjacky. That's how open source works!

**Comment by ricknjacky** [comment]
>@ricknjacky are you still working on it? If yes would you like some help?

@RinkiyaKeDad  
Sorry for the late reply, I just lost track of this one, and recently I've been busy with exams at my University. 
this issue is solved pls refer #889 { I had some ambiguity pertaining to testing the changes in this activity, though that's solved now}

>I'm new to Sugarizer development and would like to take this issue up. 

Even my experience with the codebase is pretty nascent, maybe we should explore the platform and it's codebase a bit more so that we don't make silly mistakes(like I did above) and help each other out 😃

**Comment by ricknjacky** [comment]
@llaske #889 solves this issue, I tested (rightly this time) the changes. 
Pls review

**Comment by RinkiyaKeDad** [comment]
> this issue is solved pls refer #889 { I had some ambiguity pertaining to testing the changes in this activity, though that's solved now}
> 
> >

Hey @ricknjacky thanks for letting me know. Would definitely like to collaborate with you on solving some other issue!

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/889
