### ISSUE TITLE
Typo in Step 2 of Tutorial 

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#890]
In the heading of Step 2 'Customize' is spelled as 'Ccustomize' ref. https://github.com/saurabhhere/sugarizer/blob/master/docs/tutorial/VanillaJS/step2.md#step-2-ccustomize-icon-and-content

![Screenshot from 2020-10-17 01-00-48](https://user-images.githubusercontent.com/60233336/96302327-43568280-1016-11eb-8610-a454fcf2bc55.png)

**Comment by llaske** [comment]
Good shot.
Same problem in Vue.js tutorial so I've renamed your issue.

**Comment by llaske** [comment]
Closed in https://github.com/llaske/sugarizer/pull/891
