### ISSUE TITLE
Actual File Structure of ActivityTemplate is Different than what it is shown in Tutorial

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#892]
### Actual File Structure of template is different from what shown in photo of File Structure in Step 1 in Tutorial

**In Vanilla JS Tutorial** (ref. https://github.com/llaske/sugarizer/blob/master/docs/tutorial/VanillaJS/step1.md#file-structure )

Shown File Structure: 
![Screenshot from 2020-10-17 16-53-31](https://user-images.githubusercontent.com/60233336/96336235-ea313200-109b-11eb-94a1-fa575a49d311.png)

Actual File Structure (as in activities/ActivityTemplate/VanillaJS) : 

![Screenshot from 2020-10-17 17-03-54](https://user-images.githubusercontent.com/60233336/96336249-0f25a500-109c-11eb-8eaf-f9a5085b70ea.png)

Similarly **in VueJs Tutorial** (ref. https://github.com/llaske/sugarizer/blob/master/docs/tutorial/VueJS/step1.md#file-structure)

Shown File Structure:

![Screenshot from 2020-10-17 16-59-41](https://user-images.githubusercontent.com/60233336/96336269-37150880-109c-11eb-9372-2aab81198bec.png)

Actual File Structure (as in activities/ActivityTemplate/VueJS) :

![Screenshot from 2020-10-17 16-59-06](https://user-images.githubusercontent.com/60233336/96336291-557b0400-109c-11eb-84e1-aad524f6303d.png)

**Comment by saurabhhere** [comment]
Can I work on this?
Thanks :)

**Comment by llaske** [comment]
Hmmm. The file structure is very similar. There is very limited difference.
I don't think it could be confusing for users.

**Comment by saurabhhere** [comment]
That's totally fine..I was just going through the steps and found this so I thought to discuss it with you.
You can close this issue if you want.
