### ISSUE TITLE
Option in Paint Activity to export the current drawing to the journal as an image

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#911]
It would be a nice feature if we have a button to export the current drawing in Paint activity to the journal as an image ( like we have in Moon Activity) in JPEG or PNG format.
for this, a simple toolbar button would work.
The user/child can later use his/her drawing and can import it to various other activities like Write Activity, Curriculum Activity, etc. from the journal.

**Comment by llaske** [comment]
In fact, it's already possible to import directly a Paint content into an activity.
Fototoon activity implement it [here](https://github.com/llaske/sugarizer/blob/dev/activities/Fototoon.activity/js/activity.js#L106). It take no more than 2 lines of code.
So IMHO the question is more to update activities where importing Paint content make sense than adding one - more - toolbar button in Paint to export content as an image.

**Comment by prakashujjwal1010** [comment]
yes, agreed.
But the export tool button was also useful to save the drawing in form of image for more general use ( like downloading image to device directly and using that image off the sugarizer platform etc)
However, your "updating activities rather than adding one more toolbar button" point makes sense to me.

**Comment by llaske** [comment]
Okay you're right. I will try to do some space later. May be by grouping some icons in palettes.
I've commented your PR.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/912
