### ISSUE TITLE
Stop button is not fully responsive in Clock Activity

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#924]
Stop button hides if the window size is **less than 620px in width**.

Preview :

![Screenshot from 2021-01-23 23-50-57](https://user-images.githubusercontent.com/60233336/105610540-187a8800-5dd6-11eb-911d-c9c1cba1e722.png)

**Comment by llaske** [comment]
Yes but it should be responsive only in landscape mode.
See https://github.com/llaske/sugarizer/issues/422 for more detail on responsive requirement in Sugarizer.

**Comment by saurabhhere** [comment]
Thanks for sharing the responsive requirements in Sugarizer.
