### ISSUE TITLE
Add a popup when image is exported in Planets Activity

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#927]
![Screenshot from 2021-02-18 15-11-50](https://user-images.githubusercontent.com/60233336/108337906-a9892700-71fb-11eb-86d6-f6b05b0023d6.png)

Popup can be added to notify the user about the planet image exported

**Comment by ricknjacky** [comment]
Nice, quite similar to #867 #868 #869 and #870 missed this activity back then.

**Comment by llaske** [comment]
Yes sure. A popup should be displayed at end.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/928
