### ISSUE TITLE
Palettes not responsive in Dollar Street Activity

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#929]
Thing Palette and Region palette are not fully responsive

Preview :

![Screenshot from 2021-02-18 16-24-47](https://user-images.githubusercontent.com/60233336/108346859-da6e5980-7205-11eb-87aa-dd809a2bc4f5.png)

**Comment by llaske** [comment]
Good point.
Thanks for your reactivity.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/930
