### ISSUE TITLE
Add background to Sugarizer home screen

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#931]
We can add an option to change the Sugarizer home screen background-color to other solid colors or images.

**Comment by llaske** [comment]
Hmmm. I'm not a big fan of this Sugar feature.
I think that it's better to keep the Sugar UI as simple as possible. So I'm more comfortable with a black&white UI than by a colorful one.

Plus, original [Sugar Design Guide](https://wiki.sugarlabs.org/go/Human_Interface_Guidelines) mention some inspiring guidelines that continue to guide me:

> Using the interface without requiring the ability to distinguish color (a significant portion of the population has some level of color blindness)

> All of the activities, objects, and comments belonging to a child take on her own colors—even when they appear on the laptops of other children on the mesh—forming a visual identity that supplements her name and attributes. 

> To maintain a degree of purity to this system, interface elements, buttons, and other icons that belong solely to the activity and not to any particular child should remain in grayscale to the extent possible. While removing color as a primary visual clue may seem counter-intuitive, it does encourage the icon's form to clearly indicate its function.

**Comment by saurabhhere** [comment]
That makes sense. Thanks for sharing Sugar Design Guide.
