### ISSUE TITLE
Sound and Video recording in Record activity don't work on Android/iOS

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#932]
On Android and iOS, features to record sounds and videos don't work. Nothing happen when clicking on matching button.

![image](https://user-images.githubusercontent.com/981841/109067643-136b6a00-76ef-11eb-8453-f57d37338197.png)

This feature works in the browser and in Windows/MacOS/Linux.

**Comment by llaske** [comment]
Sounds related to missing of `cordova-plugin-media-capture` plugin.
Fix in progress on https://github.com/llaske/sugarizer/tree/feature/cordova10

**Comment by sarthak-g** [comment]
@llaske ,
How can we add a plugin and test it with sugarizer activity (for ex: media capture plugin in record activity).

**Comment by llaske** [comment]
@sarthak-g you could use [Sugarizer APK Builder](https://github.com/llaske/sugarizer-apkbuilder) with the image [llaske/sugarizer-apkbuilder:cordova10](https://hub.docker.com/layers/140250005/llaske/sugarizer-apkbuilder/cordova10/images/sha256-77f61cc4466de1b5d2eef76a2446c1dda99a1af2488c4d6b136a50cdab723b74?context=explore) instead of llaske/sugarizer-apkbuider:latest.

**Comment by sarthak-g** [comment]
@llaske  I mean, how can we use sugarizer as cordova project so that I can add any new plugin in it (with 'cordova plugin add' command). Right now when we do 'cordova plugin list' in sugarizer directory and cordova-plugin-sugarizeros directory, both shows they are not cordova based project.

**Comment by llaske** [comment]
If you want to change Cordova settings or build options, use Sugarizer APK Builder but change the entry point to open a bash instead of launching build process:

```
sudo docker run --rm -it \
	 -v `pwd`/sugarizer:/sugarizer \
	 -v `pwd`/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros \
	 -v `pwd`:/output \
         --entrypoint /bin/bash \
         llaske/sugarizer-apkbuilder:cordova10
```

It launch a command line into the docker so you're free to update the build environment. Then you could launch the `./make_android.sh` (the default entry point for the image) to start generation.

**Comment by saurabhhere** [comment]
Hi @llaske @sarthak-g,
I am able to generate apk using Sugarizer APK Builder and llaske/sugarizer-apkbuilder:cordova10 but facing a few issues. Those are:
1. In which directory we have to use Cordova command like `cordova add plugin`, currently for llaske/sugarizer-apkbuilder:cordova10 and llaske/sugarizer-apkbuilder:latest it is showing "not a Cordova based project".
2. After adding the plugin how do we have to test it? Do we have to generate apk again using the docker image to test changes? 
3. If yes, How to run that apk? Do we have to use emulator to check changes or is there any other method to check changes for android/ios?
It will be of great help to me if you can guide me.
Thanks :)

**Comment by sarthak-g** [comment]
Hi @saurabhhere ,
Below is the method which I followed for testing.
 
> 1. In which directory we have to use Cordova command like `cordova add plugin`, currently for llaske/sugarizer-apkbuilder:cordova10 and llaske/sugarizer-apkbuilder:latest it is showing "not a Cordova based project".

You can simply add plugin with spec(version no.) in [config.xml](https://github.com/llaske/sugarizer/blob/master/config.xml) file.
Ex- for adding media capture plugin, add this line to config file:
`<plugin name="cordova-plugin-media-capture" spec="3.0.3" />`
After saving, when you will build apk, it will automatically install plugin.


> 2. After adding the plugin how do we have to test it? Do we have to generate apk again using the docker image to test changes?

Yes

> 3. If yes, How to run that apk? Do we have to use emulator to check changes or is there any other method to check changes for android/ios?

After building apk, you can install it in your phone and test it. If you have to check console messages, you can do that through USB debugging.
Steps:
1. Enable USB debugging in your phone. Connect your phone to desktop via USB.
2. Go to chrome browser in desktop.
Type: "chrome://inspect" in URL and enable "discover USB devices" option.
3. Run apk in phone and you can see your device with apk name under "Remote target" section in chrome desktop. Click on "inspect" and you can see console messages.

**Comment by saurabhhere** [comment]
@sarthak-g Thank you for your clear and helpful explanation.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/b628ec0a24fa925b9e1081b48a3f117fdad70578
