### ISSUE TITLE
Video not responsive in Video Viewer Activity 

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#933]
Video height exceeds background height in iPhone 6/7/8 landscape mode due to which overflow occurs in the y-direction.

Preview:

![VideoActivity](https://user-images.githubusercontent.com/60233336/109533214-fdd7b500-7adf-11eb-83fe-bd0ee96bbee9.gif)

**Comment by llaske** [comment]
Yes, you're right.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/934
