### ISSUE TITLE
The way to launch Sugarizer locally with Chrome has changed

### ISSUE THREAD

**Issue by ricknjacky** [llaske/sugarizer#937]
A recent discussion on sugarlabs mailing list has rightly brought this to our attention that the path{as mentioned in markdown files} via which we open sugarizer in our browser is actually incorrect.

Even I faced this issue where, upon running the following command:

`chrome --allow-file-access-from-files  index.html `

A blank page opens up, 

![Screenshot (593)](https://user-images.githubusercontent.com/50985033/111066016-dbcc3280-84e2-11eb-8ea7-ced18167d1e7.png)

to tackle this I always opened the index.html file navigating into the directory where it resides. This is however a heuristic approach and I presume not the right way to access sugarizer in browser locally.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/938
