### ISSUE TITLE
Link in Record Activity Readme Not working

### ISSUE THREAD

**Issue by aditya113141** [llaske/sugarizer#944]
The link - https://play.google.com/store/apps/details?id=com.cyngn.cameranext in the [Record Activity](https://github.com/llaske/sugarizer/tree/master/activities/Record.activity) is not found. Maybe it is outdated and needs update.

**Comment by llaske** [comment]
This URL is referenced here: https://github.com/llaske/sugarizer/blob/dev/activities/Record.activity/README.md 

BTW I'm not sure this advice is still useful.

**Comment by saurabhhere** [comment]
@llaske I think Cyanogen Camera is removed from the google play store, that's why the link is not working.

**Comment by llaske** [comment]
Ok so I think we could remove the advice from the README file.
