### ISSUE TITLE
Default position of scrollbar (top)  after everytime an activity is quit.

### ISSUE THREAD

**Issue by shivamrai1904** [llaske/sugarizer#945]
Rather than displaying  the activity list from top (by default) after every time we quit an application , the activity list is to be displayed at the point till the place up to where it was already scrolled. 
I thought for this as when i was trying all activities one by one in the activity list , when i reached to activities present in the last of activity page each time when i quit an activity i was by default directed to top of activity list . So for going to the activity next to previous activity i would have had to scroll again to bottom.

**Comment by llaske** [comment]
Yes, you're right.

**Comment by renneytj** [comment]
Can I work on this enhancement or is someone currently working on this?

**Comment by llaske** [comment]
@renneytj sure. Let's go.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/948

**Comment by llaske** [comment]
@shivamrai1904, please don't close the issue.
Issues are closed only when a new release is out.

**Comment by shivamrai1904** [comment]
Sorry sir,
I wasn't aware of this thing.
I will reopen it.

**Comment by shivamrai1904** [comment]
Fine you did it.
