### ISSUE TITLE
the hamburger button should have a toggle feature for list view

### ISSUE THREAD

**Issue by rahulkiller104** [llaske/sugarizer#959]
![WhatsApp Image 2021-05-29 at 1 16 58 PM](https://user-images.githubusercontent.com/56788144/120062801-9818ac00-c081-11eb-91f2-cf389d275edd.jpeg)

list view button should worked as hamburger toggle because when i started this app ,i am expecting for this behaviour.

**Comment by llaske** [comment]
Sugar platform use it's own UI concepts.
It could be disturbing for adults familiar with other concepts but it's very easy to understand by children.

**Comment by rahulkiller104** [comment]
@llaske  thank you for explaination
