### ISSUE TITLE
Broken Link in Step 0 of Tutorial

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#961]
![Screenshot from 2021-06-02 00-19-42](https://user-images.githubusercontent.com/60233336/120375504-81e84580-c338-11eb-8bb5-65be3aa67313.png)

`README.md` link is Broken in Step 0 of both VanillaJS and VueJS tutorial.

**Comment by llaske** [comment]
You're right. It should be a link to the `Sugarizer Application` paragraph of the `README.md` file at the root of the repo.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/962
