### ISSUE TITLE
Overlapping of icon-background on hover

### ISSUE THREAD

**Issue by rucha0702** [llaske/sugarizer#974]
web-activity-icons overlap a little with the icons near them on hovering.

![sug1](https://user-images.githubusercontent.com/77936051/150927352-75eb6638-9889-496a-b5a5-f7b113ec0870.JPG)     ![sug2](https://user-images.githubusercontent.com/77936051/150927357-2714217f-d917-4566-8d41-cc2e49c0533d.png)             

![sug3](https://user-images.githubusercontent.com/77936051/150927364-037aebc0-8dab-48ad-b438-bcfbe213e097.png)

However, it looks fine if the border-radius is set to 50%

![ans1](https://user-images.githubusercontent.com/77936051/150927797-dbd50f73-f514-4c7d-9e07-60c86ed03cdb.png)

https://user-images.githubusercontent.com/77936051/150928724-56c16ebb-5edc-4cd9-b03b-96535c25aac8.mp4

I would be happy to create a PR if the issue is approved.

**Comment by llaske** [comment]
You're right there is an overlap on icons in "circle mode" (i.e. when there is no size to draw all icons in the same page as a spiral).
There is no overlap in spiral mode.

![Peek 30-01-2022 10-39](https://user-images.githubusercontent.com/981841/151694562-0c5a5e40-d279-4251-bce2-39dd32342496.gif)

I don't like the idea to change border radius, it's not consistent with the Sugar UI.
May be the idea could be to add spaces between icons in circle mode.

FYI all magic regarding spiral/circle mode happen [here](https://github.com/llaske/sugarizer/blob/dev/js/homeview.js#L218).

**Comment by rucha0702** [comment]
Hey, so I went through the homeview.js file you mentioned above and found a constant by the name of iconSpacingFactor over 
 [here](https://github.com/rucha0702/sugarizer/blob/master/js/constant.js#:~:text=constant.iconSpacingFactor%20%3D%201.1%3B) that defines the spacing. After a small change in its value, it looked like this.

Before:
![before](https://user-images.githubusercontent.com/77936051/151918449-04d7c0be-6180-485b-aa24-d3d1d595e4cc.JPG)

After:
![between](https://user-images.githubusercontent.com/77936051/151918470-671c1e67-b9dd-4be8-8d6d-ef809e0167e5.JPG)

Am I doing it right?

**Comment by llaske** [comment]
> Am I doing it right?
Just changing this value will probably affect spacing for both spiral and circle mode.
It will be better to find a solution to fix only the circle mode issue.

**Comment by rucha0702** [comment]
> > Am I doing it right?
> 
> Just changing this value will probably affect spacing for both spiral and circle mode. It will be better to find a solution to fix only the circle mode issue.

Oh okay, I'll try finding a solution just for the circle mode.

**Comment by AnandChourasia007** [comment]
Hey @llaske , I think I fixed this issue without affecting the spiral design. 
Before
![Before fix](https://user-images.githubusercontent.com/89119829/155729019-46229af0-0c29-4c6b-957f-6623ad77221b.jpg)
:
After
![Hover overlap fixed without affecting the spiral design](https://user-images.githubusercontent.com/89119829/155729049-09c1d8e8-08e2-4643-b2cc-6fd65c160102.jpg)
:
Spiral mode view after changing circular mode view
![Spiral view after making changes to the circular view](https://user-images.githubusercontent.com/89119829/155729133-45f75852-e9a2-462f-88ee-7fef0a39bb9b.jpg)
:
Is this good?

**Comment by llaske** [comment]
@AnandChourasia007 Sounds good.
Please send a PR so I will be able to review it.

**Comment by AnandChourasia007** [comment]
@llaske I have submitted the PR to the repo from which I had forked which was sugarlabs/sugarizer. After that I saw that most PR have been made to your repo ilaske/sugarizer. Is this fine or should I fork from your repo and submit my PR ?

**Comment by llaske** [comment]
@AnandChourasia007 the latest repo is https://github.com/llaske/sugarizer . Please send your PR on the dev branch.

**Comment by AnandChourasia007** [comment]
Yeah sure! Sorry for the trouble.

**Comment by AnandChourasia007** [comment]
Hey @llaske, after making the fix, to how much extent should I check if the hover effect has been fixed? I mean do I have to ensure that this fixes hover effect all the way down upto mobile phones screen dimensions? Taking mobile responsiveness into account I mean. Because that would require resizing appropriately the inner two icons as well.
This is the current extent to which there is no overlap after fixing:
![Fix attempt 2](https://user-images.githubusercontent.com/89119829/155835043-ec4eb1c7-b0d7-41a6-b9a3-1cdea1244c21.jpg)
Is this good? Or should I fix for even more tighter screens.
