### ISSUE TITLE
UI improvement in 'Cloze Text' exercise button of 'Exerciser Activity'

### ISSUE THREAD

**Issue by S-kus** [llaske/sugarizer#975]
In the "Cloze Text" exercise of **Exerciser Activity** the `Add Blank` button has no margin, as shown:

![Screenshot from 2022-02-10 19-50-25](https://user-images.githubusercontent.com/86892991/153434283-ea89b615-0bef-4159-bbe7-77178a53fb37.png)

After adding some margin it looks better than earlier, As shown:

![Screenshot from 2022-02-10 20-18-10](https://user-images.githubusercontent.com/86892991/153434225-37fb61a6-0abe-4997-9638-67203f2f4d3d.png)

**Comment by S-kus** [comment]
Hey, @llaske Could you please review it?

I also find some more issues with this activity on different screens i.e. related to responsivity. Can I list them and raise an issue for that? 
Thank you!

**Comment by llaske** [comment]
You're it will be better to add a margin.
BTW I suggest that you declare this issue in the Exerciser repo [here](https://github.com/llaske/ExerciserReact/issues).

**Comment by S-kus** [comment]
Okay Sure @llaske I will do changes and raise the required pull request in the given repo.
