### ISSUE TITLE
Improve calculator screen responsivity

### ISSUE THREAD

**Issue by codebloded** [llaske/sugarizer#982]
Screenshot below :arrow_down: 
we just have to set the width of container under media query

![WhatsApp Image 2022-02-28 at 3 10 45 AM](https://user-images.githubusercontent.com/48005711/155901078-831e342c-5e2d-4d6e-8d3e-d5dc1c4fb072.jpeg)

**Comment by codebloded** [comment]
@llaske  I did the changes and , this issue is done .! 
have a look on the pull request

**Comment by llaske** [comment]
Sugarizer is not responsive in every case. Specifically the Window width should be greater than Window height. Read https://github.com/llaske/sugarizer/issues/422 for more.
BTW you're right, there is room for improvement.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/0cd094b944cce8d2154cee7807e3ad281d82b52e

**Comment by llaske** [comment]
@codebloded issues must not be closed before a release include it
