### ISSUE TITLE
Dollar street activity not loading.

### ISSUE THREAD

**Issue by AnandChourasia007** [llaske/sugarizer#985]
On clicking on the dollar street activity icon, a new page begins loading. But the loading never completes and an error is logged in the console, 'HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE'.

![Dollar street activity not loading](https://user-images.githubusercontent.com/89119829/156037755-61ff8cf3-7853-4da6-9e9c-d22e864520c2.jpg)

However, the buttons 'filter by region' and 'see families' work perfectly fine.

https://user-images.githubusercontent.com/89119829/156038671-a04cae64-2553-4f0d-ae6f-ca4ee77e38ab.mp4

Also, the slider boundary values in the 'filter by income' button are set to NaN.
![Slider limits issue](https://user-images.githubusercontent.com/89119829/156037787-b2824bf5-7657-47a1-b851-9712cecded0a.jpg)

**Comment by codebloded** [comment]
@AnandChourasia007  hey, are you working on this issue?

**Comment by llaske** [comment]
@AnandChourasia007 Hmmm, you're right. I guess that something has changed in the API.

**Comment by AnandChourasia007** [comment]
> @AnandChourasia007 hey, are you working on this issue?

Umm, I cannot work on this for the next week at least(due to my mid semester exams). 😪
So feel free to try and fix it.

**Comment by codebloded** [comment]
> @AnandChourasia007 Hmmm, you're right. I guess that something has changed in the API.

Yes @llaske  when i backtrack this thing , i found api isn't working properly for this thing, there is an function inside apiref, which return  NaN instead of number

**Comment by llaske** [comment]
@codebloded something similar happens last year (see [here](https://github.com/llaske/sugarizer/issues/940)).
To fix it, the idea is to debug how the [original website](https://www.gapminder.org/dollar-street) works and try to do the same.

**Comment by AnandChourasia007** [comment]
> > @AnandChourasia007 Hmmm, you're right. I guess that something has changed in the API.
> 
> Yes @llaske when i backtrack this thing , i found api isn't working properly for this thing, there is an function inside apiref, which return NaN instead of number

The function returns NaN because the api used in Sugariser for this activity doesn't exist anymore. The new API will have to be integrated now I think.
![dollarstreet email response](https://user-images.githubusercontent.com/89119829/156707411-7010dfd4-fd47-498b-b035-d35d53321392.jpg)

**Comment by llaske** [comment]
@AnandChourasia007 There is no documentation about the API because it's not directly intended to be shared. To create the DollarStreet activity we've just done reverse engineering - with the authorization of Gapminder - on the current website to understand how it works. 
So to fix the issue, the same work should be done/adapted.

**Comment by AnandChourasia007** [comment]
Oh I see

**Comment by dhwaj1902** [comment]
Hi, I was debugging the dollar street activity I found that this API ``https://ds-dev.dollarstreet.org/dollar-street/v1/`` is no longer exists, and this API is used to get ``street-settings``, ``languages``, ``region-filter`` and ``things-filter``. The region and things filter can be done with this ``https://api.dollarstreet.org/v1/`` API, while for settings and language we need to hard code the things.

**Comment by llaske** [comment]
Yes you're right the API `https://ds-dev.dollarstreet.org/dollar-street/v1/` no longer work.

BTW I don't see any mention of `https://api.dollarstreet.org/v1/` API call. It look like values for `street-settings`, `languages`, `region-filter` and `things-filter` are now directly included in the HTML page:

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/981841/158603216-eec30e03-acdf-438c-b563-1ca042d146dc.png">

May be we could extract them manually (at first) to fix the issue?

**Comment by llaske** [comment]
Help is still wanted here.

**Comment by llaske** [comment]
Fix in https://github.com/llaske/sugarizer/commit/2f5026dfd1bbfe4475030e8761a75dcc8dbd9494
