### ISSUE TITLE
In Dollar Street activity family details are not responsive 

### ISSUE THREAD

**Issue by codebloded** [llaske/sugarizer#991]
I have found an unresponsiveness in dollar street activity , family details in not responsive 
here is the screen shot for the same :arrow_down: 
@llaske  have a look on it
 
![xx](https://user-images.githubusercontent.com/48005711/156650803-4bd5d772-41b8-4726-8214-20005f2b1e07.jpeg)

**Comment by codebloded** [comment]
@llaske  i fixed this issue and doing a pull request :smiley:

**Comment by llaske** [comment]
Sugarizer is not responsive for every window size. See [here](https://github.com/llaske/sugarizer/issues/422) for more.

**Comment by codebloded** [comment]
> Sugarizer is not responsive for every window size. See [here](https://github.com/llaske/sugarizer/issues/422) for more.

so, should i work on responsiveness of sugarizer or not?

**Comment by codebloded** [comment]
Okay now i got it.

**Comment by AnandChourasia007** [comment]
Hey @codebloded , will you please close this issue, since its not required to be fixed.

**Comment by codebloded** [comment]
Sure
