### ISSUE TITLE
Improve some styling or UI of calculator activity

### ISSUE THREAD

**Issue by aman-netizen** [llaske/sugarizer#993]
Hello sir , I go through calculator activity and I found some issues like some buttons and not visible (or it is to down) and history of previous operations are also look messy 

![image](https://user-images.githubusercontent.com/82169120/156697127-d46b5222-c57d-40c4-ba2a-a2a9aaf56f2c.png)

I improve this issue in PR #988.

**Comment by llaske** [comment]
Hmmm. What is your screen size? It look like you've got a very large screen.
I'm not sure we could have this sort of screen for a child.

**Comment by aman-netizen** [comment]
Sir screen size is 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/82169120/156870507-cc2875ec-4e7c-4b7e-a9a9-387a61046944.png">

Sir I have added some other things like center the calculator input thing and history of previous operation down . Sir give me some suggestions on that so I improve it further better.

**Comment by llaske** [comment]
@aman-netizen I've commented your PR.
Please avoid to implement multiple features/fixes in the same result.
It's easier for us if you propose one issue at a time then wait for our answers before implementing PR.

**Comment by aman-netizen** [comment]
Sorry sir from next time I make sure to fix one changes at a time.
