### ISSUE TITLE
Add some more components or features in planets activity 

### ISSUE THREAD

**Issue by aman-netizen** [llaske/sugarizer#994]
Sir I go through planets activity and it consist of 8 planets with there details, I was thinking to add more thing in that like some galaxies , moon or some stars with there details . If you like this idea then I can work on this.

**Comment by llaske** [comment]
Moon has already a dedicated activity (Moon activity).
Stars and galaxies could already be explored in the Constellation activity.

**Comment by aman-netizen** [comment]
Okay sir , actually I haven't explored that activities yet.
